#%RAML 1.0 DataType
description: A unique identifier, used in combination with the SKU, so that future requests with the same combination have the same result.
example: 82251928-8863-488e-840b-2aebd10b57ba
type: string
