#%RAML 1.0 DataType

description: Enum allowing indication of a group or a location using an enum

type:
  description: The type of the id to be supplied which could be either 'location' or 'group'
  type: string 
  enum: [location, group]
  example: location
