#%RAML 1.0 DataType
description: A full location group consisting of the group ID and its assigned locations.
properties:
    groupId: !include GroupId.raml
    locations:
      description: A list of locations assigned to this group.
      type: array
      items:
        type: !include LocationId.raml