#%RAML 1.0 DataType
description: The type of place where the inventory is located which can either be 'location' or 'group'.
enum: [location, group]
type: string
examples: {location: location, group: group}