#%RAML 1.0 NamedExample
value:
  {
    "campaignId": "NewWinterCampaign",
    "coupons": [
        "WinterSpecial"
    ],
    "creationDate": "2019-10-03T19:36:56.000Z",
    "customerGroups": [
        "Registered"
    ],
    "description": "Campaign for winter specials",
    "enabled": true,
    "endDate": "2020-07-31T23:09:08.000Z",
    "lastModified": "2019-10-10T14:52:47.356Z",
    "startDate": "2019-04-01T11:30:15.000Z"
}
