#%RAML 1.0 NamedExample

value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/bad-request",
    "title": "Bad Request",
    "detail": "Request body contains 1 or more attributes that contains errors."
  }