#%RAML 1.0 NamedExample

value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden-access",
    "title": "Forbidden",
    "detail": "Access to requested resource is forbidden."
  }