const MOCK_SERVICE_BEARER_HEADER_KEY = "ms2-authorization";
const MOCK_SERVICE_CLIENT_ID_HEADER_KEY = "x-dw-client-id";
const DEFAULT_CLIENT = "abcd";

export {
  MOCK_SERVICE_BEARER_HEADER_KEY,
  DEFAULT_CLIENT,
  MOCK_SERVICE_CLIENT_ID_HEADER_KEY
};
