#%RAML 1.0 NamedExample
value:
  {
    "description": "Block traffic for malformed URL requests",
    "expression": "(http.request.uri.path matches \"^/path1/.*\")",
    "actions": ["block"],
    "enabled": false,
    "position": {
        "before": "2c0fc9fa937b11eaa1b71c4d701ab86e"
    }
  }