#%RAML 1.0 NamedExample
value:
  {
    "data": [
      {
        "ruleId": "ffffe61cf25e4ec49c34b029ff3060f7",
        "description": "Block traffic for malformed URL requests",
        "expression": "(http.request.uri.path matches \"^/path1/.*\")",
        "actions": ["block"],
        "lastUpdated": "2022-12-14T21:25:22.329194Z",
        "enabled": false
      },
      {
        "ruleId": "2c0fc9fa937b11eaa1b71c4d701ab86e",
        "description": "Skip user agent",
        "expression": "(http.user_agent contains \"Client\")",
        "actions": ["skip_custom_rules, skip_waf"],
        "lastUpdated": "2022-12-14T21:30:34.263795Z",
        "enabled": true
      }
    ]
  }