#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in the Data Source Code Group API.

responses:
  400:
    description: |
      Thrown when the ID given in the request URL is different from the ID provided in the source code group document.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "type": "IdConflictException",
            "title": "The ID given in the request URL is different from the ID provided in the source code group document.",
            "instance": "/sites/SiteGenesis/source_code_groups/foo"
          }