#%RAML 1.0 NamedExample
value:
  {
    "limit": 3,
    "data": [
      {
        "id": "kids-wear"
      },
      {
        "id": "mens"
      },
      {
        "id": "mens-accessories-luggage"
      }
    ],
    "offset": 0,
    "total": 3

  }