#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response when a shipment was not found.

uses:
  DataTypes: ../data-types.raml
  
responses:
  404:
    description: |
            The given shipment ID does not reference an existing shipment.
    body:
      application/problem+json:
        type: DataTypes.ErrorResponse
        example: |
          {
            "title": "Shipment Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/not-found",
            "detail": "No shipment with ID 'express_shipment' could be found."
          }
