#%RAML 1.0 NamedExample
value:
  {
   "data": {
        "ruleId": "ffffe61cf25e4ec49c34b029ff3060f7",
        "description": "Rate limit /path1",
        "expression": "http.request.uri.path matches \"^/path1/.*\"",
        "characteristics": ["cf.unique_visitor_id"],
        "action": "block",
        "period": 60,
        "requestsPerPeriod": 50,
        "mitigationTimeout": 600,
        "countingExpression": "http.request.uri.path matches \"^/path1/.*\" and http.response.code eq 400",
        "enabled": false,
        "lastUpdated": "2022-12-14T21:25:22.329194Z"
   }
}