#%RAML 1.0 NamedExample
postCampaignSearch200:
  {
    "limit": 2,
    "hits": [
        {
            "campaignId": "mens-clothing-dress-shirts",
            "creationDate": "2019-11-06T21:12:35.000Z",
            "customerGroups": [
                "Everyone"
            ],
            "description": "This a campaign for the Mens Dress Shirts Category offering a specific banner as well as a 20% off dress shirts promotion, and a custom sort rule of product name ascending",
            "enabled": false,
            "lastModified": "2019-11-06T21:12:35.000Z"
        },
        {
            "campaignId": "mens-clothing-suits",
            "creationDate": "2019-11-06T21:12:35.000Z",
            "customerGroups": [
                "Everyone"
            ],
            "description": "This is a campaign that displays a landing banner, with a 25% discount on all suits and default sorting rule of top selling suits.",
            "enabled": false,
            "lastModified": "2019-11-06T21:12:35.000Z"
        }
    ],
    "query": {
        "textQuery": {
            "fields": [
                "id",
                "description"
            ],
            "searchPhrase": "campaign"
        }
    },
    "offset": 1,
    "total": 4
}
