#%RAML 1.0 NamedExample
# This example is for Data Catalogs
value:
    {
      "limit": 2,
      "data": [
        {
          "id": "apparel-catalog"
        },
        {
          "id": "electronics-catalog"
        }
      ],
      "offset": 0,
      "total": 2
  }
