#%RAML 1.0 NamedExample
value :
  {
    "mrtHostname": "customer.mobify-storefront.com",
    "expressions": ["(http.host in {\"test-customer.salesforce.com\" \"test2-customer.salesforce.com\"} and not ( http.request.uri.path matches \"^/path4/.*\" or http.request.uri.path matches \"^.*/path5/.*/products/.*\"))"],
    "descriptions": ["Phased rollout rule for test-customer.salesforce.com and test2-customer.salesforce.com"]
  }