#%RAML 1.0 NamedExample
value :
  {
    "enabled": true,
    "expression": "(http.host eq \"dev-customer.salesforce.com\" and not ( http.request.uri.path matches \"^/path4/.*\" or http.request.uri.path matches \"^.*/path5/.*/products/.*\"))",
    "description": "Phased rollout rule for dev-customer.salesforce.com"
  }