#%RAML 1.0 NamedExample
value:
  {
    "data": 
      {
        "ruleset": 
          {
            "id": "12345678901234asdfasfasdf1234567",
            "name": "MRT Rules",
            "lastUpdated": "2022-09-15T21:14:42.372459Z",
            "rules": [
              {
                "id": "12345678901234asdfasfasdf1234567",
                "expression": "(http.host eq \"dev-customer.salesforce.com\" and not ( http.request.uri.path matches \"^/path4/.*\" or http.request.uri.path matches \"^.*/path5/.*/products/.*\"))",
                "lastUpdated": "2022-09-27T18:32:34.675182Z",
                "ref": "12345678901234asdfasfasdf1234567",
                "enabled": true,
                "mrtHostname": "customer.mobify-storefront.com"
              }
            ]
          }
      }
  }
