#%RAML 1.0 DataType

usage: Defines a status response with entity as defined in [response envelopes](https://salesforce.quip.com/pIbZA1gpxDGS#DCRACAzhyEy),
  for responses with entities consider `response-envelope.raml`.

properties:
  data:
    description: The result of the resources requested by the caller.
    type: array
    items: any
    required: false