#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "effectiveDateTime": null,
    "customQualifiers" : 
    {
      "deviceType": "iPad",
      "operatingSystem": null,
      "storeId": "SLC1",
    },
    "assignmentQualifiers" : 
    {
      "store": "london"
    }, 
    "clientIp": "12.12.12.1",
    "geoLocation": {
      "countryCode": "US",
      "country": "United States of America",
      "city": "Boston",
      "postalCode": "01730",
      "metroCode": "M234",
      "region": "NA",
      "regionCode": "12345",
      "latitude": 10.11,
      "longitude": 198.34
    }
  }