#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "effectiveDateTime": "2020-12-20T00:00:00Z",
    "sourceCode": "wii1-98",
    "customQualifiers" : 
    {
      "deviceType": "mobile",
      "ipAddress": "189.0.0.0",
      "operatingSystem": "Android"
    },
    "assignmentQualifiers" : 
    {
      "store": "boston"
    },
    "customerGroupIds" : [ "BigSpenders","MobileUsers" ]    
  }