#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "effectiveDateTime": null,
    "customQualifiers" : 
    {
      "deviceType": "iPad",
      "operatingSystem": null,
      "storeId": "SLC1",
    },
    "assignmentQualifiers" : 
    {
      "store": "london"
    }     
  }