#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "sourceCode": "wii1-98",
    "customQualifiers" : 
    {
      "deviceType": "iPad",
      "ipAddress": "189.0.0.0",
      "storeId": "SLC1"
    },
    "assignmentQualifiers" : 
    {
      "store": "london"
    },
    "customerGroupIds" : [ "BigSpenders","MobileUsers" ]

  }