#%RAML 1.0 NamedExample
value:
  [{
    "itemId": "051e908cca031ebf8ee80cbb0a",
    "productId": "green-bag",
    "quantity": 1
  },{
    "itemId": "078a492cca031ebf8ee80739ab",
    "optionItems" : [{
      "optionId":"Option1",
      "optionValueId":"ValueA"
    }],
    "quantity": 1
  }]
