#%RAML 1.0 NamedExample
{
  "data" :
    {
      "id": "c504870194831cd12c3fc0284f294abb",
      "name": "OWASP ModSecurity Core Rule Set",
      "description": "OWASP Core Ruleset (2013) provides protection against common attack categories, including SQL Injection and Cross-Site Scripting.",
      "zone_id": "56702a674281951f541f9f304f7431f0",
      "detection_mode": "anomaly",
      "sensitivity": "low",
      "action_mode": "simulate"
    }
}