#%RAML 1.0 Library

types:
  
  DataTransferRecordId:
    description: The unique idenfitier of a Data Transfer Record.
    type: string
    example: a607ab82-5f3d-11ea-bc55-0242ac130003
  
  IngestionJobId:
    description: The unique idenfitier of an Ingestion Job.
    type: string
    example: cb95f974-5f3f-11ea-bc55-0242ac130003
