#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in Data Products API.
responses:
  400:
    description: |
            Bad Request. Thrown in case a specified expand parameter value is unknown.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Unqueryable Field",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unqueryable-field",
            "detail": "The field 'link' can't be queried.",
            "field": "link"
          }