#%RAML 1.0 NamedExample
value:
  {
      "billingAddress": {
          "address1": "4 Main St.",
          "address2": "Basement Flat",
          "city": "Boston",
          "companyName": "Flexo",
          "countryCode": "US",
          "firstName": "John",
          "jobTitle": "Software Engineer",
          "lastName": "Smith",
          "phone": "+1 33-33-33",
          "postalCode": "40982",
          "secondName": "H.",
          "stateCode": "MA",
          "title": "Mr"
      },
      "channelType": "storefront",
      "creationDate": "2021-06-14T14:43:38.000Z",
      "currency": "USD",
      "customerInfo": {
          "customerId": "acWVHaXaaBGEsgTThh3zLnEr7b",
          "customerName": "John H. Smith",
          "guest": true
      },
      "giftCertificateItems": [
          {
              "basePrice": 2.00,
              "giftCertificateItemId": "5df2c340d44d73ac8589f54cc6",
              "grossPrice": 2.00,
              "itemText": "Gift Certificate",
              "netPrice": 2.00,
              "recipientEmail": "benet@example.com",
              "shipmentId": "me",
              "tax": 0.00,
              "taxBasis": 2.00
          }
      ],
      "lastModified": "2021-06-14T14:44:31.011Z",
      "orderTotal": 356.78,
      "paymentInstruments": [
          {
              "paymentInstrumentId": "50394ab45914dfc571508da28f",
              "paymentMethodId": "CREDIT_CARD",
              "paymentTransaction": {
                  "amount": 356.78
              }
          }
      ],
      "productItems": [
          {
              "basePrice": 159.00,
              "bonusProductLineItem": false,
              "brand": "Apple",
              "gift": false,
              "grossPrice": 166.95,
              "inventoryId": "inventory",
              "itemId": "ee4d59636150e0685b76caf8c5",
              "itemText": "Apple iPod Nano",
              "minOrderQuantity": 1,
              "netPrice": 159.00,
              "position": 1,
              "productId": "apple-ipod-nano-blue-16g",
              "productName": "Apple iPod Nano",
              "quantity": 1,
              "shipmentId": "me",
              "stepQuantity": 1,
              "tax": 7.95,
              "taxBasis": 159.00,
              "taxRate": 0.05,
              "c_warehouse": "023"
          },
          {
              "basePrice": 199.00,
              "bonusProductLineItem": false,
              "brand": "Apple",
              "gift": false,
              "grossPrice": 208.95,
              "inventoryId": "inventory",
              "itemId": "0515fc0f1ad46e009df23128a8",
              "itemText": "Apple iPod Nano",
              "minOrderQuantity": 1,
              "netPrice": 199.00,
              "position": 2,
              "productId": "apple-ipod-nano-black-16g",
              "productName": "Apple iPod Nano",
              "quantity": 1,
              "shipmentId": "me",
              "stepQuantity": 1,
              "tax": 9.95,
              "taxBasis": 199.00,
              "taxRate": 0.05,
              "c_warehouse": "023"
          },
          {
              "basePrice": 199.00,
              "bonusProductLineItem": false,
              "brand": "Apple",
              "gift": false,
              "grossPrice": 208.95,
              "inventoryId": "inventory",
              "itemId": "e1c9855f66227547d6e0befc79",
              "itemText": "Apple iPod Nano",
              "minOrderQuantity": 1,
              "netPrice": 199.00,
              "position": 3,
              "priceAdjustments": [
                  {
                      "appliedDiscount": {
                          "amount": 0.9,
                          "percentage": 90,
                          "type": bonus
                      },
                      "basePrice": -179.10,
                      "campaignId": "BogoCampaign",
                      "creationDate": "2021-06-14T14:43:38.000Z",
                      "custom": false,
                      "grossPrice": -188.06,
                      "itemText": "bogo-promo",
                      "lastModified": "2021-06-14T14:43:38.000Z",
                      "manual": false,
                      "netPrice": -179.10,
                      "priceAdjustmentId": "16349d1fca3f854465cea15142",
                      "promotionId": "bogo-promo",
                      "eligibleProductItemReferences": [
                          {
                             "itemId":"ee4d59636150e0685b76caf8c5",
                             "eligibleItems": [1]
                          },
                          {
                             "itemId":"0515fc0f1ad46e009df23128a8",
                             "eligibleItems": [1]
                          },
                          {
                             "itemId":"16349d1fca3f854465cea15142",
                             "eligibleItems": [1]
                          }
                      ],
                      "tax": -8.96,
                      "taxBasis": -179.10
                  }
              ],
              "productId": "apple-ipod-nano-red-16g",
              "productName": "Apple iPod Nano",
              "quantity": 1,
              "shipmentId": "me",
              "stepQuantity": 1,
              "tax": 9.95,
              "taxBasis": 199.00,
              "taxRate": 0.05,
              "c_warehouse": "023"
          }
      ],
      "shipments": [
          {
              "gift": false,
              "shipmentId": "me",
              "shipmentNo": "00001501",
              "shipmentTotal": 409.28,
              "shippingAddress": {
                  "address1": "4 Main St.",
                  "address2": "Basement Flat",
                  "city": "Boston",
                  "companyName": "Flexo",
                  "countryCode": "US",
                  "firstName": "John",
                  "jobTitle": "Software Engineer",
                  "lastName": "Smith",
                  "phone": "+1 33-33-33",
                  "postalCode": "40982",
                  "secondName": "H.",
                  "stateCode": "MA",
                  "title": "Mr"

              },
              "shippingMethod": {
                  "id": "001"
              }
          }
      ],
      "shippingItems": [
          {
              "basePrice": 9.99,
              "grossPrice": 10.49,
              "itemId": "5b56d37b34cba5357852dbc1c8",
              "itemText": "Shipping",
              "netPrice": 9.99,
              "shipmentId": "me",
              "tax": 0.50,
              "taxBasis": 9.99,
              "taxRate": 0.05
          }
      ],
      "taxation": "net",
      "taxTotal": 16.89,
      "c_distributingAgency": "Tools Incooperated"
  }
