#%RAML 1.0 NamedExample
value:
  {
    "appliedDiscount": {
      "amount": 5,
      "type": "amount"
    },
    "basePrice": -5,
    "createdBy": "storefront",
    "creationDate": "2021-06-10T16:00:04.585Z",
    "custom": true,
    "grossPrice": -5.25,
    "itemText": "Employee discount applied.",
    "lastModified": "2021-06-10T16:00:04.712Z",
    "manual": true,
    "netPrice": -5,
    "priceAdjustmentId": "db69d9efa1a270ab5cedf67bf8",
    "promotionId": "employee5DollarOff",
    "reasonCode": "employee",
    "tax": -0.25,
    "taxBasis": -5
  }