#%RAML 1.0 NamedExample
value:
  {
    "itemText" : "Employee discount applied.",
    "manual": true,
    "reasonCode" : "employee",
    "promotionId" : "employee20DollarsOff",
    "discount" : {
        "value" : 20.0,
        "type" : "amount"
    }
  } 
