#%RAML 1.0 NamedExample
value:
  {
    "itemText" : "Employee discount applied.",
    "manual": true,
    "reasonCode" : "employee",
    "promotionId" : "bogo-promo",
    "discount" : {
        "value" : 20.0,
        "type" : "amount"
    },
    "eligibleProductItemReferences": [
      {
        "itemId":"ee4d59636150e0685b76caf8c5",
        "eligibleItems": [1]
      },
      {
        "itemId":"0515fc0f1ad46e009df23128a8",
        "eligibleItems": [1]
      },
      {
        "itemId":"16349d1fca3f854465cea15142",
        "eligibleItems": [1]
      }
    ],
  } 
