#%RAML 1.0 NamedExample
value:
  {
    "itemText" : "Employee discount applied.",
    "manual": true,
    "reasonCode" : "employee",
    "promotionId" : "employeeFixed2DollarShipping",
    "discount" : {
        "value" : 2.0,
        "type" : "fixed_price"
    }
  } 
