#%RAML 1.0 NamedExample
get-promotion-example:
  {
    "archived": false,
    "assignmentInformation": {
      "active": true,
      "activeCampaignAssignments": [
        {
          "campaignId": "coupon-campaign",
          "coupons": [
            "shipping-promotion-coupon"
          ],
          "description": "Coupon Shipping Promotion",
          "enabled": true,
          "promotionId": "my-shipping-promotion",
          "schedule": {
            
          }
        }
      ],
      "campaignId": "coupon-campaign",
      "enabled": true,
      "schedule": {

      },
      "scheduleType": "none"
    },
    "creationDate": "2020-01-09T16:50:32.000Z",
    "disableGloballyExcluded": false,
    "enabled": true,
    "exclusivity": "no",
    "id": "my-shipping-promotion",
    "lastModified": "2020-01-09T16:50:32.000Z",
    "name": {
      "default": "Coupon Shipping Promotion"
    },
    "promotionClass": "shipping",
    "c_customString": "Custom Value"
  }