#%RAML 1.0 NamedExample
patch-promotion-response:
  {
    "archived": false,
    "assignmentInformation": {
      "active": false,
      "activeCampaignAssignments": [
        
      ],
      "campaignId": "coupon-campaign",
      "enabled": false,
      "schedule": {
        
      },
      "scheduleType": "none"
    },
    "creationDate": "2020-01-13T20:22:09.189Z",
    "disableGloballyExcluded": false,
    "enabled": false,
    "exclusivity": "class",
    "id": "my-promotion",
    "lastModified": "2020-01-13T20:31:25.795Z",
    "name": {
      "default": "__PROMOTION_ID__"
    },
    "promotionClass": "order",
    "c_customString": "Custom Value"
  }