#%RAML 1.0 NamedExample
value:
  {
     "address1":"100 Presidential Way",
     "address2":"100 Presidential Way 2",
     "city":"Woburn",
     "last_name":"Smith",
     "title":"Prof. Dr.",
     "country_code":"US",
     "phone":"+1 123 456789",
     "company_name":"DWRE",
     "second_name":"Daniel",
     "salutation":"Mr.",
     "state_code":"MA",
     "postal_code":"01801",
     "first_name":"John",
     "job_title":"Director",
     "c_district": "South End",
     "c_floor": 2,
     "c_note": "Engineering"
  }