#%RAML 1.0 NamedExample
value:
  {
     "address1":"100 Presidential Way",
     "address2":"100 Presidential Way 2",
     "city":"Woburn",
     "lastName":"Smith",
     "title":"Prof. Dr.",
     "countryCode":"US",
     "phone":"+1 123 456789",
     "companyName":"DWRE",
     "secondName":"Daniel",
     "salutation":"Mr.",
     "stateCode":"MA",
     "postalCode":"01801",
     "firstName":"John",
     "jobTitle":"Director",
     "c_district": "South End",
     "c_floor": 2,
     "c_note": "Engineering"
  }