#%RAML 1.0 SecurityScheme
description: A security scheme that supplements SLAS Administration APIs secured with an ECOM Account Manager JWT.<br>This security scheme expects a valid ECOM Account Manager Bearer token passed in the <b>Authorization</b> header to permit API access. See OCAPI documentation for <b>/customers/auth?client_id={valid Account MAnager clientID}</b>
type: x-custom
displayName: BearerToken
describedBy:
  headers:
    Authorization:
      description: |-
        Bearer token
      type: string
      pattern: "Bearer .*"
      examples: 
        authenticatedUser: Bearer eyJfdiI6IjEiLCJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdiI6IjEiLCJleHAiOjE2MDk3ODY0MjEsImlhdCI6MTYwOTc4NDYyMSwiaXNzIjoiNzI2YmRlODYtN2I5OS00MTVkLTk4ZWMtOTI5MGJhZDE4OTA0Iiwic3ViIjoie1wiX3ZcIjpcIjFcIixcImN1c3RvbWVyX2luZm9cIjp7XCJjdXN0b21lcl9pZFwiOlwiYWJYZFZwUndPUnM3WHEyQjJITktWaFh3NjZcIixcImd1ZXN0XCI6ZmFsc2UsXCJ2aXNpdF9pZFwiOlwiMjdmZjZiNzZjZDIzMjk0NGM0MDlmMDMyZGFcIn19In0.yrRzdCvmn2Ft9PfVj5WWcQ1M0aGV6AL9yak7b1yUHqezIE7PhybkOYfLjTfgldfoVKrFHHqV852ZHuYOLp3EQUfbphzGloTlEQPKJLAYAQLMaMgjSt-qws6HWjWsV6oBp8jeiIeoXXE7GCntkYbVrlybjoZVh3LlHSvZXly9PDuEY0vyuhIxqwt0fbyHmoHBqkO5n9Pey_ukOmGHoVuswiCcfv74Dyz0prVTrV6VTVkn64acAHVprfhWyrzgwVk5d5N2z_mM8J7xG-ymZu4vCavmcWBH1wRVoQM6y1dDAvVDvHpESyBGcOkKfxNRugmGBQ-_zmups50HV4KkjN6n80JfNRGsWKZBTNZPNrUuegrwY5FC2LeyBBNuPEvwHkP3aodk3L4bLbn_r3Tf51cGYeZKpzBRLgi79zVFtKQ6FFS_-QoP9pl-jaWMC-D7d65KSEAAyQpo3q5A76rIbKc94FC20qzd5CkWJu7Uo4bfBlpGdQMaEIMG2tcuD0IDEEXZCBtNj1OtOUkcE4rCXInPiFtnXhpw5Mv_sBnzuOT_P6mZ__X4IaZJZoHPCoYQHZzt