#%RAML 1.0 Library

types:
  ErrorCodeTypesEnum:
    type: ErrorCodesEnum

  InvalidRequestParameter:
    enum: [InvalidRequestParameter]
    type: string
    example: InvalidRequestParameter

  InvalidRequestParameterAvailabilityExport:
    enum: [InvalidRequestParameter, LocationDoesNotExist, GroupDoesNotExist]
    type: string
    example: InvalidRequestParameter

  EntityNotFound:
    enum: [EntityNotFound]
    type: string
    example: EntityNotFound
    
  ExportInProcess:
    enum: [ExportInProcess]
    type: string
    example: ExportInProcess

  ImportInProgress:
    enum: [ImportInProgress]
    type: string
    example: ImportInProgress

  FileAlreadyReceived:
    enum: [FileAlreadyReceived]
    type: string
    example: FileAlreadyReceived

  ExpiredUploadLink:
    enum: [ExpiredUploadLink]
    type: string
    example: ExpiredUploadLink

  ExpiredResultLink:
    enum: [ExpiredResultLink]
    type: string
    example: ExpiredResultLink

  ErrorCodesEnum:
    enum:
      - InsufficientQuantity
      - DuplicateGroupId
      - InvalidGroupId
      - DuplicateSku
      - MissingParameter
      - InvalidRequest
      - InvalidRequestParameter
      - EntityAlreadyExists
      - PositiveQuantityRequired
      - ReservationInUnknownState
      - ReservationInvalidState
      - ReservationCancelled
      - EntityNotFound
      - ReservationCancellationFailed
      - ExportInProcess
      - ExportProcessFailed
      - Unknown
      - DuplicateEventId
      - ReservationOperationInProcess
      - ConcurrentModification
      - GroupDoesNotExist
      - OnlyOneLocationSupported
      - NotAppliedDueToAtomicFailure
      - ImportInProgress
      - ExpiredDeltaLink
      - InventoryReset
      - UnableToStartExport
      - ResourceNotFound
      - LocationListMustNotBeEmpty
      - SeeOtherResource
      - TenantNotProvisioned
      - ReservationAlreadyFinalized
      - MismatchedGroupAndLocation
      - GroupMustNotBeEmpty
      - LocationListTooLarge
      - ExpiredUploadLink
      - ExpiredResultLink
      - FileAlreadyReceived
      - IllegalGroupState
      - DeleteTenantNotAllowed
      - TenantResetInProgress
      - LocationDoesNotExist
      - LocationNotInGroup
      - PreviousRequestAborted
      - PreviousRequestCancelled
      - DuplicateLocationId
    type: string
    example: InsufficientQuantity
