#%RAML 1.0 NamedExample
value:
  {
    "clientId": "client-id1",
    "clientName": "ShopperClient1",
    "clientType": "WebApp",
    "clientSecret": "Secret123",
    "scope": ["sfcc.products",
              "sfcc.catalogs",
              "sfcc.customers:ro"],
    "redirectUri": "http://localhost/callback",
    "channels": ["SiteGenesis",
                 "OtherSite"],
    "privateClient": true
  }