#%RAML 1.0 NamedExample
value: 
  {
        "idpName": "Google",
        "idpClientId": "934277749308-02dg4398n3s31ofge8cot46jirn3kpkf.apps.googleusercontent.com",
        "idpClientSecret": "aKZM1xEnZopNP2bm2gc3GKex",
        "idpAuthUrl": "https://accounts.google.com/o/oauth2/v2/auth",
        "idpTokenUrl": "https://oauth2.googleapis.com/token",
        "idpTokenInfoUrl": "https://oauth2.googleapis.com/tokeninfo",
        "idpUserinfoUrl": "https://www.googleapis.com/oauth2/v3/userinfo",
        "idpRedirectUrl": "http://localhost:9010/hydra/callback",
        "idpPreferenceValue": true
  }