#%RAML 1.0 NamedExample
value:
  {
    "tenantInstance": "aaaa_prd",
    "merchantName": "Popular Merchant",
    "tenantDescription": "Merchant Description",
    "tenantContact": "Jerry Smith",
    "emailAddress": "jerry@merchant.com",
    "phoneNo": "801-555-1234"
  }