#%RAML 1.0 NamedExample

value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/conflicted",
    "title": "Resource Conflict",
    "detail": "The request made for the resource is not valid."
  }