#%RAML 1.0 NamedExample

value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/resource-not-found",
    "title": "Not Found",
    "detail": "Requested resource was not found"
  }