openapi: 3.0.3
info:
  title: Shopper Products API - Category Parameters
  description: "Shopper Products API - Category Parameters"
  version: 1.0.0
paths: {}
components:
  parameters:
    id:
      name: id
      in: path
      description: The ID of the requested category.
      required: true
      schema:
        $ref: '../schemas/category.yaml#/components/schemas/CategoryId'
    ids:
      name: ids
      in: query
      required: true
      schema:
        $ref: '../schemas/category.yaml#/components/schemas/CategoryIds'
    levels:
      name: levels
      in: query
      schema:
        $ref: '../schemas/category.yaml#/components/schemas/Levels'
