openapi: 3.0.3
info:
  title: Shopper Products API - Product Parameters
  description: "Shopper Products API - Product Parameters"
  version: 1.0.0
paths: {}
components:
  parameters:
    allImages:
      name: allImages
      in: query
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/AllImages'
    expand:
      name: expand
      in: query
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/ProductExpansions'
    id:
      name: id
      description: The ID of the requested product.
      in: path
      required: true
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/ProductId'
    ids:
      name: ids
      in: query
      required: true
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/ProductIds'
    inventoryIds:
      name: inventoryIds
      in: query
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/InventoryIds'
    perPricebook:
      name: perPricebook
      in: query
      schema:
        $ref: '../schemas/product.yaml#/components/schemas/PerPricebook'
