openapi: 3.0.0
info:
  title: Shopper Products
  version: v1
  description: "# API Overview\n\nThe Shopper Products API enables you to access product details for products that are online, merchandised to a particular site catalog, and ready to be sold. You can use these product details to merchandise the product on other ecommerce channels. To set up category navigation paths on other commerce apps or storefronts, you can use the Categories API.\n\nCaching is provided for the Shopper Products API. For details, see [Server-Side Web-Tier Caching.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/server-side-web-tier-caching.html)\n\n## Authentication & Authorization\n\nThe client requesting the product information must have access to the Products resource. The Shopper Products API requires a shopper access token from the Shopper Login and API Access Service (SLAS).\n\nFor details on how to request a shopper access token from SLAS, see the guest user flows for [public clients](https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-public-client.html#guest-user) and [private clients](https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-private-client.html#guest-user) in the SLAS guides.\n\n## Use Cases\n\n### Populate Product Listing Pages\n\nUse the Shopper Product API so that a customer, browsing on a commerce shopping app built using Commerce Cloud APIs, can see a list of products. For example, hydrate a list of products (max 24). The API returns product details including images, prices, promotions, and product availability.\n\n![b2c-commerce-shopper-products-screenshot-1.png](https://resources.docs.salesforce.com/rel1/doc/en-us/static/misc/b2c-commerce-shopper-products-screenshot-1.png)\n\n### Get Variation Product Details on an Ecommerce Channel\n\nUse the API so that a customer, browsing on a commerce shopping app built using Commerce Cloud APIs, can switch between different variation products. The API returns product details including images, prices, promotions, and available to sell inventory.\n\n![b2c-commerce-shopper-products-screenshot-2.png](https://resources.docs.salesforce.com/rel1/doc/en-us/static/misc/b2c-commerce-shopper-products-screenshot-2.png)\n\n### Retrieve Promotion Information\n\nPromotions provide discounts to shoppers when they meet certain purchase requirements.\n\nPromotion information is described in detail in [Promotion Details](https://developer.salesforce.com/docs/commerce/commerce-api/guide/promotion-details.html), but the following list provides several key points:\n\n- Pricing discounts for basket and shipping promotions are NEVER returned by the 'getProduct' or 'getProducts' endpoint.\n- Promotional pricing is ONLY returned for products that are included with non-conditional promotions.\n- Callout messages are ALWAYS returned by the 'getProduct' and 'getProducts' endpoints.\n\nBy default, 'getProduct' and 'getProducts' return promotion information for a queried product. Promotion information includes both pricing and callout message information. However, the specific pricing and callout information that is fetched is determined by:\n\n- Promotion Type\n- Product Type\n- Product Purchase Requirements\n\nSome promotions can be displayed on a Product Data Page (PDP) or Product Listing page (PLP), while other promotions are displayed in the context of a basket, such as an order level promotion: \"add the product to your basket to view price information\". It is important to understand what is included in the response when designing a PDP or PLP on top of SCAPI to ensure your design aligns with implementable features.\n\n#### Shopper Personalization\nThe SCAPI response can be personalized using the Shopper Context API or hooks. By setting specific values in the Shopper Context API, you can modify the response of the 'getProduct' or 'getProducts' endpoint based on the shopper's context. For instance, you can offer a 5% discount or free shipping to shoppers using mobile devices.\n\n#### JWA Caching\nThe response is cached in JWA, which means promotion data contained in the response is also cached based on the TTL (Time to Live) specified in the Business Manager [Feature Switches](https://help.salesforce.com/s/articleView?id=cc.b2c_feature_switches.htm&type=5) configuration.\nWhen the shopper context value is updated, a check is conducted to see if the updated shopper context affects the retrieval of product-promotion data. If it does, then the response is fetched from the source and cached in the JWA.\n\nFor details, see [Server-Side Web-Tier Caching.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/server-side-web-tier-caching.html)\n\n### Use Hooks\n\nFor details working with hooks, see [Extensibility with Hooks.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/extensibility_via_hooks.html)\n\n## Resources\n\n### Product\n\nA full representation of a product or service that is to merchandise. A ready to merchandise product is one that is online, categorized, and published to a channel. The information associated with a product includes, the product name, description, custom and system attributes, variations, price, availability, and images.\n\n### Category\n\nCategories and subcategories are the structure by which products are organized and grouped in a catalog and on a storefront. Categories can have relationships to other categories. Further, each category can provide context that is inherited by subcategories. For example, a category can have an assigned attribute. A product assigned to that category or any subcategory inherits the categories’s attribute value. Once the product is removed from the category, the attribute value is no longer inherited by the product. You can also use category linking for site hierarchical navigation. For example, inside the Clothing category you may have Men’s, and inside the Men’s category you may have Pants.\n\nCategories are not tags. \n\n## Endpoints\n\n### GET /products\n\nReturns product details for up to 24 products in one API request. You can use this API for use cases that require populating or hydrating multiple products at a time, such as populating the Product Listing Pages.\n\nThe response data includes availability, promotions, images, and prices, along with the basic product information for the products requested.\n\n### GET /products/{id}\n\nReturns product details about a single product. Use this API for use cases that require populating or hydrating one product at a time, such as the Product Detail Pages.\n\nThe response data includes availability, promotions, options, images, prices, variations, bundled_products, set_products, recommendations, and the basic product information for the product requested.\n\n### GET /categories\n\nReturns category details including the parent child relationships for one or more categories. The limit on depth for the parent-child relationship is 2."
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/product/shopper-products/{version}
    variables:
      shortCode:
        default: shortCode
      version:
        default: version
paths:
  /organizations/{organizationId}/products:
    parameters:
      - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/organizationId'
    get:
      description: Allows access to multiple products by a single request. Only products that are online and assigned to a site catalog are returned. The maximum number of productIDs that can be requested are 24. Along with product details, the availability, product options, images, price, promotions, and variations for the valid products will be included, as appropriate.
      operationId: getProducts
      summary: Allows access to multiple products by a single request
      security:
        - ShopperToken: [ sfcc.shopper-products ]
      parameters:
        - $ref: './components/parameters/product.yaml#/components/parameters/ids'
        - $ref: './components/parameters/product.yaml#/components/parameters/inventoryIds'
        - $ref: './components/parameters/product.yaml#/components/parameters/expand'
        - $ref: './components/parameters/product.yaml#/components/parameters/allImages'
        - $ref: './components/parameters/product.yaml#/components/parameters/perPricebook'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/siteId'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/select'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/locale'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/currency'
      responses:
        200:
          $ref: './components/responses/product.yaml#/components/responses/GetProductsResponse'
        400:
          $ref: './components/responses/product-errors.yaml#/components/responses/GetProductsBadRequestResponse'
        401:
          $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/responses/common-errors.yaml#/components/responses/401unauthorized'

  /organizations/{organizationId}/products/{id}:
    parameters:
      - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/organizationId'
      - $ref: './components/parameters/product.yaml#/components/parameters/id'
    get:
      description: Allows access to product details for a single product ID. Only products that are online and assigned to a site catalog are returned. Along with product details, the availability, images, price, bundled_products, set_products, recommedations, product options, variations, and promotions for the products will be included, as appropriate.
      operationId: getProduct
      summary: Allows access to product details for a single product ID
      security:
        - ShopperToken: [ sfcc.shopper-products ]
      parameters:
        - $ref: './components/parameters/product.yaml#/components/parameters/inventoryIds'
        - $ref: './components/parameters/product.yaml#/components/parameters/expand'
        - $ref: './components/parameters/product.yaml#/components/parameters/allImages'
        - $ref: './components/parameters/product.yaml#/components/parameters/perPricebook'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/select'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/currency'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/locale'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/siteId'
      responses:
        200:
          $ref: './components/responses/product.yaml#/components/responses/GetProductResponse'
        400:
          $ref: './components/responses/product-errors.yaml#/components/responses/GetProductBadRequestResponse'
        401:
          $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/responses/common-errors.yaml#/components/responses/401unauthorized'
        404:
          $ref: './components/responses/product-errors.yaml#/components/responses/GetProductNotFoundResponse'

  /organizations/{organizationId}/categories:
    parameters:
      - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/organizationId'
    get:
      description: When you use the URL template, the server returns multiple categories (a result object of category documents). You can use this template as a convenient way of obtaining multiple categories in a single request, instead of issuing separate requests for each category. You can specify up to 50 multiple IDs. You must enclose the list of IDs in parentheses. If a category identifier contains parenthesis or the separator sign, you must URL encode the character. The server only returns online categories.
      operationId: getCategories
      summary: Allows access to multiple categories by a single request
      security:
        - ShopperToken: [ sfcc.shopper-categories ]
      parameters:
        - $ref: './components/parameters/category.yaml#/components/parameters/ids'
        - $ref: './components/parameters/category.yaml#/components/parameters/levels'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/locale'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/siteId'
      responses:
        200:
          $ref: './components/responses/category.yaml#/components/responses/GetCategoriesResponse'
        400:
          $ref: './components/responses/category-errors.yaml#/components/responses/GetCategoriesBadRequestResponse'
        401:
          $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/responses/common-errors.yaml#/components/responses/401unauthorized'

  /organizations/{organizationId}/categories/{id}:
    parameters:
      - $ref: './components/parameters/category.yaml#/components/parameters/id'
      - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/organizationId'
    get:
      description: |-
        When you use the URL template below, the server returns a category identified by its ID; by default, the server
        also returns the first level of subcategories, but you can specify another level by setting the levels
        parameter. The server only returns online categories.
      operationId: getCategory
      summary: Allows access to category details for a single category ID
      security:
        - ShopperToken: [ sfcc.shopper-categories ]
      parameters:
        - $ref: './components/parameters/category.yaml#/components/parameters/levels'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/locale'
        - $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/parameters.yaml#/components/parameters/siteId'
      responses:
        200:
          $ref: './components/responses/category.yaml#/components/responses/GetCategoryResponse'
        "400":
          $ref: './components/responses/category-errors.yaml#/components/responses/GetCategoryBadRequestResponse'
        "401":
          $ref: './dependencies/commerce-cloud-standards-oas-1.0.0-SNAPSHOT/components/responses/common-errors.yaml#/components/responses/401unauthorized'
        "404":
          $ref: './components/responses/category-errors.yaml#/components/responses/GetCategoryNotFoundResponse'

components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    ShopperToken:
      $ref: './components/security-schemes.yaml#/components/securitySchemes/ShopperToken'
  links: {}
  callbacks: {}
