#%RAML 1.0 NamedExample
value:
  [
   {
      "couponId":"CouponA",
      "creationDate":"2019-10-25T12:00:00Z",
      "description":"A Coupon",
      "enabled":false,
      "exportedCodeCount":0,
      "lastModified":"2019-10-25T12:00:00Z",
      "redemptionCount":0,
      "redemptionLimits":{
         "limitPerCode":0,
         "limitPerCustomer":0,
         "limitPerTimeFrame":{
            "redemptionTimeFrame":0,
            "limit":0
         }
      },
      "singleCode":"MyCode",
      "totalCodesCount":1,
      "type":"single_code"
   }
  ]