ignores:
  # Include a reason why each package is listed
  - typedoc-plugin-external-module-map # Used by typedoc in `npm run doc`
  - typedoc-plugin-nojekyll # Used by typedoc in `npm run doc`
  - node-fetch # We only use @types/node-fetch, not node-fetch itself
  - retry # Use OperationOptions from retry in templates but not recognized by depcheck
  - '@types/retry' # Corresponds to retry
  - '@openapitools/openapi-generator-cli' # Used by openapi-generator-cli in `npm run renderTemplates`
  - '@types/node-fetch' # Used by multiple files for fetch types
  - chai # Used by multiple files for testing
  - sinon # Used by multiple files for testing
  - nock # Used by multiple files for testing to mock API calls
  - handlebars # Used by generation script to generate version.ts and top level index.ts files
  - fs-extra # Used by generation script and updateApis script
