#%RAML 1.0 Trait
description: Thrown if the request is malformed, incomplete or otherwise erroneous.
responses:
  '400':
    description: Thrown if an invalid locale has been provided.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "title": "Unknown Locale",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unknown-locale",
            "detail": "The locale 'ab-CD' is unknown.",
            "locale": "ab-CD"
          }