#%RAML 1.0 Trait
description: Thrown if the requested resource is not found.
responses:
  '404':
    description: Thrown if no mapping was found for a given URL segment.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "title": "Seo Url Mapping Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/seo-url-mapping-not-found",
            "detail": "black/mens/accessories/luggage",
            "urlSegment": "black/mens/accessories/luggage",
            "locale": "en_US"
          }
          