#%RAML 1.0 NamedExample
# Example of Client List
value: 
  {
    data: [
      {
          "clientId": "a462b606-317c-4a3c-90a7-4b0b938f3807",
          "secret": "",
          "name": "Shop Mart",
          "scopes": ["sfcc.products sfcc.catalogs sfcc.products.ro"],
          "redirectUri": "http://localhost:9010/callback",
          "callbackUri": "http://localhost:9010/pwd/reset/callback",
          "channels": [
              "SiteGenesis",
              "OtherSite"
          ],
          "isPrivateClient": true
      },
      {
          "clientId": "726bde86-7b99-415d-98ec-9290bad18904",
          "secret": "",
          "name": "High Adventure Wear",
          "scopes": ["sfcc.products sfcc.catalogs sfcc.products.ro"],
          "redirectUri": "http://localhost:9010/callback",
          "callbackUri": "http://localhost:9010/pwd/reset/callback",
          "channels": [
              "SiteGenesis",
              "OtherSite"
          ],
          "isPrivateClient": true
      },
      {
          "clientId": "slas-default-client-1",
          "secret": "",
          "name": "Shop Salesforce",
          "scopes": ["sfcc.products.ro sfcc.catalogs.ro"],
          "redirectUri": "http://localhost:9010/callback",
          "callbackUri": "http://localhost:9010/pwd/reset/callback",
          "channels": [
              "SiteGenesis",
              "OtherSite"
          ],
          "isPrivateClient": true
      }
    ]
  }

