#%RAML 1.0 NamedExample
value:
  {
    "clientId": "client-id1",
    "name": "ShopperClient1",
    "type": "WebApp",
    "secret": "",
    "scopes": ["sfcc.products",
              "sfcc.catalogs",
              "sfcc.customers:ro"],
    "redirectUri": "http://localhost/callback",
    "channels": ["SiteGenesis",
                 "OtherSite"],
    "privateClient": true
  }