#%RAML 1.0 NamedExample
value:
  {
    "clientId": "client-id1",
    "secret": "secret12345",
    "name": "High Adventure Wear",
    "scopes": [
        "sfcc.products",
        "sfcc.catalogs",
        "sfcc.products.ro"
    ],
    "redirectUri": ["http://localhost:9010/callback"],
    "callbackUri": ["http://localhost:9010/pwd/reset/callback"],
    "channels": ["SiteGenesis",
                 "OtherSite"],
    "isPrivateClient": true
}