#%RAML 1.0 NamedExample
value: 
  {
    "tenantId": "aaaa_prd",
    "username": "joe.shopper@google.com",
    "email": "joe.shopper@google.com",
    "credQualityMeasure": 0,
    "pwdStrengthMeasure": 0,
    "pwdQualityMeasure": 0,
    "credChangeCount": 0,
    "loginCount": 0,
    "lastLoginDatetime": 2021-08-18T16:41:41.090Z,
    "lastCredcheckDatetime": 2021-08-18T16:41:41.090Z,
    "atoScore": 3,
    "atoLastDatetime": 2021-08-18T16:41:41.090Z,
    "atoLastSourceIp": "",
    "atoScoreHistory": "5, 6, 7"
  }