#%RAML 1.0 NamedExample
value: 
  {
    "name": "google",
    "clientId": "idp-client-id",
    "clientSecret": "idp-secret",
    "authUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "tokenInfoUrl": "https://oauth2.googleapis.com/tokeninfo",
    "userInfoUrl": "https://www.googleapis.com/oauth2/v3/userinfo",
    "redirectUrl": "http://localhost:9010/hydra/callback",
    "scopes": ["openid","email","profile"],
    "preferenceValue": true,
    "teamId": "appleTeamId",
    "keyId": "appleKeyId",
    "loginMergeClaims": ["email"],
    "oidcClaimMapper": ["accessToken=access_token","refreshToken=refresh_token","accessTokenTTL=expires_in","idToken=id_token","subject=sub","email=email","userId=sub","familyName=family_name","givenName=given_name","name=name"]
  }