#%RAML 1.0 NamedExample
value:
  {
      "channelId": "SiteGenesis",
      "name": "Passwordless Email Template",
      "subject": "Passwordless Token Request",
      "link": "This is your passwordless token: ${token}",
      "locale": "en-us",
      "actionType": "PWDLESS_LOGIN",
      "templateType": "EMAIL",
      "template": "Passwordless Login Token Request\n\nHello ${name},\nYou're receiving this email because you requested a passwordless login token for your account.\n${link}"
  }