#%RAML 1.0 NamedExample
value:
  {
    "createdBy": "slas",
      "modifiedBy": "slas",
      "createdTime": "2021-02-25T00:55:54.119+0000",
      "modifiedTime": "2021-02-25T00:55:54.119+0000",
      "tenantId": "slsa_dev",
      "merchantId": 2,
      "description": "SLAS Default Tenant Two",
      "contact": "Tenant Two",
      "emailAddress": "tenant2@slas.tst",
      "phoneNo": "111-222-4444",
      "tier": "S",
      "requestQuotaPerMinute": 8000,
      "isDeleted": false,
      "status": "CLEAR"
  }