#%RAML 1.0 NamedExample
# Example of Tenant List
value:
  {
    data: [
      {
          "createdBy": "SLAS",
          "modifiedBy": "SLAS",
          "createdTime": "2021-02-25T00:55:52.726+0000",
          "modifiedTime": "2021-02-25T00:55:52.726+0000",
          "tenantId": "bcgl_stg",
          "merchantId": 1,
          "description": "BCGL Stg",
          "contact": "Slas Test",
          "emailAddress": "bcgl@slas.tst",
          "phoneNo": "",
          "isDeleted": false,
          "status": "CLEAR"
      },
      {
          "createdBy": "SLAS",
          "modifiedBy": "SLAS",
          "createdTime": "2021-02-25T00:55:54.119+0000",
          "modifiedTime": "2021-02-25T00:55:54.119+0000",
          "tenantId": "slsa_dev",
          "merchantId": 2,
          "description": "SLAS Default Tenant Two",
          "contact": "Tenant Two",
          "emailAddress": "tenant2@slas.tst",
          "phoneNo": "",
          "isDeleted": true,
          "status": "CLEAR"
      },
      {
          "createdBy": "SLAS",
          "modifiedBy": "SLAS",
          "createdTime": "2021-02-25T01:20:42.179+0000",
          "modifiedTime": "2021-02-25T01:20:42.179+0000",
          "tenantId": "blar_dev",
          "merchantId": 3,
          "description": "Token Testing",
          "contact": "John Doe",
          "emailAddress": "jdoe@shotzphoto.tst",
          "phoneNo": "",
          "isDeleted": false,
          "status": "CLEAR"
      }
    ]
  }