#%RAML 1.0 NamedExample

value:
  {
    "categoryCount": 30,
    "creationDate": "2019-02-21T22:09:39.000Z",
    "id": "apparel-catalog",
    "lastModified": "2019-02-21T22:09:39.000Z",
    "name": {
      "default": "Apparel Master Catalog"
    },
    "online": true,
    "recommendationCount": 0,
    "rootCategory": "root"
  }