#%RAML 1.0 NamedExample
post_campaign_search_400:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-operation",
  "detail": "Failed to execute search query: wrong syntax.",
  "title": "Incorrect Syntax"
}