#%RAML 1.0 Library

types:
  CancelEnum: !include ../types/ReservationStatus.raml
  CancelReservationRequestBody:
    description: The body that is sent requesting a reservation be cancelled.
    properties:  
      status:
        type: CancelEnum
        example: CANCELLED
