#%RAML 1.0 Library

types:
  ReservationId: !include ../types/ReservationId.raml
  ReservedReservationGroup: !include ../types/ReservedReservationGroup.raml
  ReservedReservationLocation: !include ../types/ReservedReservationLocation.raml

  GetReservationResponseBody:
    description: The body that is returned when reservation details are requested.
    properties:  
      reservationId:
        type: ReservationId
      groups:
        required: false
        type: array
        items: ReservedReservationGroup
      locations:
        required: false
        type: array
        items: ReservedReservationLocation
          
    
                  