#%RAML 1.0 Library

usage: |-
  This is a collection of types, traits, security schemes, and more that have been built to support multiple different API Specs in the Inventory Availability Space, in conjuction with the standard Salesforce API Standards library, via:

# Traits
traits:
  GenericResponseErrorCode: !include traits/GenericResponseErrorCode.raml
   
types:
  ATF: !include types/ATF.raml
  ATO: !include types/ATO.raml
  Date: !include types/Date.raml
  DeltaToken: !include types/DeltaToken.raml
  EffectiveDate: !include types/EffectiveDate.raml
  ErrorCode: !include types/ErrorCode.raml
  ExternalRefIf: !include types/ExternalRefId.raml
  FileValidation: !include types/FileValidation.raml
  Future: !include types/Future.raml
  GenericAttribute: !include types/GenericAttribute.raml
  GenericProcessStats: !include types/GenericProcessStats.raml
  GenericStatuses: !include types/GenericStatuses.raml
  GroupId: !include types/GroupId.raml
  IdempotenceId: !include types/IdempotenceId.raml
  LocationGroup: !include types/LocationGroup.raml
  LocationId: !include types/LocationId.raml
  LocationOrGroup: !include types/LocationOrGroup.raml
  Place: !include types/Place.raml
  PlaceId: !include types/PlaceId.raml
  PlaceType: !include types/PlaceType.raml
  QOH: !include types/QOH.raml
  ReservedQuantity: !include types/ReservedQuantity.raml
  SafetyStock: !include types/SafetyStock.raml
  SkuId: !include types/SkuId.raml
  UniqueId: !include types/UniqueId.raml