#%RAML 1.0 NamedExample
{ 
   "description": "Birthday Gift",
   "enabled": false, 
   "message": "A birthday gift for you",
   "recipientEmail": "john.doe@gmail.com",
   "recipientName": "John Doe",
   "senderName": "Jane Doe",
   "status": "pending"
}