#%RAML 1.0 NamedExample
value:
  {
   "amount": {"currencyMnemonic": "USD", "value": 1000},
   "description" : "Birthday gift",
   "message" : "A birthday present to you",
   "senderName" : "Jane Doe",
   "recipientName" : "John Doe",
   "recipientEmail" : "john.doe@gmail.com",
   "status" : "issued",
   "orderNo" : "CA17293",
   "enabled" : false
}