#%RAML 1.0 NamedExample
{
  "amount": {
    "currencyMnemonic": "USD",
    "value": 100.00
  },
  "balance": {
    "currencyMnemonic": "USD",
    "value": 100.00
  },
  "creationDate": "2015-07-31T14:36:17.544Z",
  "description": "Birthday gift",
  "enabled": false,
  "maskedGiftCertificateCode": "************KTIP",
  "merchantId": "NorthernTrailOutfitters",
  "message": "A birthday gift for you",
  "orderNo": "CA17293",
  "recipientName": "John Doe",
  "recipientEmail": "john.doe@gmail.com",
  "senderName": "Jane Doe",
  "status": "issued",
  "transactions": [
    {
      "amount": {
        "currencyMnemonic": "EUR",
        "value": 80.00
      },
      "orderNo": "my-order_no",
      "timestamp": "2015-09-09T17:16:12.066Z",
      "typeCode": "create"
    }
  ]
}