#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response.

responses:
  404:
    description: Not Found.
    body:
      application/json:
        type: Error
        example: |
          {
            "type": "ProductNotFoundException",
            "title": "No product with ID 'apple-ipod-s' for site 'SiteGenesis' could be found.",
            "detail": "Check Product Id",
            "instance": ""
          }