#%RAML 1.0 NamedExample

value:
  {
    "data": [
        {
            "certificateId": "14b72e2c-db8e-40ec-9f89-d80ca431a36e",
            "status": "PENDING_VALIDATION",
            "minTlsVersion": "1.2",
            "certificateType": "automatic",
            "certificateAuthority": "google",
            "certificateValidation": "txt",
            "certificateVerificationTXTName": "_acme-challenge.test.example.com",
            "certificateVerificationTXTValue": "DBCtxdyQSyo9eXxys-uGVCwPFHLsc8_lu11QetQz4IA",
            "certificateVerificationStatus": "PENDING",
            "customHostnameId": "6c8beb36-a679-4eca-a09a-e3d6aca12787",
            "customHostname": "test.example.com",
            "customHostnameStatus": "ACTIVE"
        },
        {
            "certificateId": "16b3f671-de15-4ba8-8c02-84ba011b7751",
            "hosts": [
                "shop.example.com"
            ],
            "expiresOn": "2024-05-27T22:58:10Z",
            "uploadedOn": "2024-02-27T22:58:11Z",
            "issuer": "LetsEncrypt",
            "signature": "SHA256WithRSA",
            "status": "ACTIVE",
            "minTlsVersion": "1.2",
            "certificateType": "automatic",
            "certificateAuthority": "lets_encrypt",
            "certificateValidation": "http",
            "customHostnameId": "dd625c6d-8553-4d14-abc2-6d747866c8d9",
            "customHostname": "shop.example.com",
            "customHostnameStatus": "ACTIVE"
        },
        {
            "certificateId": "f135013c-2bf7-4225-b043-84cf35a93e12",
            "hosts": [
                "*.example.com"
            ],
            "expiresOn": "2024-04-09T20:36:39Z",
            "uploadedOn": "2024-03-19T22:32:41Z",
            "issuer": "LetsEncrypt",
            "signature": "SHA256WithRSA",
            "status": "ACTIVE",
            "minTlsVersion": "1.2",
            "certificateType": "custom",
            "customHostnameId": "6567aee6-bdbe-4cb1-9f4b-73209c5e867a",
            "customHostname": "www.example.com",
            "customHostnameStatus": "ACTIVE"
        }
    ]
}