#%RAML 1.0 NamedExample

value:
  {
    "data": 
      {
        "certificateId": "730a1be4-22d7-11eb-aff1-0242ac120002",
        "status": "ACTIVE",
        "hosts": ["salesforce.com"],
        "expiresOn": "2022-01-12T04:15:57Z",
        "uploadedOn": "2020-01-12T04:15:57Z",
        "customHostnameVerificationTXTName": "_salesforce.com",
        "customHostnameVerificationTXTValue": "4c9c3f4f-2e91-4c5d-a902-f12f9c285b9e",
        "customHostnameId": "465a48f6-3d98-4c15-9312-211984ee8629",
        "customHostname": "test.salesforce.com",
        "customHostnameStatus": "ACTIVE"
      }
  }