#%RAML 1.0 NamedExample

value:
  {
    "data": [
        {
            "certificateId": "dc95610a-9a20-4e24-b6d6-232df5fc32d1",
            "hosts": [
                "shop.example.com"
            ],
            "expiresOn": "2024-05-14T23:00:45Z",
            "uploadedOn": "2024-03-19T21:28:36Z",
            "issuer": "LetsEncrypt",
            "signature": "SHA256WithRSA",
            "status": "ACTIVE",
            "certificateType": "custom_legacy"
        },
        {
            "certificateId": "3a2a71c6-c00f-41c4-86dd-d6dc434851d5",
            "hosts": [
                "www.example.com"
            ],
            "expiresOn": "2024-04-15T17:07:59Z",
            "uploadedOn": "2024-03-19T21:28:36Z",
            "issuer": "LetsEncrypt",
            "signature": "SHA256WithRSA",
            "status": "ACTIVE",
            "certificateType": "custom_legacy"
        }
    ]
}