#%RAML 1.0 NamedExample

value:
  {
    "data":
      {
        "customHostnameId": "465a48f6-3d98-4c15-9312-211984ee8629",
        "customHostname": "test.salesforce.com",
        "customHostnameVerificationTXTName": "_salesforce.com",
        "customHostnameVerificationTXTValue": "4c9c3f4f-2e91-4c5d-a902-f12f9c285b9e",
        "customHostnameStatus": "ACTIVE"
      }
  }