#%RAML 1.0 NamedExample
  {
    "data":
      {
        "hsts": {
          "enabled" : false,
          "includeSubdomains" : false,
          "maxAge" : 200,
          "preload" : false
        },
        "securityLevel" : "medium",
        "tls13Enabled" : false,
        "alwaysUseHttps": true
      }
  }