#%RAML 1.0 NamedExample

value:
  {
    "data":
      {
        "zoneId": "023e105f4ecef8ad9ca31a8372d0c353",
        "zoneName": "stg-zzzz-cc-merchant-com.cc-ecdn.net",
        "createdOn": "2022-01-01T05:20:00.12345Z",
        "status": "active"
      }
  }