#%RAML 1.0 Trait
description: 400 response when there is a bad request for a customer.
responses:
  '400':
      description: |
                CustomerId URL parameter does not match the verified customer represented by the JWT token.
      body:
        application/json:
          type: Error
          example: 
            {
            "type": "Invalid customer.",
            "title": "Invalid customer.",
            "detail": "The customer is invalid.",
            "instance": "Blah"
          }
