#%RAML 1.0 Trait
description: 401 response when a customer is not authorized.
responses:
  '401':
      description: |
                Indicates that the customerId URL parameter does not match the verified customer represented by the JWT token, which is not relevant when using OAuth, or indicates that the provided new address name is already used for the customer.
      body:
        application/json:
          type: Error
          example: {
            "type": "InvalidCustomerException",
            "title": "CustomerId URL parameter does not match the verified customer represented by the JWT token.",
            "detail": "Blah",
            "instance": "/blah"
          }