#%RAML 1.0 Trait
#generic response for responses that have a body of type: ErrorCode, with placeholders for the response code, description, errorCode and error Message

responses:
  <<responseCode>>:
    description: <<description>>
    body:
      application/json:
        type: !include ../types/ErrorCode.raml        
        example:
          errorCode: <<errorCode>>
          message: <<message>>