#%RAML 1.0 NamedExample
value:
  {
    "data": {
      "name": "Managed Ruleset",
      "rulesetId": "efb7b8c949ac4650a09736fc376e9aee",
      "action": "js_challenge",
      "enabled": true
    }
  }