#%RAML 1.0 NamedExample
value:
  {
      "data": {
          "ruleId": "53065ac9bd9449f3895f1865467a0e6a",
          "action": "log",
          "score": 5,
          "categories": [
              "application-multi",
              "attack-reputation-scanner",
              "capec-1000",
              "capec-118",
              "capec-224",
              "capec-310",
              "capec-541",
              "language-multi",
              "paranoia-level-1",
              "pci-6-5-10",
              "platform-multi"
          ],
          "description": "913100: Found User-Agent associated with security scanner",
          "lastUpdated": "2024-08-19T17:26:58.593021Z",
          "enabled": true
      }
  }