#%RAML 1.0 NamedExample
value:
  {
   "_v" : "19.10",
   "amount": {"currencyMnemonic": "USD", "value": 1000},
   "description" : "my-description",
   "message" : "my-message",
   "senderName" : "my-sender_name",
   "recipientName" : "my-recipient_name",
   "recipientEmail" : "my-recipient_email",
   "status" : "issued",
   "orderNo" : "my-order_no",
   "enabled" : false
}