openapi: 3.0.3
info:
  title: Common Parameters
  description: Salesforce Commerce API common parameters
  version: 1.0.0
paths: {}
components:
  parameters:
    currency:
      name: currency
      in: query
      schema:
        $ref: '../components/schemas/iso-standards.yaml#/components/schemas/CurrencyCode'
    siteId:
      name: siteId
      in: query
      required: false
      schema:
        $ref: '../components/schemas/common.yaml#/components/schemas/SiteId'
      example: en-US
    locale:
      name: locale
      in: query
      required: false
      schema:
        $ref: './schemas/iso-standards.yaml#/components/schemas/LocaleCode'
    limit:
      name: limit
      in: query
      schema:
        $ref: '../components/schemas/pagination.yaml#/components/schemas/Limit'
    offset:
      name: offset
      in: query
      schema:
        $ref: '../components/schemas/pagination.yaml#/components/schemas/Offset'
    select:
      name: select
      in: query
      schema:
        $ref: '../components/schemas/common.yaml#/components/schemas/Select'
    shortCode:
      name: shortCode
      in: path
      required: true
      example: 0dnz6oep
      schema:
        $ref: '../components/schemas/common.yaml#/components/schemas/ShortCode'
    organizationId:
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '../components/schemas/common.yaml#/components/schemas/OrganizationId'



