#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Promotions API.
responses:
  404:
    description:
      Thrown when there is no promotion found with the given ID for the requested site.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example:
          {
            "title": "Promotion Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/promotion-not-found",
            "detail": "No promotion with ID 'not-existing-promotion' in site 'SiteGenesis' could be found.",
            "promotionId": "not-existing-promotion",
            "siteId": "SiteGenesis"
          }