#%RAML 1.0 NamedExample
value:
  {
    "addressId": "2",
    "address1": "123 Trailblazer Ave.",
    "postalCode": "94105",
    "lastName": "Leung",
    "title": "",
    "salutation": "Ms",
    "companyName": "Ursa Major Solar",
    "secondName": "",
    "phone": "415-555-1212",
    "countryCode": "US",
    "city": "San Francisco",
    "address2": "",
    "firstName": "Wei",
    "jobTitle": "",
    "stateCode": "CA"
  }

