#%RAML 1.0 NamedExample
value:
  {
    "credentials": {
    "enabled": true,
    "locked": false,
    "login": "CandaceEvans2585",
    "passwordQuestion": ""
    },
    "lastName": "Evans",
    "customerNo": "00005002"
  }
