#%RAML 1.0 NamedExample
value:
  {
    "defaultProductOptionValue": false,
    "id": "value1",
    "optionPrices": [
        {
            
            "currencyMnemonic": "USD",
            "value": 100.00
        }
    ],
    "skuExtension": "s10",
    "value": {
        "default": "value 1",
        "en-US": "value 1(en-US)",
        "en": "value 1(en)"
    }
  }