#%RAML 1.0 NamedExample
value:
  {
   "customName" :
   {
      "default" : "My Option"
   },
   "description" :
   {
      "default" : "Description for my option."
   },
   "id" : "my-option",
   "image" :
   {
      "absUrl" : "https://example.com/on/demandware.static/-/Sites-XMaster/default/aaaaaaaabbbbbbbbbabababba/option.jpg",
      "disBaseUrl" : "https://example.com/dw/image/v2/zzzz_s01/on/demandware.static/-/Sites-XMaster/default/aaaaaaaabbbbbbbbbabababba/option.jpg",
      "path" : "option.jpg"
   },
   "name" : "option",
   "shared" : false,
   "sortingMode" : "byoptionprice"
  }