#%RAML 1.0 NamedExample

value:
  {
    "refinements": {
        "size": "8",
        "refinementColor": "Black",
        "isNew": "true"
    },
    "resourceId": "womens-clothing-bottoms",
    "resourceType": "category"
  }