#%RAML 1.0 NamedExample
value:
  {
     "c_externalReferenceCode": "dfg73DsFgH93Lkj2SaArePos",
     "c_processedDate": "2019-10-07",
     "c_additionalInformation" : "Brunch enim ligula congue eu tempus craft beer tellus amet non urna sapien you probably haven’t heard of them eros ornare massa massa. Duis craft beer mattis pellentesque nulla risus arcu San Francisco adipiscing proin lorem sapien integer wire-rimmed glasses auctor ipsum cursus eget nam. Toms bibendum donec vivamus molestie vulputate fixie cursus amet eget nibh integer craft beer pellentesque odio mauris porttitor sodales."
  }