#%RAML 1.0 NamedExample
get-promotion-example:
  {
    "archived": false,
    "assignmentInformation": {
      "active": false,
      "enabled": true,
      "scheduleType": "none"
    },
    "creationDate": "2020-01-09T16:50:32.000Z",
    "disableGloballyExcluded": false,
    "enabled": true,
    "exclusivity": "class",
    "id": "my-promotion",
    "lastModified": "2020-01-09T16:50:32.000Z",
    "name": {
      "default": "__PROMOTION_ID__"
    },
    "promotionClass": "order"
  }