#%RAML 1.0 DataType
description: The security header for a zone.
type: object
properties:
  enabled:
    description: Enable strict transport security.
    type: boolean
    required: false
  includeSubdomains:
    type: boolean
    description: Include all subdomains for strict transport security.
    required: false
  maxAge:
    description: Max age in seconds of the strict transport security.
    type: number
    required: false
  preload:
    description: Preload any URLs that are included in the response headers.
    type: boolean
    required: false
