#%RAML 1.0 DataType
description: Response for MRT rules. MRT rules are a way to route certain storefront requests to the managed runtime instance.
type: object
properties:
  ruleset: 
    description: The MRT ruleset. 
    type: MRTRuleset