#%RAML 1.0 DataType
description: Request to enable or disable OCAPI Caching Page rule
type: object
properties:
  enableOCAPICachingPageRule:
    description: true to enable OCAPI Caching Page rule, false to disable.
    type: boolean
    example: true