#%RAML 1.0 DataType
description: An origin header modification rule.
type: object
properties:
  headerName:
    description: The name of the header forwarded to the origin.
    type: string
    example: x-sfdc-access-control
  headerValue:
    description: The masked value of the header forwarded to the origin.
    type: string
    example: '****************789'
  lastUpdated:
    description: Date when the rule was last updated.
    type: datetime
    example: 2022-01-01T05:20:00Z