#%RAML 1.0 DataType
description: Used to specify the position of a rule.
type: object
properties:
  before:
    description: Insert the current rule before this ruleId.
    type: string
    example: 2c0fc9fa937b11eaa1b71c4d701ab86e
    required: false
  after:
    description: Insert the current rule after this ruleId.
    type: string
    example: 2c0fc9fa937b11eaa1b71c4d701ab86e
    required: false