#%RAML 1.0 DataType
properties:
  brotliCompression:
    type: string
    description: Brotli compression setting of a zone.
    required: false
    default: off
    enum: ["on", "off"]
  http2Prioritization:
    type: string
    description: Http2 prioritization setting for a zone.
    required: false
    default: off
    enum: ["on", "off"]
    example: off
  webp:
    type: string
    description: Support for the WebP image format when using image modification for a zone. The WebP image format can be used with supported clients for added performance benefits. Setting this property to `on` will return an error when the `polish` property is set to `off`.
    required: false
    default: off
    enum: ["on", "off"]
    example: off      
  polish:
    type: string
    description: The level of polish (image quality) used for image modification. The value `lossless` corresponds to **Polish Level Basic** in the UI, and the value `lossy` corresponds to **Polish Level Basic+JPEG.** To disable image modification, set this property to `off`. Setting this property to `off` will prevent you from setting the `webp` property to `on`.
    required: false
    default: off
    enum: [off, lossless, lossy]
    example: off
  earlyHints:
    type: string
    description: Early Hints for a zone.
    required: false
    default: off
    enum: [ "on", "off" ]
    example: off
  http3:
    type: string
    description: Http3 for a zone.
    required: false
    default: off
    enum: [ "on", "off" ]
    example: off
  http2ToOrigin:
    type: string
    description: Http2 to Origin for a zone.
    required: false
    default: off
    enum: [ "on", "off" ]
    example: off

examples:
  brotliCompressionExample:
    brotliCompression: off
  http2PrioritizationExample:
    http2Prioritization: off
  polishExample: 
    polish: off
  webpExample: 
    webp: off
  earlyHintsExample:
    earlyHints: off
  http3Example:
    http3: off
  http2ToOriginExample:
    http2ToOrigin: off