#%RAML 1.0 DataType
description:
type: object
properties:
  isEnabled:
    description:
    type: boolean
    default: false
  maxAge:
    description: Max age in seconds of the strict transport security.
    type: number
  shouldIncludeSubdomains:
    description: Include subdomains for strict transport security.
    type: boolean
  isNosniffEnabled:
    description: |
      Include the `X-Content-Type-Options: nosniff` header.
    type: boolean

example:
  isEnabled: true
  maxAge: 3600
  shouldIncludeSubdomains: true
  isNosniffEnabled: false
