properties:
  sensitivity:
    type: string
    enum: ["low", "medium", "high", "off"]
    description: Sensitivity for traditional (owasp) rule package.
  action_mode:
    type: string
    enum: ["simulate", "challenge", "block"]
    description: The default action that is taken for rules under traditional(owasp) firewall package.