#%RAML 1.0 DataType
properties:
  ruleId?:
    type: string
    example: 892e67954025e0ba6atefd586b9e58b3
  groupId?:
    type: string
    maxLength: 100
    example: 372e67954025e0ba6aaa6d586b9e0b60
  action:
    type: string
    enum: ["block", "challenge", "monitor", "disable", "default"]
    description: The action to apply to WAF rule
    example: block
  defaultAction?:
    type: string
    enum: ["block", "challenge", "monitor", "disable"]
    description: The action to apply to WAF rule
    example: block
  description?:
    type: string
    description: Description of the WAF Group.
    example: "Test WAF Rule to protect against SQL injection"

examples:
  example1:
    ruleId: 892e67954025e0ba6atefd586b9e58b3
    groupId: 372abe67954025e0ba6aaa6d586b9e0b
    action: monitor
    defaultAction: challenge
    description: SQL injection protection
  example2:
    ruleId: 673e67954025e0ba6atefd586b90mtd5
    groupId: 396abe67954025e0ba6bde6d586b9e5a
    action: challenge
    defaultAction: block
    description: xss attack protection