#%RAML 1.0 DataType
properties:
  version:
    type: string
    description: Version to update the worker to. If omitted it will update to the latest available version.
    required: false
    example: "2.0.12"

examples:
  versionExample:
    version: "2.0.12"

    