
#%RAML 1.0 DataType

type: object
displayName: Zone
description: Zone is the container for hostnames and various CDN settings/properties. Each zone is tied to a single origin.

properties:
  zoneId:
    type: string
    maxLength: 100
    description: Identity of the zone.
  name:
    type: string
    maxLength: 100
    description: Name given to the zone. This needs to be a DNS domain name for eg example.com
  status:
    type: string
    enum: ["active", "pending", "initializing", "moved", "deleted", "deactivated"]
    description: Status of the zone for eg "Pending" , "Active"

examples:
  example1:
    zoneId: example1-zone-Id
    name: example1.com
    status: pending
  example2:
    zoneId: example2-zone-Id
    name: example2.com
    status: active