#%RAML 1.0 NamedExample
# Added for work performed in W-7535728
value:
  {
    records: [
      {
        "id": "82251928-8863-488e-840b-2aebd10b35ed",
        "externalRefId": "7282822-9823-aaa",
        "from": {
          "location": "warehouse4"
        },
        "to": {
          "location": "warehouse5"
        },
        "sku": "sku-001",
        "quantity": 2.011
      },
      {
        "id": "82251928-8863-488e-840b-2aebd10b57ba",
        "externalRefId": "7282822-9823-bbb",
        "from": {
          "group": "UnitedStates"
        },
        "to": {
          "location": "warehouse5"
        },
        "sku": "sku-002",
        "quantity": 7.132,
        "ignoreAvailabilityCheck": true
      }, 
      {
        "id": "12345-23456-3456-4567-5678-6F6F",
        "externalRefId": "1234561-3574-6B6D",
        "from": {
          "location": "warehouse5"
        }, 
        "to": {
          "group": "UnitedStates"
        },
        "sku": "sku1000",
        "quantity": 5.417
      }
   ]
  }
