#%RAML 1.0 NamedExample
# Added for work performed in W-7535728
value:
  {
  "errors": [
    {
      "details": {
        "id": "82251928-8863-488e-840b-2aebd10b57ba",
        "externalRefId": "7282822-9823-aaa",
        "from": {
          "group": "UnitedStates"
        },
        "to": {
          "group": "Canada"
        },
        "sku": "sku-001",
        "quantity": 2.011
      },
      "message": "Insufficient Quantity",
      "errorCode": "InsufficientQuantity"
    }
  ]
}