#%RAML 1.0 NamedExample
value:
  {
    "reservationTime": "2019-07-24T21:13:00Z",
    "expirationTime": "2019-07-24T21:18:00Z",
    "success": false,
    "groups": [
      {
      "id": "UnitedStatus",
      "errors": [
        {
        "sku": "sku5678",
        "errorCode": "InsufficientQuantity"
        }
      ],
      "details": [
        {
        "sku": "sku1234",
        "quantity": 10.1
        }
      ]
      }
    ],
    "locations": [
      {
      "id": "warehouse5",
      "errors": [
        {
        "sku": "sku5678",
        "errorCode": "InsufficientQuantity"
        }
      ],
      "details": [
        {
        "sku": "sku1234",
        "quantity": 10.1
        }
      ]
      }
    ]
  }