#%RAML 1.0 Library

uses:
  IDs: Types/identifiers.raml
  
types:

  # Resource Indentifiers
  DataTransferRecordId: IDs.DataTransferRecordId
  IngestionJobId: IDs.IngestionJobId

  # Validation Status
  FileStatus: !include Types/enums/file-upload-status.raml
  IngestionStatus: !include Types/enums/ingestion-job-status.raml

  # Algorihtm
  FileHashAlgorithm: !include Types/enums/file-hash-algorithm.raml
  
  # Method
  UploadMethod: !include Types/enums/upload-method.raml
  IngestionBehavior: !include Types/enums/ingestion-behavior.raml