openapi: 3.0.3
info:
  title: Seo
  version: v1
  description: "# API Overview\n\nThis API uploads a custom sitemap and triggers the sitemap generation process. \n\nTBD: Are there any guides we can/should link to here?\n\n## Authentication & Authorization\n\nFor resource access, you must use a client ID and client secret from Account Manager to request an access token. The access token is used as a bearer token and added to the `Authorization` header of your API request.\n\nThe API client must also have at least one of the following OAuth scopes: <TBD>. You must include the relevant scope(s) in the client ID used to generate the token. For details, see the [Authorization Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html)\n\nFor detailed setup instructions, see the [Authorization for Admin APIs](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-admin-apis.html) guide.\n\n## Use Cases\n\nTBD"
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/site/seo/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/sitemap:
    put:
      summary: Upload a custom sitemap and trigger sitemap generation process.
      description: This API uploads a custom sitemap and triggers the sitemap generation process.
      operationId: uploadCustomSitemapAndTriggerSitemapGeneration
      security:
        - AmOAuth2:
            - sfcc.seo.rw
      responses:
        '202':
          description: The site generation process runs asynchronously and takes a few minutes to complete. The generated sitemap is available at the location specified in the location header.
          headers:
            Location:
              description: The generated sitemap location url
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                putSitemap400:
                  $ref: '#/components/examples/putSitemap400'
        '404':
          description: The given hostname was not found in the alias file.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                putSitemap404:
                  $ref: '#/components/examples/putSitemap404'
        '409':
          description: The requested action could not be completed because the job is currently running and its state is being updated.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                putSitemap409:
                  $ref: '#/components/examples/putSitemap409'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SitemapRequest'
            examples:
              sitemapRequestBody:
                $ref: '#/components/examples/sitemapRequestBody'
        required: true
    parameters:
      - $ref: '#/components/parameters/organizationId'
      - $ref: '#/components/parameters/siteId'
components:
  securitySchemes:
    AmOAuth2:
      type: oauth2
      description: AccountManager OAuth 2.0 bearer token Authentication.
      flows:
        clientCredentials:
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            sfcc.seo.rw: Allows write operations on seo.
        authorizationCode:
          authorizationUrl: https://account.demandware.com/dwsso/oauth2/authorize
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            sfcc.seo.rw: Allows write operations on seo.
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
    String4000:
      type: string
      maxLength: 4000
      description: "The String4000 schema is a foundational schema designed for fields or attributes that are stored in a database field with a maximum capacity of 4000 bytes. \nThis schema accommodates various character sets, with the following considerations:\n  - ASCII Characters: Each ASCII character occupies 1 byte, allowing up to 4000 characters.\n  - Latin Characters: Many Latin characters require 2 bytes each, allowing up to 2000 characters.\n  - Asian Characters: Many Asian characters require 3 bytes each, allowing approximately 1333 characters."
      example: This is a detailed description of an Excellent Product. It includes all the features, specifications, and benefits of the product. The Excellent Product is designed to provide exceptional performance and reliability. It is made from high-quality materials and has been rigorously tested to ensure it meets the highest standards. Whether you are using it for personal or professional purposes, the Excellent Product is the perfect choice. With its advanced technology and user-friendly design, it offers unparalleled convenience and efficiency. Order your Excellent Product today and experience the difference it can make.
    SitemapRequest:
      properties:
        customSitemapFile:
          description: The custom sitemap file to be uploaded. Must conform to the [Sitemap Protocol](https://www.sitemaps.org/protocol.html), with a root `<urlset>` element and well-formed `<url>` entries.The filename must not start with `sitemap` nor contain forward or backward slashes. The file must contain valid xml content and the filename must have an .xml extension.
          allOf:
            - $ref: '#/components/schemas/String4000'
          example: custom-sitemap.xml
        hostname:
          minLength: 1
          description: The hostname for which the sitemap will be generated. The hostname must be listed in the aliases file in Business Manager
          allOf:
            - $ref: '#/components/schemas/String4000'
          example: www.abc.com
      required:
        - customSitemapFile
        - hostname
      type: object
    Location:
      maxLength: 2048
      description: URL where the resource is located.
      example: /index.html
      type: string
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
  examples:
    sitemapRequestBody:
      value:
        customSitemapFile: sitemap.xml
        hostname: secure.sitegenesis.com
    putSitemap400:
      value:
        title: Bad Request
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/validation
        detail: The custom sitemap must be an XML file.
    putSitemap404:
      value:
        title: The given hostname was not found in the alias file.
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors
        detail: The hostname was not found in the alias file.
        hostname: www.abc.com
    putSitemap409:
      value:
        title: Sitemap Generation In Progress
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/validation
        detail: The previous generate sitemap request has not completed.
