#%RAML 1.0 DataType
description: This object defines a single Inventory Import Future
type: object
properties:
  future:
    description: A single import inventory item future
    type: !include ../GlobalTypes/Future.raml