#%RAML 1.0 DataType
description: This object is the import location inventory record
type: object
properties:
  location:
    description: The location name of the inventory item
    type: string
    example: warehouse1
  inventory-record: !include ImportInventoryRecord.raml