#%RAML 1.0 DataType

description: This type contains the structure for the initiate sku exclusions import request body
properties:
  fileName:
    description: the filename to be imported.
    type: string
    example: "sku_exclusion_import.json"
  linkDuration:
    description: the duration the uploadlink shall remain active after being created.
    type: number
    example: 60
