#%RAML 1.0 NamedExample
value:
  {
    "timestamp": "2020-07-06T18:10:45.927+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "No message available",
    "path": "/inventory/impex/v1/organizations/myOrgId/location-graph/exports",
    "type": "about:blank"
  }