#%RAML 1.0
#In C4E review
title: Baskets
description: |-
   Provides access to the Headless Commerce APIs for basket management related functionality.
version: v1
protocols: HTTPS
mediaType: application/json
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/checkout/baskets/{version}
baseUriParameters:
  shortCode:
    description: |-
      Region-specific merchant identifier.
    example: fd4gt8

uses:
  StatusCodes: status-codes.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.15/commerce-cloud-standards.raml 
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/api-standards.raml

types:
'/organizations/{organizationId}':
  type: CommerceCloudStandards.Organization
  '/baskets':
    type: CommerceCloudStandards.Organization
    '/{basketId}':
      type: CommerceCloudStandards.Organization
      uriParameters:
        basketId:
          description: |-
            The basket identifier.
          minLength: 1
          type: string
          example: "bczFTaOjgEqUkaaadkvHwbgrP5"
      delete:
        description: |-
          Deletes a basket.
        is:
          - StatusCodes.NoContent
          - StatusCodes.BasketNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited:
              responseStatus: 204
          - ApiStandards.RateLimited:
              responseStatus: 404
        displayName: deleteBasket
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.baskets", "sfcc.baskets.rw" ] }
          - CommerceCloudStandards.AmOAuth2
