#%RAML 1.0 Library
#In C4E review
usage: Use the following traits for request and response status information.

types:
  ErrorResponse: !include exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/dataTypes/error-response.raml

traits:
  OK-Basket: !include traits/ok-basket.raml
  OK-PriceAdjustment: !include traits/ok-price-adjustment.raml
  OK-PriceAdjustments: !include traits/ok-price-adjustments.raml
  OK-ProductPriceAdjustment: !include traits/ok-product-price-adjustment.raml
  OK-ProductPriceAdjustments: !include traits/ok-product-price-adjustments.raml
  BasketNotFound: !include traits/basket-not-found.raml
  PriceAdjustmentNotFound: !include traits/price-adjustment-not-found.raml
  ProductItemNotFound: !include traits/product-item-not-found.raml
  ShippingItemNotFound: !include traits/shipping-item-not-found.raml
  SiteNotFound: !include traits/site-not-found.raml
  CreatedNoContent: !include traits/created-no-content.raml
  NoContent: !include traits/no-content.raml
  BadRequest: !include traits/bad-request.raml
