#%RAML 1.0 DataType
description: The delta token obtained from a full export or a previous request to this API
example: e3NoYXJkSWQtMDAwMDAwMDE1NzczOTkxNTc2MDItYmE5MGYxNGE6MDAwMDAwMDAwMDAwMDAwMDAwNDQ0fQ==
type: string