#%RAML 1.0 DataType

description: The effective date for the info provided. The date represents when the onHand value was accurate at the location.
type: union
anyOf:
  - type: datetime
    example: 2019-07-24T21:13:00Z
    format: rfc3339
    displayName: Valid date 
  - type: nil
    example: null
