#%RAML 1.0 DataType
properties:
  errorCode:
    type: !include ErrorCodeTypeEnum.raml
  message: string
  title: 
    type: string
    required: false
  detail: 
    type: string
    required: false
  instance: 
    type: string
    required: false
  type:
    type: string
    required: false