#%RAML 1.0 DataType
description: |
  A convenience identifier for the consumer, used for auditing events. This field is NOT used by the service itself, but is intended for the consumer to be able to identify records submitted from their systems that are external to OCI.  
  
  NOTE: Currently, there is no way to export the event log, so currently the field is only useful when interacting with support staff.
example: 7282822-9823-aaa
type: string