#%RAML 1.0 DataType

description: The 'future' object contains data that tells us what is expected to arrive for this item in the future, as well as when those amounts of inventory should arrive.
properties:
  expectedDate:
    example: 2019-08-24T21:13:00Z
    description: The date the future quantity is expected to arrive at the location
    type: !include Date.raml
  quantity:
    description: The amount that is expected to arrive at a future date
    type: number
    minimum: 0.001
    multipleOf: 0.001
    example: 10.25
