#%RAML 1.0 DataType

description: The group info, associated with an item and used in the availability responses.
properties:
  id:
    type: !include GroupId.raml
  records:
    description: Records returned for a sku/group combination
    type: array
    items:
      type: !include RecordWithEffectiveDateNotRequired.raml
