#%RAML 1.0 DataType

description: Location information used for availability by location responses

properties:
  id:
    type: !include LocationId.raml
  records:
    description: Records returned for the sku/location combination
    type: array
    items: 
      type: !include RecordWithEffectiveDateNotRequired.raml