#%RAML 1.0
title: Promotions
version: v1
protocols: HTTPS
mediaType: application/json
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/pricing/promotions/{version}
baseUriParameters:
  shortCode:
    description: A region-specific merchant identifier.
    example: 0dnz6oep
    pattern: ^([a-z0-9]+)(-[a-z0-9]+)*$
description: !include promotions-description.md

uses:
    DataPromotionTraits: promotions-traits-library.raml
    ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/api-standards.raml
    CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.20/commerce-cloud-standards.raml

types:
  Campaign:
    description: Document representing a campaign.
    properties:
      campaignId:
        description: The ID of the campaign.
        maxLength: 256
        minLength: 1
        type: string
      coupons:
        description: The array of assigned coupon IDs, not sorted.
        type: array
        items:
          type: string
        required: false
      creationDate:
        description: Returns the value of attribute 'creationDate'.
        type: datetime
        required: false
      customerGroups:
        description: The array of assigned customer groups, not sorted.
        type: array
        items:
          type: string
        required: false
      description:
        description: The description of the campaign.
        maxLength: 4000
        type: string
        required: false
      enabled:
        description: The enabled flag for campaign.
        type: boolean
        required: false
      endDate:
        description: The date the scenario ends.
        type: datetime
        required: false
      lastModified:
        description: Returns the value of attribute 'lastModified'.
        type: datetime
        required: false
      sourceCodeGroups:
        description: The array of assigned source code groups, not sorted.
        type: array
        items:
          type: string
        required: false
      startDate:
        description: The date the scenario begins.
        type: datetime
        required: false
  Promotion:
    description: |-
      Document representing a promotion. Unless otherwise stated, attributes of this document are not supported when using
       the Open Commerce API to update multiple promotions at once.
    properties:
      archived:
        description: |-
          Determines if this promotion is archived. This attribute is allowed to be updated when using the Open
           Commerce API to update multiple promotions at once.
        type: boolean
        required: false
      assignmentInformation:
        description: Information about the assignments and assignment schedules of this promotion.
        type: PromotionAssignmentInformation
        required: false
      creationDate:
        description: Returns the value of attribute 'creationDate'.
        type: datetime
        required: false
      currencyCode:
        description: |-
          The ISO 4217 mnemonic code of the currency this promotion is restricted to. If not populated, then there is no
           currency restriction on the promotion.
        maxLength: 3
        type: string
        required: false
      disableGloballyExcluded:
        description: Determines if this promotion ignores the global product exclusions for promotions.
        type: boolean
        required: false
      enabled:
        description: |-
          Determines if this promotion is enabled. This attribute is allowed to be updated when using the Open
           Commerce API to update multiple promotions at once.
        type: boolean
        required: false
      exclusivity:
        description: |-
          Determines if the promotion can be combined with other promotions of the same promotion class or if it cannot be
           combined with any other promotions. This attribute is allowed to be updated when using the Open Commerce API to
           update multiple promotions at once.
        type: string
        enum:
          - 'no'
          - class
          - global
        required: false
      id:
        description: The ID for the promotion.
        type: string
        required: false
      lastModified:
        description: Returns the value of attribute 'lastModified'.
        type: datetime
        required: false
      name:
        description: The user supplied name of this promotion, which can be localized.
        type: object
        properties:
          //:
            type: string
        required: false
      promotionClass:
        description: |-
          The class of the promotion. If the promotion class is modified, then the promotion rule and all of its values,
           such as whether or not to disable global product exclusions, are reset.
        type: string
        enum:
          - product
          - shipping
          - order
        required: false
      tags:
        description: |-
          Returns the list of tags assigned to this promotion. If used to set the tags on a promotion, the promotion will
           only have the tags passed in the input. Any existing tags are removed.
        type: array
        items:
          type: Tag
        required: false
      siteId?: CommerceCloudStandards.SiteId
  PromotionAbtestGroupAssignment:
    properties:
      abtestDescription:
        type: string
      abtestId:
        type: string
      enabled:
        type: boolean
      schedule:
        type: Schedule
      segmentDescription:
        type: string
      segmentId:
        type: string
  PromotionAssignmentInformation:
    properties:
      abtestId:
        description: |-
          If there is only one assignment, and that assignment is an A/B test segment, the ID of the A/B test the segment
           belongs to. Otherwise, empty.
        type: string
        required: false
      abtestSegmentId:
        description: |-
          If there is only one assignment, and that assignment is an A/B test segment, the ID of the A/B test segment.
           Otherwise, empty.
        type: string
        required: false
      active:
        description: True if the individual assignment or the multiple assignments are currently active.
        type: boolean
      activeAbtestAssignments:
        description: A list of currently active A/B tests this is assigned to.
        type: array
        items:
          type: PromotionAbtestGroupAssignment
        required: false 
      activeCampaignAssignments:
        description: A list of currently active campaigns this is assigned to.
        type: array
        items:
          type: PromotionCampaignAssignment
      campaignId:
        description: If there is only one assignment, and that assignment is a campaign, the ID of the campaign. Otherwise, empty.
        type: string
      enabled:
        type: boolean
      endDate:
        description: |-
          The end date of the container of the assignment (a Campaign or ABTest). If scheduleType is
           scheduleType : "multiple" or scheduleType : "none", then then result is null. Also, a null
           date returns null.
        type: datetime
        required: false
      schedule:
        description: |-
          The schedule of the assignment (a Campaign or ABTest). If scheduleType is
           scheduleType : "multiple" or scheduleType : "none", then then result is null.
        type: Schedule
      scheduleType:
        description: |-
          If there is only one active assignment, or no active assignments and one upcoming assignment, this is that type
           of assignment (scheduleType : "campaign" or scheduleType : "abtest"). If there are no
           assignments, it is scheduleType : "none", otherwise, scheduleType : "multiple".
        type: string
        enum:
          - none
          - campaign
          - abtest
          - multiple
      startDate:
        description: |-
          The start date of the container of the assignment (a Campaign or ABTest). If scheduleType is
           scheduleType : "multiple" or scheduleType : "none", then then result is null. Also, a null
           date returns null.
        type: datetime
        required: false
      upcomingAbtestAssignments:
        description: A list of upcoming A/B tests this is assigned to.
        type: array
        items:
          type: PromotionAbtestGroupAssignment
        required: false
      upcomingCampaignAssignments:
        description: A list of upcoming campaigns this is assigned to.
        type: array
        items:
          type: PromotionCampaignAssignment
        required: false
  PromotionCampaignAssignment:
    description: Document representing a promotion campaign assignment.
    properties:
      campaign:
        description: The campaign.
        type: Campaign
        required: false
      campaignId:
        description: The ID of the campaign.
        maxLength: 256
        minLength: 1
        type: string
      coupons:
        description: The sorted array of assigned coupon IDs.
        type: array
        items:
          type: string
        required: false
      customerGroups:
        description: The sorted array of assigned customer groups.
        type: array
        items:
          type: string
        required: false
      description:
        description: The description of the promotion campaign assignment.
        maxLength: 4000
        type: string
      enabled:
        description: True if the assignment resource is enabled.
        type: boolean
      promotion:
        description: The promotion.
        type: Promotion
        required: false
      promotionId:
        description: The ID of the promotion.
        maxLength: 256
        minLength: 1
        type: string
      rank:
        description: The rank of promotion campaign assignment.
        type: integer
        format: int32
        required: false
      schedule:
        description: The schedule of the assignment resource.
        type: Schedule
      sourceCodeGroups:
        description: The sorted array of assigned source code groups.
        type: array
        items:
          type: string
        required: false
  PromotionSearchResult:
    description: Document representing a promotion search result.
    type: CommerceCloudStandards.PaginatedSearchResult
    properties:
      hits:
        description: The sorted array of promotion search hits. Can be empty.
        type: Promotion[]
  Recurrence:
    description: Document representing a schedule recurrence.
    properties:
      dayOfWeek:
        description: The days of week for recurrence.
        type: array
        items:
          type: string
          enum:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
      timeOfDay:
        description: The time of the day for recurrence.
        type: TimeOfDay
  Schedule:
    description: Document representing a time schedule for slots.
    properties:
      endDate:
        description: 'The date to end of validity. ISO8601 date time format: yyyy-MM-dd''T''HH:mm:ssZ.'
        type: datetime
        required: false
      recurrence:
        description: The recurrence of the schedule by day of week and time of day. Not all schedules support a recurrence.
        type: Recurrence
        required: false
      startDate:
        description: 'The date to start validity. ISO8601 date time format: yyyy-MM-dd''T''HH:mm:ssZ.'
        type: datetime
        required: false
  Tag:
    description: Document representing a tag
    properties:
      tagId:
        description: The ID of the tag.
        type: string
  TimeOfDay:
    description: Document representing a time schedule within a single day.
    properties:
      timeFrom:
        description: |-
          The time to start from. Time format: HH:mm:ss. Seconds
           are ignored and set to 0.
        type: string
      timeTo:
        description: |-
          The time to end on. Time format: HH:mm:ss. Seconds
           are ignored and set to 0.
        type: string
'/organizations/{organizationId}/promotions':
    type: CommerceCloudStandards.Organization
    is:
      - CommerceCloudStandards.SiteSpecific
    post:
      description: |-
        Searches for promotions.
         
         The SearchRequest document contains a search object that allows filtering on various attributes.
         
         The query attribute specifies a complex query that can be used to narrow down the search using the following searchable
         attributes:
         
          | Attribute | Type |
          |-----------|--------|
          | id | String |
          | name | String |
          | currecyCode |  String |
          | exclusivity |  String |
          | enabled | Boolean |
         
         Note that only searchable attributes can be used in sorting. Additionally, the following attribute can be used to
         sort:
         
          | Attribute | Type |
          |-----------|--------|
          | promotionClass | String |

      displayName: promotionsSearch
      is:
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
      responses:
        '200':
          description: Search promotions successfully.
          body:
            application/json:
              type: PromotionSearchResult
        '400':
          description: Thrown if the query is ill-formed.
      body:
        application/json:
          type: CommerceCloudStandards.SearchRequest
      securedBy:
        - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
        - CommerceCloudStandards.AmOAuth2
    '/{id}':
      is:
        - CommerceCloudStandards.SiteSpecific
      uriParameters:
          id:
            description: The ID of the promotion to create.
            minLength: 1
            type: string
            example:
              -Buy5for50
              -$5_off_ties_promotion
      delete:
          description: Deletes the promotion by ID.
          displayName: deletePromotion  
          is:
            - ApiStandards.RateLimited:
                responseStatus: 204
          responses:
            '204':
              description: Deleted the promotion successfully.
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2
      get:
          description: Action to get promotion information.
          displayName: getPromotion
          is:
            - DataPromotionTraits.PromotionNotFound:
            - ApiStandards.RateLimited:
                responseStatus: 200
            - ApiStandards.RateLimited:    
                responseStatus: 404
          responses:
            '200':
              description: Retrieved promotion information successfully.
              body:
                application/json:
                  type: Promotion
                  examples:
                    promotionGetResponse: !include Examples/get-promotion-response.raml
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2
      patch:
          description: Updates the promotion with the specified information.
          displayName: updatePromotion
          is:
            - DataPromotionTraits.PromotionNotFound:
            - ApiStandards.RateLimited:
                responseStatus: 200
            - ApiStandards.RateLimited:    
                responseStatus: 404
          responses:
            '200':
              description: |-
                Update a promotion using the information provided.
                Fields that can be updated:
                name, ID, enabled
              body:
                application/json:
                  type: Promotion
                  examples: 
                    promotionPatchResponse: !include Examples/patch-promotion-response.raml
          body:
            application/json:
              type: Promotion
              examples: 
                promotionPatchRequest: !include Examples/patch-promotion-request.raml
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2
      put:
          description: Creates a promotion using the information provided.
          displayName: createPromotion
          is:
            - DataPromotionTraits.PromotionIdConflict:
            - ApiStandards.RateLimited:
                responseStatus: 200
            - ApiStandards.RateLimited:    
                responseStatus: 400
          responses:
            '200':
              description: Creates a promotion using the information provided.
              body:
                application/json:
                  type: Promotion
                  examples:
                    promotionPutResponse: !include Examples/put-promotion-response.raml
          body:
            application/json:
              type: Promotion
              examples:
                promotionPutRequest: !include Examples/put-promotion-request.raml
          securedBy:  
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2