#%RAML 1.0 DataType
description: Generic response generated when an attempt is made to delete multiple import batches

properties:
  deleted:
    type: array
    items: !include ../GlobalTypes/UniqueId.raml
    example: [323b0g69-d37d-423a-84f5-8f393fe80459]
  errors:
    type: array
    items: !include DeletedImportErrorsObjects.raml