#%RAML 1.0 DataType

properties:
  id:
    type: string
    description: The ID of the import that failed delete
    example: a94a8fe5-ccb1-9ba6-1c4c-0873d3412f8
  message:
    type: string
    description: The message associated with the deletion error
    example: "Failed to delete"
  errorCode: 
    type: string
    description: The code associated with the deletion error
    example: "err205"     