#%RAML 1.0 DataType

description: Batch import status request response
type: object
example: !include ../../Examples/ImportGetBatchStatusResponseExample.raml
properties:
  results:
    type: array
    items: !include ImportStatusResponseObject.raml