#%RAML 1.0 DataType

description: The file upload has been successfully started. Details about the upload are available in the response body.
properties:
  status:
    type: string
    description: The overall status of the import of the file. Can be either PENDING, RUNNING, or COMPLETED.
    example: PENDING
  importId:
    type: string
    description: The UUID of the import job.
    example: d88e54c5-23ed-4e33-a6a9-c31dc810662b      