#%RAML 1.0 DataType

description: Common response from import initiation calls
properties:
  importId: 
    type: string
    description: The ID associated with the initiated import
    example: d88e54c5-23ed-4e33-a6a9-c31dc810662b
  importStatusLink:
    type: string
    description: URI where import status can be acquired
    example: "/inventory/impex/v1/organizations/testOrg/availability-records/imports/d88e54c5-23ed-4e33-a6a9-c31dc810662b/status"
  uploadLink:
    type: string
    description: URL to submit the upload file
    example: "/inventory/impex/v1/organizations/testOrg/availability-records/imports/uploadlink/d88e54c5-23ed-4e33-a6a9-c31dc810662b"
  uploadMethod:
    type: string
    description: Upload HTTP Method, i.e. Multipart/Form
    example: POST
  uploadLinkExpirationUTC:
    type: datetime
    description: ISO Time when upload link expires
    example: 2019-06-07T15:10:04.357Z
    format: rfc3339