#%RAML 1.0 Trait

usage: This trait allows for taking in an input header containing the meta data about the client's request.

headers:
  meta-data-env?:
    description: Header defining the client's environment of the incoming request to discovery. The expected values are prod or non-prod.
    type: string
    maxLength: 10
    example: prod
  meta-data-usage?:
    description: Header defining the usage of the incoming request to discovery. The expected values are b2b, b2c or content.
    type: string
    maxLength: 10
    example: b2b
  meta-data-implementation?:
    description: Header defining the implementation type of the incoming request to discovery. The expected values are hsr, canonical or custom.
    type: string
    maxLength: 15
    example: hsr