#%RAML 1.0 DataType
properties:
  firewallruleId?:
    type: string
    maxLength: 100
    example: 295a8932ghnml74b286t15
  zoneId:
    type: string
    maxLength: 100
    description: Identity of the zone the WAF group belongs to.
  type:
    type: string
    enum: ["ip", "country"]
    description: Type of the firewall rule
    example: ip
  action:
    type: string
    enum: ["blocklist", "allowlist"]
    description: The action applied by the firewall rule
    example: blocklist
  values:
    type: string[]
    description: Values of the type specified. IPs can be individual IPs or CIDR blocks. For countries use 2 letter ISO 3166 country codes https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

examples:
  example1:
    firewallruleId: 321at3d0254n46ht10kl10ct20
    zoneId: example1-zone-Id
    type: country
    action: allowlist
    values: ["US","JP"]
  example2:
    firewallruleId: 537at3d0254p46ht2fkl79cb13
    zoneId: example2-zone-Id
    type: ip
    action: blocklist
    values: ["127.0.0.1","192.168.0.0/16"]

