#%RAML 1.0 NamedExample
value:
  {
    "limit": 1,
    "data": [
      {
        "productId": "apple-ipod-classic-1",
        "variationValues": {
          "color": "Silver",
          "memorySize": "120 GB"
        }
      }
    ],
    "offset": 0,
    "total": 1
  }