#%RAML 1.0 NamedExample
value:
  {
    "description": {
        "default": "desc of 8 (default)",
        "en-US": "desc of 8 (en-US)",
        "en": "desc of 8 (en)"
    },
    "position": 1.0,
    "value": "8"
  }