#%RAML 1.0 NamedExample
value:
  [
    {
      "amount": {
        "currencyMnemonic": "USD",
        "value": 1000.00
      },
      "balance": {
        "currencyMnemonic": "USD",
        "value": 1000.00
      },
      "creationDate": "2020-01-10T21:31:49.242Z",
      "description": "Birthday Gift",
      "enabled": false,
      "lastModified": "2020-01-10T21:31:49.246Z",
      "maskedGiftCertificateCode": "************KHAL",
      "merchantId": "00001001",
      "message": "A birthday gift for you",
      "orderNo": "CA17293",
      "recipientEmail": "john.doe@gmail.com",
      "recipientName": "John Doe",
      "senderName": "Jane Doe",
      "status": "issued",
      "transactions": [
        {
          "amount": {
            "currencyMnemonic": "USD",
            "value": 1000.00
          },
          "orderNo": "CA17293",
          "timestamp": "2020-01-10T21:31:49.244Z",
          "typeCode": "create"
        }
      ]
    }
  ]