#%RAML 1.0 NamedExample
value:
  {
   "amount" : 
   {
      "currencyMnemonic" : "USD",
      "value" : 100.00
   },
   "balance" : 
   {
      "currencyMnemonic" : "USD",
      "value" : 100.00
   },
   "creationDate" : "2015-07-31T15:05:52.311Z",
   "description" : "Gift certificate sample description-updated",
   "enabled" : false,
   "maskedGiftCertificateCode" : "***********cate",
   "merchantId" : "my-merchant_id",
   "message" : "Gift certificate sample message-updated",
   "orderNo" : "my-order_no",
   "recipientEmail" : "updatedemail@abc.com",
   "recipientName" : "xyz-updated",
   "senderName" : "abc-updated",
   "status" : "pending",
   "transactions" : 
    [
        {
            "amount" : 
            {
                "currencyMnemonic" : "EUR",
                "value" : 80.00
            },
            "orderNo" : "my-order-no",
            "timestamp" : "2015-09-09T17:16:12.066Z",
            "typeCode" : "create"
        }
    ]   
}