#%RAML 1.0 Library
#In C4E review
usage: This library provides all order relevant data types

types:
  ErrorResponse: !include ../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.3/dataTypes/error-response.raml
  OrderUpdateRequest:
    description: Request body to update custom properties.
    properties:
  PaymentInstrumentUpdateRequest:
    description: Request body to update custom properties.
    properties:
  PaymentTransactionUpdateRequest:
    description: Request body to update custom properties.
    properties:
  OrderConfirmationStatusUpdateRequest:
    description: Request body to update the order confirmation status.
    properties:
      status:
        description: The new confirmation status for an order.
        type: string
        enum:
          - confirmed
          - not_confirmed
  OrderExportStatusUpdateRequest:
    description: Request body to update the order export status.
    properties:
      status:
        description: The new export status for an order.
        type: string
        enum:
          - exported
          - not_exported
          - ready
          - failed
  OrderExternalStatusUpdateRequest:
    description: Request body to update the order external status.
    properties:
      status:
        description: The new external status for an order.
        maxLength: 256
        minLength: 1
        type: string
  OrderPaymentStatusUpdateRequest:
    description: Request body to update the order payment status.
    properties:
      status:
        description: The new payment status for an order.
        type: string
        enum:
          - paid
          - part_paid
          - not_paid
  OrderShippingStatusUpdateRequest:
    description: Request body to update the order shipping status.
    properties:
      status:
        description: The new shipping status for an order.
        type: string
        enum:
          - shipped
          - part_shipped
          - not_shipped
  OrderStatusUpdateRequest:
    description: Request body to update the order status.
    properties:
      status:
        description: The new status for an order.
        type: string
        enum:
          - created
          - new
          - open
          - completed
          - cancelled
          - failed
  ShippingAddressUpdateRequest:
    description: Request body to update the shipping address.
    properties:
      address1?:
        type: string
      address2?:
        type: string
      city?:
        type: string
      company_name?:
        type: string
      country_code?:
        type: string
      first_name?:
        type: string
      full_name?:
        type: string
      id?:
        type: string
      job_title?:
        type: string
      last_name?:
        type: string
      phone?:
        type: string
      post_box?:
        type: string
      postal_code?:
        type: string
      salutation?:
        type: string
      second_name?:
        type: string
      state_code?:
        type: string
      suffix?:
        type: string
      suite?:
        type: string
      title?:
        type: string