#%RAML 1.0 Library
#In C4E review
usage: Use the following traits for request and response status information.

traits:
  Success: !include traits/success.raml
  OrderNotFound: !include traits/order-not-found.raml
  SiteNotFound: !include traits/site-not-found.raml
  PaymentInstrumentNotFound: !include traits/payment-instrument-not-found.raml
  ShipmentNotFound: !include traits/shipment-not-found.raml
  BadRequest: !include traits/bad-request.raml
  StatusTransitionConflict: !include traits/status-transition-conflict.raml
  CancelOrderConflict: !include traits/cancel-order-conflict.raml
  PlaceOrderConflict: !include traits/place-order-conflict.raml
  UndoCancelOrderConflict: !include traits/undo-cancel-order-conflict.raml
  UndoFailOrderConflict: !include traits/undo-fail-order-conflict.raml