#%RAML 1.0 DataType

description: Common response from export reservations initiation calls
properties:
  exportId: 
    type: string
    description: The ID associated with the initiated reservations export
    example: 60679175-C589-49A9-87FE-DC07F657D7C0
  exportStatusLink:
    type: string
    description: URI where reservations export status can be acquired
    example: "/inventory/impex/v1/organizations/testOrg/reservations/exports/60679175-C589-49A9-87FE-DC07F657D7C0/status"