#%RAML 1.0 Trait
description: 404 response when a customer is not found.
responses:
  '404':
      description: |
                Requested Resource Not Found
      body:
        application/json:
          type: Error
          example: 
            {
            "type": "CustomerNotFoundException",
            "title": "Customer with the given customer id is unknown.",
            "detail": "No customer with ID 'abfTWMDZOgi3JPzkHjv9IhmziI' could be found.",
            "instance": "/blah"
          }