#%RAML 1.0 DataType

type: object
properties:
  arguments:
    type: object
    description: A map that provides fault arguments. Data can be used to provide error messages on the client side.
    required: false
  displayMessagePattern: 
    type: string
    description: The localized display message pattern, if the request parameter display_locale was given
    required: false  
  message:
    type: string
    description: The message text of the java exception.
    required: true 
  type:
    type: string
    description: The name of the java exception.
    required: true