#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response for a duplicate campaign in the Data Campaigns API.
responses:
  400:
    description:
      Thrown if a campaign exists already in the site with the given campaign ID.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
          "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/campaign-duplicate",
          "detail": "The campaign couldn't be created because of duplicate ID 'CampaignXYZ'.",
          "title": "Duplicate Error"
          }  