#%RAML 1.0
title: Shopper SEO
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/site/shopper-seo/{version}
description: Provides access to SEO-related information, such as URL mapping information.
mediaType:
  - application/json
version: v1
protocols: [HTTPS]
uses:
  ShopperSeoTrait: Traits/ShopperSeoTrait.raml
  ShopperSeoLib: shopper-seo-library.raml
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.15/api-standards.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.27/commerce-cloud-standards.raml
baseUriParameters:
  shortCode:
    description: Region-specific merchant identifier.
    example: fd4gt8
    pattern: ^([a-z0-9]+)(-[a-z0-9]+)*$

/organizations/{organizationId}:
  type: CommerceCloudStandards.Organization
  /url-mapping:
    get:
      description: Gets URL mapping information for a given URL segment. The returned information contains the type of resource the provided urlSegment is associated with - CATEGORY, PRODUCT or CONTENT_ASSET. If any refinements are part of the urlSegment, and if they have been configured in Business Manager, they are returned as a map in the response.
      displayName: getUrlMapping
      is:
        - CommerceCloudStandards.SiteSpecific:
        - ShopperSeoTrait.LocaleSpecific:
        - ShopperSeoLib.BadRequest
        - ShopperSeoLib.Unauthorized
        - ShopperSeoLib.NotFound
      responses:
        '200': 
          description: Returns URL mapping information for the given URL segment.
          body:
            type: ShopperSeoLib.UrlMapping
      queryParameters:
        urlSegment:
          description: The URL segment for which the mapping information is requested. The URL segment of a URL is the complete path of a URL. For example, the URL segment for 'www.abc.com/mens/clothing/shorts' is 'mens/clothing/shorts'. There is no limit on the maximum length of the urlSegment, but the total length of the URL (after URL encoding) should be less than 2048 characters.
          minLength: 1
          type: string
          example: mens/clothing/shirts
      securedBy:
        - CommerceCloudStandards.ShopperToken: { scopes: [sfcc.shopper-seo] }



