#%RAML 1.0 Library

traits:
  BadRequest: !include Traits/BadRequest.raml
  Unauthorized: !include Traits/Unauthorized.raml
  NotFound: !include Traits/NotFound.raml

uses:
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.15/api-standards.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.27/commerce-cloud-standards.raml

types:
  UrlMapping:
    description: URL mapping information for a given URL segment.
    type: object
    properties:
      resourceType:
        description: The type of resource.
        type: string
        enum: ['CATEGORY', 'PRODUCT', 'CONTENT_ASSET']
        minLength: 1
        maxLength: 256
      resourceId:
        description: Identifier for the resource.
        type: string
        minLength: 1
        maxLength: 256
      refinements:
        description: Relevant refinement filters inferred from the URL. It is only applicable when resource type is CATEGORY, optional for other resource types.
        type: object
        additionalProperties: true