#%RAML 1.0 DataType

description: Error generated when attempting to create a reservation with the same ID as an existing one.
properties:
  errorCode:
    enum: [ReservationInvalidState, ReservationCancelled, ConcurrentModification]
    type: string
    example: "ReservationInvalidState"
  message:
    type: string
    example: "Reservation is in a CLOSED state."
  type:
    type: string
    required: true
    example: "about:blank"
  parameterName:
    description: When invalid json is passed to the service, this field will indicate which piece of the supplied json was invalid.
    type: string
    required: false
    example: "sku"
