#%RAML 1.0 DataType

#ReservationErrorLines2
description: An alternate definition for error lines, allowing multiple different examples in the same response body
properties:
  sku:
    description: The sku associated with the failed reservation line item
    type: !include ../GlobalTypes/SkuId.raml
    example: sku5678
    required: true
  errorCode:
    description: The error code associated with the error line item.
    type: string
    example: InsufficientQuantity
