#%RAML 1.0 DataType

#ReservationSuccessfulLines:
description: Successful reservation lines
properties:
  sku:
    description: The sku associated with the successful reservation line item
    type: !include ../GlobalTypes/SkuId.raml
    required: true
    example: "sku1234"
  quantity:
    description: The quantity amount associated witht he successful reservation line item
    type: number
    example: 10.10