#%RAML 1.0 NamedExample
value:
  {
    "type": "about:blank",
    "errorCode": "InvalidRequestParameter",
    "message": "'onHand' numeric value out of bounds (<10 digits>.<3 digits> expected)",
    parameterName: "onHand"
  }