#%RAML 1.0 NamedExample
value:
  {
    "d88e54c5-23ed-4e33-a6a9-c31dc810662b": {
      "status": "AVAILABLE",
      "export": {
        "startTimeUTC" : "2019-02-12T12:34:56",
        "endTimeUTC": "2019-02-12T12:52:12",
        "recordsProcessedCount" : 2000,
        "recordsExportedCount" : 2000
      },
      "download": {
        "downloadLink": "https://inv-service.com/d88e54c5-23ed-4e33-a6a9-c31dc810662b?tokenOne",
        "downloadLinkExpirationUTC" : "2019-02-12T13:23:51Z"
      },
      "validation": {
        "fileHashType": "sha-256",
        "fileHash": "e9v2d11298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852c922",
        "fileSize": "(bytes) 5231942"
      }
    }, 
    "abcd-1234-efgh-5678-ijklm-90123": {
      "status": "AVAILABLE",
      "export": {
        "startTimeUTC" : "2019-02-12T12:34:56",
        "endTimeUTC": "2019-02-12T12:52:12",
        "recordsProcessedCount" : 2000,
        "recordsExportedCount" : 2000
      },
      "download": {
          "downloadLink": "https://inv-service.com/abcd-1234-efgh-5678-ijklm-90123?tokenOne",
          "downloadLinkExpirationUTC" : "2019-02-12T13:23:51Z"
      },
      "validation": {
        "fileHashType": "sha-256",
        "fileHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "fileSize": "(bytes) 4230948"
      }
    }
  }