#%RAML 1.0 NamedExample
value:
  { 
    "deleted": [
      "d88e54c5-23ed-4e33-a6a9-c31dc810662b",
      "da39a3ee-5e6b-4b0d-3255-bfef95601890",
      "a94a8fe5-ccb1-9ba6-1c4c-0873d391e987"
    ],
    "errors": [
      { 
        "id": "a94a8fe5-ccb1-9ba6-1c4c-0873d3943215",
        "message": "Failed to delete",
        "errorCode": "err205"
      }
    ]
  }