#%RAML 1.0 NamedExample
value:
  {
    "locations": [
        {
            "id": "surprise",
            "records": [
                {
                    "sku": "sku123",
                    "atf": 17.0,
                    "ato": 27.25,
                    "reserved": 0,
                    "safetyStockCount": 10.0,
                    "effectiveDate": "2020-04-08T14:05:22.790896-07:00",
                    "futures": [
                        {
                            "quantity": 10.25,
                            "expectedDate": "2019-08-24T21:13:00Z"
                        }
                    ],
                    "onHand": 27.0
                }
            ]
        },
        {
            "id": "wickenburg",
            "records": [
                {
                    "sku": "sku123",
                    "atf": 30.0,
                    "ato": 40.25,
                    "reserved": 0,
                    "safetyStockCount": 20.0,
                    "effectiveDate": "2020-04-08T14:05:22.790896-07:00",
                    "futures": [
                        {
                            "quantity": 10.25,
                            "expectedDate": "2019-08-24T21:13:00Z"
                        }
                    ],
                    "onHand": 50.0
                }
            ]
        }
    ]
  }