#%RAML 1.0 NamedExample
value:
  {
  "locations": [
    {
      "id": "warehouse5",
      "records": [
        {
          "sku": "sku123",
          "atf": 1137.65,
          "ato": 1147.9,
          "onHand": 0,
          "reserved": 12.5,
          "safetyStockCount": 0,
          "effectiveDate": "2019-07-24T21:13:00Z",
          "futures": [
            {
              "expectedDate": "2019-08-24T21:13:00Z",
              "quantity": 10.25
            }
          ]
        }
      ]
    }
  ],
  "groups": [
    {
      "id": "UnitedStates",
      "records": [
        {
          "sku": "sku123",
          "atf": 1137.65,
          "ato": 1147.9,
          "onHand": 0,
          "reserved": 12.5,
          "safetyStockCount": 0,
          "effectiveDate": "2019-07-24T21:13:00Z",
          "futures": [
            {
              "expectedDate": "2019-08-24T21:13:00Z",
              "quantity": 10.25
            }
          ]
        }
      ]
    }
  ]
}