#%RAML 1.0 NamedExample

value:
  {
    "results": [
      {
        "importId": "MNXW23LFOJRWKY3MN52WILTQOJXWILSBORZWS42JNZ2GKZ3SMF2GS33OKRSW4YLOOR6DKYTFMEZWMZRVFU4WIMTGFU2DGNBWFVRDEZRUFUZDGYTFME4DIMTDGEZTC___",
        "status": "Completed",
        "validation": {
          "status": "Success",
          "fileHashType": "SHA_256",
          "fileHash": {
            "expected": "70150f0a83b3eaf812517fdefa85376fac57a3796cfb2e6b413807046ccbf8fb"
          },
          "errors": [

          ]
        },
        "upload": {
          "fileName": "test.json"
        },
        "import": {
          "startTime": "2020-02-12T22:53:06.788Z",
          "endTime": "2020-02-12T22:53:08.423Z",
          "recordsProcessedCount": 4,
          "recordsReadCount": 4,
          "recordsSkippedCount": 0,   
          "fullResults": {
            "href": "/v2/tenants/AtsisIntegrationTenant/inventory/imports/MNXW23LFOJRWKY3MN52WILTQOJXWILSBORZWS42JNZ2GKZ3SMF2GS33OKRSW4YLOOR6DKYTFMEZWMZRVFU4WIMTGFU2DGNBWFVRDEZRUFUZDGYTFME4DIMTDGEZTC___/file-content",
            "exportResultExpirationUTC": "2020-02-13T15:53:05.005-07:00"
          }
        },
        "results": [

        ]
      },
      {
        "importId": "MNXW23LFOJRWKY3MN52WILTQOJXWILSBORZWS42JNZ2GKZ3SMF2GS33OKRSW4YLOOR6GCMJZMM2DSODEFUYDGNJTFU2DSNRYFU4TIYZRFVRTGNRYGQ3DMMBVG5QTC___",
        "status": "Failed",
        "validation": {
          "status": "Failed",
          "fileHashType": "SHA_256",
          "fileHash": {
            "expected": "98a91234565252380616522ce6aabf4f85738eb1d0d2a40adec75173dba195d4"
          },
          "errors": [
            "File is in GZIP format where the encoding type was not specified as GZIP' Invalid value"
          ]
        },
        "upload": {
          "fileName": "test.json"
        },
        "import": {
          "recordsProcessedCount": 0,
          "recordsReadCount": 0,
          "recordsSkippedCount": 0,
          "fullResults": {
            "href": "/v2/tenants/AtsisIntegrationTenant/inventory/imports/MNXW23LFOJRWKY3MN52WILTQOJXWILSBORZWS42JNZ2GKZ3SMF2GS33OKRSW4YLOOR6GCMJZMM2DSODEFUYDGNJTFU2DSNRYFU4TIYZRFVRTGNRYGQ3DMMBVG5QTC___/file-content",
            "exportResultExpirationUTC": "2020-02-13T15:56:44.856-07:00"
          }
        },
        "results": [
        ]
      }
    ]
  }
