#%RAML 1.0 NamedExample
value:
  [
    {
      "location": "warehouse5",
      "inventory-record": {
        "sku": "1",
        "quantity": 100,
        "safety-stock-count": 20,
        "futures": [
          "future":
            {
                "quantity": 150,
                "expectedDate": "2019-09-14T09:09:09.859-06:00"
            }
        ]
      }
    }
  ]