#%RAML 1.0 NamedExample
value:
  {
    "billingAddress": {
      "address1": "45 Main Rd.",
      "city": "Burlington",
      "countryCode": "US",
      "firstName": "John",
      "fullName": "John Doe",
      "jobTitle": "Product Manager",
      "lastName": "Doe",
      "phone": "6175555555",
      "postalCode": "01803-2336",
      "secondName": "Jr.",
      "stateCode": "MA",
      "suffix": "Jr.",
      "suite": "suite",
      "title": "M.Sc."
    },
    "businessType": "b2c",
    "channelType": "instagramcommerce",
    "currency": "USD",
    "customerLocale": "en_US",
    "orderNo": "00000041",
    "orderPriceAdjustments": [
      {
        "amount": 5.00,
        "basePrice": -6.00,
        "grossPrice": -6.00,
        "itemText": "5 off",
        "netPrice": -5.00,
        "reasonCode": "registered",
        "tax": -1.00,
        "taxBasis": 6.00
      }
    ],
    "orderTotal": 113.24,
    "paymentInstruments": [
    {
      "paymentMethodId": "CREDITCARD",
      "paymentTransaction": {
        "amount": 113.24,
        "transactionId": "abc13384ajsgdk1"
      }
    }
  ],
    "paymentStatus": "paid",
    "productItems": [
      {
        "brand": "brand",
        "basePrice": 99.00,
        "grossPrice": 103.95,
        "itemText": "Flat Front Pant",
        "netPrice": 99.00,
        "priceAdjustments": [
          {
            "amount": 5.00,
            "grossPrice": -6.00,
            "itemText": "5 off",
            "netPrice": -5.00,
            "reasonCode": "registered",
            "tax": -1.00
          }
        ],
        "productId": "701643632930",
        "productName": "Flat Front Pant",
        "quantity": 1,
        "shipmentId": "00000001",
        "tax": 4.95,
        "taxBasis": 99.00,
        "taxRate": 0.05
      }
    ],
    "shipments": [
      {
        "shipmentId": "00000001",
        "shippingAddress": {
          "address1": "45 Main Rd.",
          "address2": "road 2",
          "salutation": "Mr.",
          "postBox": "none",
          "companyName": "Salesforce",
          "city": "Burlington",
          "countryCode": "US",
          "firstName": "John",
          "fullName": "John Doe",
          "jobTitle": "Product Manager",
          "lastName": "Doe",
          "phone": "6175555555",
          "postalCode": "01803-2336",
          "stateCode": "MA",
          "suffix": "Jr.",
          "suite": "suite",
          "title": "M.Sc."
        },
        "shippingMethod": "EXPRESS",
        "shippingTotal": 21.29,
        "taxTotal": 4.95
      }
    ],
    "taxTotal": 7.90
  }