#%RAML 1.0 NamedExample
value:
  {
  "billingAddress": {
    "address1": "43 Main Rd.",
    "city": "Burlington",
    "firstName": "Jane",
    "lastName": "Doe"
  },
  "channelType": "instagramcommerce",
  "currency": "USD",
  "orderNo": "000028376",
  "orderTotal": 75.86,
  "taxTotal": 12.38,
  "paymentInstruments": [
    {
      "paymentMethodId": "PAYPAL",
      "paymentTransaction": {
        "amount": 75.86,
        "transactionId": "abc13384ajsgdk1"
      }
    }
  ],
  "productItems": [
    {
      "basePrice": 30.98,
      "grossPrice": 30.98,
      "netPrice": 24.79,
      "productId": "black-shoe_081273-38",
      "productName": "special edition shoe women 38",
      "quantity": 1,
      "shipmentId": "shipment1",
      "tax": 6.19
    },
    {
      "basePrice": 30.98,
      "grossPrice": 30.98,
      "netPrice": 24.79,
      "productId": "red-shirt_2937298-xl",
      "productName": "t shirt XL",
      "quantity": 1,
      "shipmentId": "shipment2",
      "tax": 6.19
    }
  ],
  "shipments": [
    {
      "shipmentId": "shipment1",
      "shippingAddress": {
        "address1": "43 Main Rd.",
        "city": "Burlington",
        "firstName": "Jane",
        "lastName": "Doe"
      },
      "shippingMethod": "GROUND",
      "shippingTotal": 4.95,
      "taxTotal": 0.00
    },
    {
      "shipmentId": "shipment2",
      "shippingAddress": {
        "address1": "45 Main Rd.",
        "city": "Burlington",
        "firstName": "John",
        "lastName": "Doe"
      },
      "shippingMethod": "EXPRESS",
      "shippingTotal": 8.95,
      "taxTotal": 0.00
    }
  ]
}