#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in Data Catalogs API.
responses:
  400:
    description: |
            Bad Request. Thrown in case a specified parameter value is unknown.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Bad Request",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-query-parameter",
            "detail": "offset-BAD-REQUEST parameters are not defined in RAML."
          }
