#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 not found in Data Customer Groups API.
responses:
  '404':
    description: Not Found. This error is thrown if the ID does not match any of the customer group sites or if the ID is ill-formed.
    body:
      application/problem+json:
        type: ErrorResponse
        example:  |
          {
            "title": "Customer List Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/customer-list-not-found",
            "detail": "No customer list with ID 'SiteGenesis-NOT-FOUND' could be found.",
            "customerListId": "SiteGenesis-NOT-FOUND"
          }
