#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 400 - Bad Request.

uses:
  ApiStandards: ../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.15/api-standards.raml

responses:
  400:
    description: |
      The request sent by the caller is not valid.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/bad-request-example.raml