#%RAML 1.0 Trait
description: This trait represents API behavior for a 409 conflict in Data Customer Groups API.
responses:
  '409':
    description: Conflict. This error is thrown when attempting to create a record that already exists.
    body:
      application/json:
        type: Error