#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in Data Catalogs API.
responses:
  400:
    description: |
            Bad Request. Thrown in case a specified parameter value is unknown.
    body:
      application/json:
        type: Error
        example: |
          {
            "type": "InvalidQueryParameterException",
            "title": "An invalid query parameter 'link' was found.",
            "detail": "Query Parameter is not valid"
          }
