#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-code-create",
  "title": "Coupon Code Create",
  "detail": "The coupon code 'bar' couldn't be created. Please make sure the code is valid.",
  "couponCode": "bar"
  }