#%RAML 1.0 NamedExample
value:
  {
  "couponId": "MyCoupon",
  "creationDate": "2019-10-20T12:00:00Z",
  "description": "This coupon is used to give 10% off stuff.\n",
  "enabled": false,
  "exportedCodeCount": 0,
  "lastModified": "2019-10-30T04:23:59Z",
  "redemptionCount": 3,
  "redemptionLimits": {
    "limitPerCode": 0,
    "limitPerCustomer": 0,
    "limitPerTimeFrame": {
      "redemptionTimeFrame": 24,
      "limit": 1
    }
  },
  "singleCode": "MyCode",
  "systemCodesConfig": {
    "codePrefix": "SG",
    "numberOfCodes": 50000
  },
  "totalCodesCount": 50,
  "type": "single_code"
  }
  