#%RAML 1.0 NamedExample
CompletedWithPartialFailures: 
  {
    "recordId":"3dd924fb-2fd5-4f49-80de-6ee49439c1f0",
    "locationId":"wickenburg",
    "sku":"1",
    "message":"'quantity' quantity must be a positive value"
  }
CompletedWithoutErrors: 
  {
    "status":"COMPLETED_WITHOUT_ERRORS"
  }
Failed: 
  {
    "status":"FAILED"
  }
