#%RAML 1.0 NamedExample

value:
  {
      "id": "a218f4b2-2dc3-4ea8-af6d-c75fafd62256",
      "status": "COMPLETED",
      "export": {
        "startTimeUTC": "2020-04-15T21:21:23.675Z",
        "endTimeUTC": "2020-04-15T21:21:23.812Z",
        "recordsProcessedCount": 7,
        "recordsExportedCount": 7
      },
      "download": {
        "downloadLink": "/inventory/impex/v1/organizations/AtsisIntegrationTenant/location-graph/exports/a218f4b2-2dc3-4ea8-af6d-c75fafd62256/file-content",
        "downloadLinkExpirationUTC": "2020-04-16T15:21:21.93-06:00"
      },
      "validation": {
        "fileHash": "15fba5d9facf494749b9cfabdc2c8fe1c73d974b9579bc67ab293e607f3c92bb",
        "fileHashType": "SHA-256",
        "fileSize": 607
      }
  }