#%RAML 1.0 NamedExample

value:
  {
    "importId": "a218f4b2-2dc3-4ea8-af6d-c75fafd62256",
    "status": "COMPLETED",
    "validation": {
      "status": "Success",
      "errors": []
    },
    "upload": {
      "fileName": "test.json"
    },
    "import": {
      "startTimeUTC": "2020-02-12T22:53:06.788Z",
      "endTimeUTC": "2020-02-12T22:53:08.423Z",
      "recordsProcessedCount": 4,
      "recordsReadCount": 4,
      "recordsSkippedCount": 0,   
      "fullResults": {
        "href": "/v2/tenants/AtsisIntegrationTenant/availability-records/imports/a218f4b2-2dc3-4ea8-af6d-c75fafd62256/file-content",
        "exportResultExpirationUTC": "2020-02-13T15:53:05.005-07:00"
      }
    }
  }
