#%RAML 1.0 NamedExample
locations:
  {
    "objects": {
      "locations": [
        "warehouse5",
        "warehouse6"
      ]
    }
  }

groups:
  {
    "objects": {
      "groups": [
        "UnitedStates",
        "Germany"
      ]
    }
  }
