#%RAML 1.0 DataType

description: Generic file validation scheme

properties:
  fileHashType:
    description: The file hash type associated with the export file.
    type: string
    example: sha-256
  fileHash:
    description: The hash associated with the export file.
    type: string
    example: e9v2d11298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852c922
  fileSize:
    description: File size in bytes.
    type: number
    example: 5231942