#%RAML 1.0 NamedExample
value:
  {
  "billingAddress": {
    "address1": "45 Main Rd.",
    "city": "Burlington",
    "firstName": "John",
    "lastName": "Doe"
  },
  "channelType": "instagramcommerce",
  "currency": "USD",
  "orderNo": "0000091837",
  "orderTotal": 66.91,
  "taxTotal": 12.39,
  "paymentInstruments": [
    {
      "paymentMethodId": "CREDITCARD",
      "paymentTransaction": {
        "amount": 30.00,
        "transactionId": "abc13384ajsgdk1",
        "authorizationStatus": {
          "code": "0",
          "message": "credit card successfully authorized",
          "status": 0
        }
      }
    },
    {
      "paymentMethodId": "PAYPAL",
      "paymentTransaction": {
        "amount": 36.91,
        "authorizationStatus": {
          "code": "0",
          "message": "paypal authorized",
          "status": 0
        },
        "transactionId": "abceou98463"
      }
    }
  ],
  "paymentStatus": "paid",
  "productItems": [
    {
      "basePrice": 30.98,
      "grossPrice": 61.96,
      "netPrice": 49.57,
      "productId": "black-shoe_97253-38",
      "productName": "special edition shoe women 38",
      "quantity": 2,
      "shipmentId": "shipment1",
      "tax": 12.39
    }
  ],
  "shipments": [
    {
      "shipmentId": "shipment1",
      "shippingAddress": {
        "address1": "45 Main Rd.",
        "city": "Burlington",
        "firstName": "John",
        "lastName": "Doe"
      },
      "shippingMethod": "GROUND",
      "shippingTotal": 4.95,
      "taxTotal": 0.00
    }
  ]
}