#%RAML 1.0 Trait
#generic response for responses that have a body of type: ErrorCode, with placeholders for the response code, description, errorCode and error Message

uses: 
  ApiStandards: /exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.12/api-standards.raml
  ErrorEnum: ../libraries/ExceptionResponses/ErrorCodeTypesEnum.raml

responses:
  <<responseCode>>:
    description: <<description>>
    body:
      application/json:
        #type: !include ../types/ErrorCode.raml
        type: ApiStandards.ErrorResponse
        example:
          type: about:blank
          errorCode: <<errorCode>>
          message: <<message>>