#%RAML 1.0 NamedExample

value:
  {
    "data": [
      {
        "certificateId": "3822ff90-ea29-44df-9e55-21300bb9419b",
        "status": "EXPIRED",
        "hosts": ["example.com", "www.example.com"],
        "expiresOn": "2021-01-01T05:20:00Z",
        "uploadedOn": "2016-01-01T05:20:00Z"
      },
      {
        "certificateId": "730a1be4-22d7-11eb-adc1-0242ac120002",
        "status": "ACTIVE",
        "hosts": ["radtimes.com", "www.super-rad-times.com"],
        "expiresOn": "2021-01-12T04:15:57Z",
        "uploadedOn": "2016-01-12T04:15:57Z"
      }
    ]
  }