#%RAML 1.0 NamedExample

value:
  {
    "data": [
      {
        "certificateId": "3822ff90-ea29-44df-9e55-21300bb9419b",
        "status": "EXPIRED",
        "hosts": ["example.com", "www.example.com"],
        "expiresOn": "2021-01-01T05:20:00Z",
        "uploadedOn": "2016-01-01T05:20:00Z",
        "issuer": "DigiCert",
        "signature": "SHA256WithRSA",
        "customHostnameVerificationTXTName": "_example.com",
        "customHostnameVerificationTXTValue": "4c9c3f4f-2e91-4c5d-a902-f12f9c285b9e",
        "customHostnameId": "354a48f6-3d98-4c15-9312-211984ee8518",
        "customHostname": "custom.example.com",
        "customHostnameStatus": "PENDING"
      },
      {
        "certificateId": "730a1be4-22d7-11eb-adc1-0242ac120002",
        "status": "ACTIVE",
        "hosts": ["salesforce.com", "www.salesforce.com"],
        "expiresOn": "2021-01-12T04:15:57Z",
        "uploadedOn": "2016-01-12T04:15:57Z",
        "issuer": "DigiCert",
        "signature": "SHA256WithRSA",
        "customHostnameVerificationTXTName": "_salesforce.com",
        "customHostnameVerificationTXTValue": "4c9c3f4f-2e91-4c5d-a902-f12f9c285b9e",
        "customHostnameId": "465a48f6-3d98-4c15-9312-211984ee8629",
        "customHostname": "test.salesforce.com",
        "customHostnameStatus": "ACTIVE"
      }
    ]
  }