#%RAML 1.0
title: Gift Certificates
version: v1
protocols: https
mediaType: application/json
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/pricing/gift-certificates/{version}
baseUriParameters:
    shortCode:
      description: A customer region-specific identifier.
      example: 0dnz6oep
description: !include gift-certificates-description.md
uses:
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/api-standards.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.20/commerce-cloud-standards.raml
  GiftCertificateTraits: gift-certificate-traits-library.raml
types:
  AccountTransaction:
    description: Document representing an account transaction.
    properties:
      amount:
        description: The amount of the gift certificate.
        type: Money
        example: !include Examples/amount-example.raml
      orderNo:
        description: The order number of the gift certificate.
        type: string
        example: my-order-43128
      timestamp:
        description: The timestamp of the transaction of the gift certificate.
        type: datetime
        example: 2020-01-08T20:54:56.641Z
      typeCode:
        description: The type code of the gift certificate.
        type: string
        enum:
          - create
          - redeem
          - delete
          - enable
          - disable
        example: redeem
  GiftCertificate:
    description: Document representing a gift certificate.
    properties:
      amount:
        description: |-
          The gift certificate amount.
           The user cannot change the gift certificate amount after the creation of the gift certificate.
        type: Money
        required: false
        example: !include Examples/amount-example.raml
      balance:
        description: |-
          The gift certificate balance.
           This is a computed attribute and cannot be modified.
        type: Money
        required: false
        example: !include Examples/amount-example.raml
      creationDate:
        description: Returns the value of attribute 'creationDate'.
        type: datetime
        required: false
        example: 2020-01-08T20:54:56.641Z
      description:
        description: The description of the gift certificate.
        maxLength: 4000
        type: string
        required: false
        example: |
          A gift certificate for birthday.
      enabled:
        description: The enabled flag of the gift certificate.
        type: boolean
        required: false
        example: true
      lastModified:
        description: Returns the value of attribute 'lastModified'.
        type: datetime
        required: false
        example: 2020-01-08T20:54:56.641Z
      maskedGiftCertificateCode:
        description: Masked code.
        type: string
        required: false
        example: "*******XQTY"
      merchantId:
        description: |-
          The merchant ID of the gift certificate.
           This is a unique attribute.
           This is a computed attribute and cannot be modified.
           This is used to get, update and the delete gift certificates.
        type: string
        required: false
        example: |
          Macy's1256489
      message:
        description: The message to the recipient of the gift certificate.
        maxLength: 4000
        type: string
        required: false
        example: |
          This gift certificate is to be given as birthday present
      orderNo:
        description: The order number of the gift certificate.
        type: string
        required: false
        example: |
          MyOrder5421
      recipientEmail:
        description: The email address of the recipient of the gift certificate.
        type: string
        required: false
        example: |
          my-recipient-email@gmail.com
      recipientName:
        description: The recipient of the gift certificate.
        maxLength: 256
        type: string
        required: false
        example: |
          Jane Doe
      senderName:
        description: The sender of the gift certificate.
        maxLength: 256
        type: string
        required: false
        example: |
          John Smith
      status:
        description: |-
          The status of the gift certificate.
           While creating a gift certificate, user can set the status
           to either "pending" or "issued" only.
        type: string
        required: false
        enum:
          - issued
          - partially_redeemed
          - pending
          - redeemed
        example: issued
      transactions:
        description: The transactions of the gift certificate.
        required: false
        type: array
        items:
          type: AccountTransaction
        example: |
          [
                {
                    "amount": {
                        "currencyMnemonic": "USD",
                        "value": 1000
                    },
                    "orderNo": "my-test-order_no",
                    "timestamp": "2020-01-08T20:54:56.644Z",
                    "typeCode": "create"
                }
            ]
  GiftCertificates:
    description: Document representing an unfiltered list of gift certificates.
    properties:
      offset: ApiStandards.Offset
      data:
        description: The collection of gift certificates.
        type: array
        items:
          type: GiftCertificate
        required: false
        example: !include Examples/gift-certificates-data-example.raml
      limit: ApiStandards.Limit
      total:
        description: The total number of documents.
        type: integer
        format: int32
        required: false
        example: 25
  GiftCertificateSearchResult:
    description: Document representing a gift certificate search result.
    type: CommerceCloudStandards.PaginatedSearchResult
    properties:
      hits:
        type: GiftCertificate[]
  Money:
    properties:
      currencyMnemonic:
        description: The mnemonic for the money.
        type: string
        example: $
      value:
        description: The value for the money.
        type: number
        format: double
        example: 100

/organizations/{organizationId}/gift-certificates:
  type: CommerceCloudStandards.Organization
  is:
    - CommerceCloudStandards.SiteSpecific
  put:
    description: |-
      Creates a gift certificate using the information provided. If a gift certificate with 
       the same unique identifier is generated, it is deleted and a new one is created.
    displayName: createGiftCertificate
    is:
      - GiftCertificateTraits.GiftCertificateNotFound
      - GiftCertificateTraits.InvalidGiftCertificateStatus
      - GiftCertificateTraits.InvalidGiftCertificateException
      - GiftCertificateTraits.GiftCertificateAmountOutOfRangeException
      - GiftCertificateTraits.GiftCertificateCreateMerchantIdNotUniqueException
      - ApiStandards.RateLimited:
            responseStatus: 200
      - ApiStandards.RateLimited:      
            responseStatus: 400
      - ApiStandards.RateLimited:      
            responseStatus: 404
    responses:
      '200':
        description: Successfully created gift certificate.
        body:
          application/json:
            type: GiftCertificate
            example:
              gift_certificate: !include Examples/gift-certificate-create-success-example.raml
      '400':
        description: If the gift certificate passed in is not valid (the argument indicates the field that was invalid), the amount specified is out of range, the merchant ID is not unique, the recipient email address is invalid, or the gift certificate status specified is invalid.
    body:
      application/json:
        type: GiftCertificate
        example:
              GiftCertificate: !include Examples/gift-certificate-create-example.raml
    securedBy:
      - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.gift-certificates.rw ] }
      - CommerceCloudStandards.AmOAuth2
  post:
    description: |-
        Searches for gift certificates. The query attribute specifies a complex query that can be used to narrow down the search. These are the list of searchable attributes:
         
        | Attribute | Type | Sortable |
        |-----------|--------|----------|
        | merchantId | String | yes |
        | maskedGiftCertificateCode * | String | no |
        | orderNo | String | yes |
        | senderName | String | yes |
        | recipientName | String | yes |
        | recipientEmail | String | yes |
        | status | String | yes |
        | enabled | Boolean | yes |
        | message | String | yes |
        | description | String | yes |
        | creationDate | Date | yes |
        | currencyMnemonic ** | String | yes |
         
        ## Notes:
          * *`maskedGiftCertificateCode`, also known as just code, can only be used in a term query.  If a
         four-character code is supplied, it is assumed that the search is on the unmasked portion of the code, otherwise
         the full code must be matched.  Text queries are not allowed.
          * **`currencyMnemonic` can only be joined with other attributes using a conjunction (`AND`).
          * Only searchable attributes can be used in sorting.
    displayName: giftCertificatesSearch
    is:
        - GiftCertificateTraits.MalformedQuery
        - GiftCertificateTraits.UnqueryableField
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
    responses:
      '200':
        description: Returns Gift Certificates.
        body:
          application/json:
            type: GiftCertificateSearchResult
            examples:
              giftCertificates: !include Examples/get-results-example.raml
      '400':
        description: Thrown if the query is ill-formed.
    body:
      application/json:
        type: CommerceCloudStandards.SearchRequest
    securedBy:
         - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.gift-certificates, sfcc.gift-certificates.rw ] }
         - CommerceCloudStandards.AmOAuth2
/organizations/{organizationId}/gift-certificates/{merchantId}:
  type: CommerceCloudStandards.Organization
  is: 
    - CommerceCloudStandards.SiteSpecific
  uriParameters:
    merchantId:
      description: The merchant ID of the requested gift certificate.
      minLength: 1
      type: string
  delete:
      description: Deletes the gift certificate by merchant ID.
      displayName: deleteGiftCertificate
      is:
        - ApiStandards.RateLimited:
            responseStatus: 204
      responses:
        '204':
          description: Successfully deleted gift certificate.
          body:
            application/json:
              type: GiftCertificate
      securedBy:
        - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.gift-certificates.rw ] }
        - CommerceCloudStandards.AmOAuth2
  get:
      description: Action to get gift certificate information using merchant ID.
      displayName: getGiftCertificate
      is:
        - GiftCertificateTraits.GiftCertificateNotFound
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 404
      responses:
        '200':
          description: Successfully retrieved gift certificate for given merchant ID.
          body:
            application/json:
              type: GiftCertificate
              examples:
                giftCertificate: !include Examples/get-result-example.raml
        '404':
          description: Thrown in case the gift certificate does not exist matching the given merchant ID.
      securedBy:
        - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.gift-certificates, sfcc.gift-certificates.rw ] }
        - CommerceCloudStandards.AmOAuth2
  patch:
      description: Updates the gift certificate with the specified information using merchant ID.
      displayName: updateGiftCertificate
      is:
        - GiftCertificateTraits.GiftCertificateNotFound
        - GiftCertificateTraits.InvalidGiftCertificateStatus
        - GiftCertificateTraits.InvalidRecipientEmail
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
        - ApiStandards.RateLimited:    
            responseStatus: 404
      responses:
        '200':
          description: Successfully updated gift certificate.
          body:
            application/json:
              type: GiftCertificate
              example:
                gift_certificate: !include Examples/gift-certificate-update-success-example.raml
        '400':
          description: If recipient email address or gift certificate status specified is invalid.
        '404':
          description: Thrown in case the gift certificate does not exist matching the given merchant ID.
      body:
        application/json:
          type: GiftCertificate
          example:
            patchGiftCertificate: !include Examples/gift-certificate-update-example.raml
      securedBy:
         - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.gift-certificates.rw ] }
         - CommerceCloudStandards.AmOAuth2