#%RAML 1.0 NamedExample
value:
  {
  "title": "Store Not Found",
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/store-not-found",
  "detail": "No store with ID 'abc' for site 'SiteGenesis' could be found.",
  "siteId": "SiteGenesis",
  "storeId": "abc"
 }