#%RAML 1.0 NamedExample
value:
  {
    "title": "Missing Postal Code",
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/missing-postal-code",
    "detail": "The input parameter 'postal_code' is required when no coordinates are provided."
  }