#%RAML 1.0 DocumentationItem
title: baseUri Standards
content: |
  The baseUri has been standardized as the following. You should use the below snippet in your RAML definitions:
          
      baseUri: https://{shortCode}.api.commercecloud.salesforce.com/<bounded-context>/<root-aggregate>/{version}
      baseUriParameters:
        shortCode:
          description: A region-specific merchant identifier.
          example: fd4gt8

  Of note:
    - the baseUri is an absolute URL
    - the only baseUriParameter is `shortCode`. `version` is special and will use the version of the API. 
    - the bounded-context and root-aggregate should be replaced with your API's bounded-context and root-aggregate, in kebab case, pluralized, and not be variablized.
