#%RAML 1.0 NamedExample
value:
  {
    "type": "about:blank",
    "errorCode": "MissingParameter",
    "message": "The field 'quantity' is missing from the request body."
    #"headers": 
    #  "X-RateLimit-Limit": The maximum number of requests permitted per window.
    #  "X-RateLimit-Remaining": The number of requests remaining in the current rate limit window.
    #  "X-RateLimit-Reset": The time at which the current rate limit window resets in UTC epoch seconds.
  }