#%RAML 1.0 DataType

#type: !include ../..//exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/inventory-availability-standards/1.0.14/types/ATO.raml

description: The amount available to order at the location
example: 1147.90
type: number
format: double
minimum: 0.000
multipleOf: 0.001
