#%RAML 1.0 DataType

#type: !include ../../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/inventory-availability-standards/1.0.14/types/Date.raml

example: 2019-07-24T21:13:00Z
type: datetime
format: rfc3339