#%RAML 1.0 DataType

#type: !include ../../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/inventory-availability-standards/1.0.14/types/GenericProcessStats.raml

properties:
  startTimeUTC: 
    description: The UTC time that the export process was started.
    type: !include Date.raml
    example: 2019-02-12T12:34:00Z
  endTimeUTC: 
    description: The UTC time that the export process completed.
    type: !include Date.raml
    example: 2019-02-12T12:52:00Z
  recordsProcessedCount: 
    description: The total number of records processed during the export request.
    type: number
    example: 2000
  recordsExportedCount: 
    description: The total number of records exported by the system.
    type: number
    example: 2000