#%RAML 1.0 Trait
description: This trait represents API behavior for a 409 response when an cancelled order can't be reopened.

uses:
  DataTypes: ../data-types.raml
  
responses:
  409:
    description: |
            The cancelled order can't be reopened.
    body:
      application/problem+json:
        type: DataTypes.ErrorResponse
        example: |
          {
            "title": "Undo Canel Order",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/undo-cancel-order",
            "detail": "The cancelled order with number '00001547' cannot be reopened."
          }