#%RAML 1.0 DataType

#UnreserveDetailGroupOnly
properties:

  id: 
    type: !include ../GlobalTypes/IdempotenceId.raml
  externalRefId:
    type: !include ../GlobalTypes/ExternalRefId.raml
  group:
    type: !include ../GlobalTypes/GroupId.raml
  sku:
    type: !include ../GlobalTypes/SkuId.raml
  quantity:
    type: number
    example: 0