#%RAML 1.0 DataType

#UnreserveDetailGroupAndLocation
properties:

  id: 
    type: !include ../GlobalTypes/IdempotenceId.raml
  externalRefId:
    type: !include ../GlobalTypes/ExternalRefId.raml
  location:
    type: !include ../GlobalTypes/LocationId.raml
    required: false
  group:
    type: !include ../GlobalTypes/GroupId.raml
    required: false
  sku:
    type: !include ../GlobalTypes/SkuId.raml
  quantity:
    type: number
    example: 0