#%RAML 1.0 Trait
description: This trait represents API behavior for a 204 response when a operation was successful and no content is returned.

uses:
  DataTypes: ../data-types.raml
  
responses:
  204:
    description: |
            The operation was successful, no content is returned.