#%RAML 1.0
#In C4E review
title: Orders
description: Provides access to Commerce Cloud Digital order related functionality.
version: v1
protocols: HTTPS
mediaType: application/json
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/checkout/orders/{version}
baseUriParameters:
  shortCode:
    description: Region-specific merchant identifier.
    example: fd4gt8

uses:
  StatusCodes: status-codes.raml
  DataTypes: data-types.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.15/commerce-cloud-standards.raml 
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.8/api-standards.raml

types:
'/organizations/{organizationId}':
  type: CommerceCloudStandards.Organization
  '/orders/{orderNo}':
    type: CommerceCloudStandards.Organization
    uriParameters:
      orderNo:
        description: The order number.
        minLength: 1
        type: string
        example: "00000410"
    patch:
      description: Updates the order.
      displayName: updateOrder
      is:
        - StatusCodes.Success
        - StatusCodes.BadRequest
        - StatusCodes.OrderNotFound
        - StatusCodes.SiteNotFound
        - CommerceCloudStandards.SiteSpecific
        - ApiStandards.RateLimited3:
            responseStatus: 204
            responseStatus2: 400
            responseStatus3: 404
      body:
          type: DataTypes.OrderUpdateRequest
          examples:
              DataTypes.OrderUpdateRequest: !include examples/order-request.raml
      securedBy:
        - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
        - CommerceCloudStandards.AmOAuth2
    /confirmation-status:
      type: CommerceCloudStandards.Organization
      put:
        description: Updates the order confirmation status.
        displayName: updateOrderConfirmationStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
        body:
            type: DataTypes.OrderConfirmationStatusUpdateRequest
            examples:
              DataTypes.OrderConfirmationStatusUpdateRequest: !include examples/order-confirmation-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    /export-status:
      type: CommerceCloudStandards.Organization
      put:
        description: |-
          Updates the order export status. Setting the status to EXPORTED will also trigger the finalization of on-order inventory transactions for this order, meaning that all inventory transactions with type on-order are moved into final inventory transactions. This is only relevant when on-order inventory is turned on for the inventory list ordered products are in.
        displayName: updateOrderExportStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404      
        body:
            type: DataTypes.OrderExportStatusUpdateRequest
            examples:
              DataTypes.OrderExportStatusUpdateRequest: !include examples/order-export-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    /external-status:
      type: CommerceCloudStandards.Organization
      put:
        description: Updates the order external status.
        displayName: updateOrderExternalStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
        body:
            type: DataTypes.OrderExternalStatusUpdateRequest
            examples:
              DataTypes.OrderExternalStatusUpdateRequest: !include examples/order-external-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    /payment-status:
      type: CommerceCloudStandards.Organization
      put:
        description: Updates the order payment status.
        displayName: updateOrderPaymentStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
        body:
            type: DataTypes.OrderPaymentStatusUpdateRequest
            examples:
              DataTypes.OrderPaymentStatusUpdateRequest: !include examples/order-payment-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    /shipping-status:
      type: CommerceCloudStandards.Organization
      put:
        description: Updates the order shipping status.
        displayName: updateOrderShippingStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
        body:
            type: DataTypes.OrderShippingStatusUpdateRequest
            examples:
              DataTypes.OrderShippingStatusUpdateRequest: !include examples/order-shipping-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    /status:
      type: CommerceCloudStandards.Organization
      put:
        description: |-
          Updates the order status. Orders which are in status NEW, COMPLETED, or CANCELLED can not be set to status CREATED or FAILED.
        displayName: updateOrderStatus
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - StatusCodes.StatusTransitionConflict
          - StatusCodes.CancelOrderConflict
          - StatusCodes.PlaceOrderConflict
          - StatusCodes.UndoCancelOrderConflict
          - StatusCodes.UndoFailOrderConflict
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited4:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
              responseStatus4: 409
        body:
            type: DataTypes.OrderStatusUpdateRequest
            examples:
              DataTypes.OrderStatusUpdateRequest: !include examples/order-status-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
    '/payment-instruments/{paymentInstrumentId}':
      type: CommerceCloudStandards.Organization
      uriParameters:
        paymentInstrumentId:
          description: ID of the payment instrument.
          minLength: 1
          type: string
          example: b7679bea661819b2de78b9de7d
      patch:
        description: Updates the payment instrument of an order.
        displayName: updateOrderPaymentInstrument
        is:
          - StatusCodes.Success
          - StatusCodes.BadRequest
          - StatusCodes.OrderNotFound
          - StatusCodes.SiteNotFound
          - StatusCodes.PaymentInstrumentNotFound
          - CommerceCloudStandards.SiteSpecific
          - ApiStandards.RateLimited3:
              responseStatus: 204
              responseStatus2: 400
              responseStatus3: 404
        body:
            type: DataTypes.PaymentInstrumentUpdateRequest
            examples:
              DataTypes.PaymentInstrumentUpdateRequest: !include examples/order-payment-instrument-request.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
          - CommerceCloudStandards.AmOAuth2
      /transaction:
        type: CommerceCloudStandards.Organization
        patch:
          description: Updates the transaction of an order payment instrument.
          displayName: updateOrderPaymentTransaction
          is:
            - StatusCodes.Success
            - StatusCodes.BadRequest
            - StatusCodes.OrderNotFound
            - StatusCodes.SiteNotFound
            - StatusCodes.PaymentInstrumentNotFound
            - CommerceCloudStandards.SiteSpecific
            - ApiStandards.RateLimited3:
                responseStatus: 204
                responseStatus2: 400
                responseStatus3: 404
          body:
              type: DataTypes.PaymentTransactionUpdateRequest
              examples:
                DataTypes.PaymentTransactionUpdateRequest: !include examples/order-payment-transaction-request.raml
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
            - CommerceCloudStandards.AmOAuth2
    '/shipments/{shipmentId}':
      type: CommerceCloudStandards.Organization
      uriParameters:
        shipmentId:
          description: ID of the shipment.
          minLength: 1
          type: string
          example: me
      /shipping-address:
        type: CommerceCloudStandards.Organization
        put:
          description: Updates (create or replace) the order shipment address.
          displayName: updateOrderShippingAddress
          is:
            - StatusCodes.Success
            - StatusCodes.BadRequest
            - StatusCodes.OrderNotFound
            - StatusCodes.SiteNotFound
            - StatusCodes.ShipmentNotFound
            - CommerceCloudStandards.SiteSpecific
            - ApiStandards.RateLimited3:
                responseStatus: 204
                responseStatus2: 400
                responseStatus3: 404
          body:
              type: DataTypes.ShippingAddressUpdateRequest
              examples:
                DataTypes.ShippingAddressUpdateRequest: !include examples/order-shipping-address-request.raml
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ "sfcc.orders.rw" ] }
            - CommerceCloudStandards.AmOAuth2
