#%RAML 1.0 DataType

#type: !include ../../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/inventory-availability-standards/1.0.16/types/ErrorCode.raml

properties:
  errorCode: string
  message: string
  title: 
    type: string
    required: false
  detail: 
    type: string
    required: false
  instance: 
    type: string
    required: false
  type:
    type: string
    required: false