#%RAML 1.0 DataType

#type: !include ../../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/inventory-availability-standards/1.0.16/types/IdempotenceId.raml

description: A unique identifier, used in combination with the SKU, so that future requests with the same combination have the same result.
example: 82251928-8863-488e-840b-2aebd10b57ba
type: string