#%RAML 1.0 NamedExample
value:
  {
    "limit": 1,
    "hits": [
        {
            "data": {
                "customerNo": "00004501",
                "lastName": "richi"
            },
            "relevance": 4.075775146484375
        }
    ],
    "query": {
        "textQuery": {
            "fields": [
                "credentials.login"
            ],
            "searchPhrase": "GwennyStrah3661"
        }
    },
    "offset": 0,
    "total": 1
  }