#%RAML 1.0 Library

types:

  AttributeName:
        description: A human-readable name for the attribute of a given locale, optionally defined when the attribute is created.
        type: string
        example: Brand
  Path:
    description: The attribute’s path, expressed in dot notation.
    type: string
    example: item.brand

  Value:
    description: The data for the attribute.
    type: any
