#%RAML 1.0 DataType

uses:
  IDs: identifiers.raml
  AttributeInfo : attribute-info.raml

description: An entity containing an attribute ID, the attribute's path, and the attribute's value for a corresponding item.
properties:
  attributeId: IDs.AttributeId
  attributeName?: AttributeInfo.AttributeName
  path: AttributeInfo.Path
  value: AttributeInfo.Value