#%RAML 1.0 Library

uses:
  IDs: identifiers.raml

types:

  GroupValue:
    description: An entity containing attribute values for a group of items.
    properties:
      itemId: IDs.ItemId
      value:
        description: The data for the given attribute.
        type: any

  GroupAttribute:
    description: An entity represeting an attribute's values aggregated over a group of items within Discovery. This entity contains an attribute ID, the attribute's path, and the attribute's values for a corresponding collection of items.
    properties:
      attributeId: IDs.AttributeId
      attributeName?:
        description: A human readable name of the attribute for a given locale, optionally defined at creation time of the attribute.
        type: string
        example: Brand
      path:
        description: The path, using dot notation, that this attribute corresponds to.
        type: string
        example: item.brand
      values: GroupValue[]