#%RAML 1.0 NamedExample
value:
  {
    "adjustedMerchandizeTotalTax": 4.95,
    "adjustedShippingTotalTax": 1.3,
    "billingAddress": {
      "address1": "45 Main Rd.",
      "city": "Burlington",
      "countryCode": "US",
      "firstName": "Max",
      "fullName": "Max Mustermann",
      "lastName": "Mustermann",
      "phone": "6175555555",
      "postalCode": "05408",
      "stateCode": "MA"
    },
    "confirmationStatus": "confirmed",
    "createdBy": "storefront",
    "creationDate": "2015-05-19T15:23:18.000Z",
    "currency": "USD",
    "customerInfo": {
      "customerId": "cdrjZ5iQeOQjpqKldaSzbvg2E8",
      "customerName": "Max Mustermann",
      "customerNo": "0002352",
      "email": "no-reply@salesforce.com",
      "guest": true
    },
    "customerLocale": "en_US",
    "exportStatus": "not_exported",
    "invoiceNo": "00000001",
    "lastModified": "2020-11-05T13:08:05.588Z",
    "merchandizeTotalTax": 4.95,
    "orderNo": "00000410",
    "orderTotal": 110.24,
    "paymentInstruments": [
      {
        "paymentCard": {
          "cardType": "Visa",
          "creditCardExpired": true,
          "expirationMonth": 1,
          "expirationYear": 2020,
          "holder": "Max Mustermann",
          "maskedNumber": "***************1111",
          "numberLastDigits": "1111",
          "validFromMonth": 1,
          "validFromYear": 2018
        },
        "paymentInstrumentId": "2c36f04e453a2512fba74ae1ea",
        "paymentMethodId": "CREDIT_CARD",
        "paymentTransaction" : {
            "amount": 110.24,
            "transactionId": "40f07907428e23c4bbc6fb0446",
            "c_authResult" : "AUTHORIZED"
          },
        "c_issuerBank" : "JPMORGAN CHASE BANK, N.A."
      }
    ],
    "paymentStatus": "not_paid",
    "placeDate": "2015-05-19T15:23:18.000Z",
    "productItems": [
      {
        "adjustedTax": 4.95,
        "basePrice": 99,
        "bonusProductLineItem": false,
        "gift": false,
        "grossPrice": 103.95,
        "itemId": "3390171e44271bad9c36592049",
        "itemText": "Flat Front Pant",
        "netPrice": 99,
        "position": 1,
        "priceAfterItemDiscount": 99,
        "priceAfterOrderDiscount": 99,
        "productId": "701643632930",
        "productName": "Flat Front Pant",
        "quantity": 1,
        "shipmentId": "me",
        "shippingItemId": "a46294cffd6945a511cb6fce05",
        "tax": 4.95,
        "taxBasis": 99,
        "taxRate": 0.05
      }
    ],
    "productSubTotal": 99,
    "productTotal": 99,
    "remoteHost": "127.0.0.1",
    "shipments": [
      {
        "adjustedMerchandizeTotalTax": 4.95,
        "adjustedShippingTotalTax": 1.3,
        "gift": false,
        "merchandizeTotalTax": 99,
        "productSubTotal": 99,
        "productTotal": 99,
        "shipmentId": "me",
        "shipmentNo": "00000001",
        "shipmentTotal": 110.24,
        "shippingAddress": {
          "address1": "45 Main Rd.",
          "city": "Burlington",
          "countryCode": "US",
          "firstName": "Max",
          "fullName": "Max Mustermann",
          "lastName": "Mustermann",
          "phone": "6175555555",
          "postalCode": "05408",
          "stateCode": "MA"
        },
        "shippingMethod": {
          "id": "DefaultShippingMethod"
        },
        "shippingStatus": "not_shipped",
        "shippingTotal": 25.99,
        "shippingTotalTax": 1.3,
        "taxTotal": 5.25
      }
    ],
    "shippingItems": [
      {
        "adjustedTax": 0.3,
        "basePrice": 5.99,
        "grossPrice": 6.29,
        "itemId": "4c3d46056d49226904ee61946c",
        "itemText": "Shipping",
        "netPrice": 5.99,
        "priceAfterItemDiscount": 5.99,
        "shipmentId": "me",
        "tax": 0.3,
        "taxBasis": 5.99,
        "taxRate": 0.05,
        "type": "fixed_price"
      },
      {
        "adjustedTax": 1,
        "basePrice": 10,
        "grossPrice": 21,
        "itemId": "a46294cffd6945a511cb6fce05",
        "itemText": "Item Shipping Cost (Surcharge)",
        "netPrice": 20,
        "priceAfterItemDiscount": 20,
        "shipmentId": "me",
        "tax": 1,
        "taxBasis": 20,
        "taxRate": 0.05,
        "type": "surcharge"
      }
    ],
    "shippingStatus": "not_shipped",
    "shippingTotal": 25.99,
    "shippingTotalTax": 1.3,
    "siteId": "ShoppingSite",
    "status": "new",
    "taxation": "net",
    "taxTotal": 5.25
  }