#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Data Gift Certificate API.
responses:
  404:
    description:
      Thrown in case the gift certificate does not exist matching the given merchant ID.
    body:
      application/json:
        type: Standards.ErrorResponse
        example:
          {
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/not-found",
            "title": "Gift Certificate Not Found Exception",
            "detail": "No gift certificate with merchant ID 'my-merchant_id' for site 'TestWapi' was found."
          }