#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in Data Gift Certificate Search API.
responses:
  400:
    description:
      Thrown if the query is ill-formed.
    body:
      application/json:
        type: Standards.ErrorResponse
        example:
          {
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/malformed-search-parameter",
            "title": "Malformed Search Parameter Exception",
            "detail": "An error occurred while decoding the request, the body was 'malformed'."
          }
