#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response in Data Gift Certificate Search API.
responses:
  400:
    description:
      Thrown if given query field is unqueryable.
    body:
      application/json:
        type: Standards.ErrorResponse
        example:
          {
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unqueryable-field",
            "title": "Unqueryable Field Exception",
            "detail": "Given field cannot be queried. For example - The field 'link' is unqueryable."
          }
