#%RAML 1.0 Trait
description: Thrown if the request is malformed, incomplete or otherwise erroneous.
responses:
  '400':
    description: Thrown if a value constraint for query parameters is violated. Also thrown unless either a combination of latitude and longitude or a combination of country code and postal code is provided, or if an invalid distance_unit is given.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/missing-postal-code",
            "title": "Missing Postal Code",
            "detail": "The input parameter 'postalCode' is required when no coordinates are provided."
          }

