#%RAML 1.0 NamedExample
value:
  {
    "errorCode": "InvalidRequestParameter",
    "message": "Reservation ID provided does not exist",
    "parameterName": "reservationId",
    "type": "about:blank"
  }