#%RAML 1.0 NamedExample
value:
  {
    "errorCode": "InvalidRequestParameter",
    "message": "All or nothing transfers are only allowed from Group to Location transfer types. Invalid transfer type for request",
    "type": "about:blank"
  }