#%RAML 1.0 NamedExample
value:
  {
    "errorCode": "InvalidRequestParameter",
    "message": "User provided locationId AND groupId.  You can only provide one or the other, not both in a single record.",
    "type": "about:blank"
  }