#%RAML 1.0 NamedExample
value:
  {
    "errorCode": "InvalidRequestParameter",
    "message": "Not one of the values accepted for Enum class",
    "parameterName": "status",
    "type": "about:blank"
  }