#%RAML 1.0 Trait

# Response for unauthorized API request access.

uses: 
  ErrorTypes: /libraries/ErrorHandling/ErrorResponses.raml
  
responses: 
  403:
    description: Organization not authorized
    body:
      application/json:
        type: ErrorTypes.403Error
        example: !include /Examples/HttpErrors/403ErrorExample.raml