#%RAML 1.0 NamedExample

value:
  {
    "data":
      [
        {
        "mtlsCertificateId": "465a48f6-3d98-4c15-9312-211984ee8629",
        "expiresOn": "2022-01-12T04:15:57Z",
        "issuer": "DigiCert",
        "signature": "SHA256WithRSA",
        "uploadedOn": "2020-01-12T04:15:57Z",
        "ca": true,
        "serialNumber": "432217133297895665180570788458463042229861757760",
        "mtlsCertificateName": "mtls_cert_name",
        "mtlsAssociatedHostname": "mtls.cert.salesforce.com"
      },
      {
        "mtlsCertificateId": "465a48f6-3d98-4c15-9312-211984ee8630",
        "expiresOn": "2022-01-12T04:15:57Z",
        "issuer": "DigiCert",
        "signature": "SHA256WithRSA",
        "uploadedOn": "2020-01-12T04:15:57Z",
        "ca": true,
        "serialNumber": "432217133297895665180570788458463042229861757761",
        "mtlsCertificateName": "mtls_cert_name",
        "mtlsAssociatedHostname": "mtls.cert.salesforce.com"
      }
    ]
  }