#%RAML 1.0 Trait
description: Thrown if the request is malformed, incomplete or otherwise erroneous.
responses:
  '400':
    description: The locale is invalid. Confirm that you passed in a locale in the valid format of ISO 639-1 for the language code and ISO 3166-1 for the country code. For example, en-US.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "title": "Unknown Locale",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unknown-locale",
            "detail": "The locale 'ab-CD' is unknown.",
            "locale": "ab-CD"
          }