#%RAML 1.0 DataType

description: Record definition used in a batch inventory update request

properties:
  externalRefId:
    required: false
    type: !include ../ExternalRefId.raml
  futureStock:
    required: false
    type: array
    items:
      type: !include ../Future.raml
  location:
    type: !include ../LocationId.raml
  onHand:
    required: false
    type: !include ../QOH.raml
  safetyStockCount:
    required: false
    type: !include ../SafetyStock.raml
  sku:
    type: !include ../SkuId.raml
  id:
    type: !include ../IdempotenceId.raml
  effectiveDate:
    required: false
    type: !include ../EffectiveDateGeneric.raml