#%RAML 1.0 DataType

description: Detail information for errors generated during a batch inventory update.
properties:
  externalRefId:
    required: false
    type: !include ../ExternalRefId.raml
  locationId:
    type: !include ../LocationId.raml
  sku:
    type: !include ../SkuId.raml
  id:
    type: !include ../IdempotenceId.raml