#%RAML 1.0 DataType
uses:
  ErrorEnum: ../../libraries/ExceptionResponses/ErrorCodeTypesEnum.raml

description: Error record information generated during a batch inventory update.
properties:
  details:
    type: !include BatchInventoryUpdateErrorDetail.raml
  message: 
    type: string
    example: Inventory record update failed
  errorCode:
    type: ErrorEnum.ErrorCodeTypesEnum
    example: InventoryReset