openapi: 3.0.3
info:
  title: Preferences
  version: v1
  description: "# API Overview\nAvailable with B2C Commerce version 24.7.2, B2C Commerce teams must regularly configure site and environment-specific settings to support changing business needs and technical integrations. In many instances, Storefront Reference Architecture (SFRA)/SiteGenesis implementations rely on declarative Custom Site Preferences to alter these settings without the need for deployment or significant engineering support. Site preferences allow teams to adapt their sites with minimal effort.\n\nThe following Preferences API endpoints retrieve preference-related information:\n\n- Global custom preferences: \nRetrieves all custom preferences at the organization level. \n\n- Site custom prefererences: \nRetrieves all custom preferences at the site level.\n\nThe Preferences API first checks to see if custom values have been set, and if so, returns the custom settings. Otherwise, the Preferences API returns the default values provided in Business Manager.\n\nNote: The Preferences API sets custom preferences. For details on working with non-custom preferences, see [Global Preferences for B2C Commerce](https://help.salesforce.com/s/articleView?id=cc.b2c_global_preferences.htm&type=5) and [Site Preferences in B2C Commerce](https://help.salesforce.com/s/articleView?id=cc.b2c_site_preferences.htm&type=5).\n\n## Authentication & Authorization\nThe custom preference API requires a Account Manager token from the [Admin APIs.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-admin-apis.html)\n\nYou must include the relevant scope(s) in the client ID used to generate the SLAS token. For details, see [Authorization Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html)\n\n## Use Cases\n### Global Custom Preference:\nA prominent private equity firm manages a diverse portfolio of brands, each operating its own site. Despite the individuality of these brands, they leverage shared third-party integrations for critical functionalities, such as payments and content management. Through a centralized approach, the firm establishes specifications for key components like the payments portal, ensuring consistency and efficiency across all sites. These specifications are meticulously crafted and undergo infrequent modifications to accommodate evolving needs while maintaining operational stability.\n\n### Site Custom Preference:  \nSite operators might have numerous tests or features tailored to their specific site. To facilitate streamlined control over these functionalities, they need a user-friendly mechanism for their merchant team to effortlessly toggle them on or off as needed. The site Preference API provides this mechanism.\n\n### Caching\nCaching capabilities are available for the Preferences APIs. For details, see [Server-Side Web-Tier Caching.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/server-side-web-tier-caching.html)\n\n## Preferences\n[Global preferences](https://help.salesforce.com/s/articleView?id=cc.b2c_global_preferences.htm&type=5)\n\n[Site preferences](https://help.salesforce.com/s/articleView?id=cc.b2c_site_preferences.htm&type=5)"
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/configuration/preferences/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/global-custom-preferences:
    get:
      summary: Retrieves the Global Custom Preferences.
      operationId: getGlobalCustomPreferenceList
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/maskPassword'
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 200
            maximum: 200
          description: Maximum records to retrieve per request, not to exceed 200. Defaults to 200.
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
            default: 0
            minimum: 0
          description: Used to retrieve the results based on a particular resource offset.
      responses:
        '200':
          description: Retrieved Global Custom Preferences successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomPreferenceList'
              examples:
                GlobalCustomPreferenceExample:
                  $ref: '#/components/examples/GlobalCustomPreferenceExample'
        '400':
          description: Thrown if the query is ill-formed.
        '401':
          description: |
            Unauthorized. Your Client ID is invalid, or you are not allowed to access
            the content provided by the requested URL.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InvalidAccessToken:
                  $ref: '#/components/examples/InvalidAccessToken'
      security:
        - AmOAuth2:
            - sfcc.preferences
  /organizations/{organizationId}/site-custom-preferences:
    get:
      summary: Retrieves the Custom Preferences for a specified siteId.
      operationId: getSiteCustomPreferenceList
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/maskPassword'
        - $ref: '#/components/parameters/siteId'
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 200
            maximum: 200
          description: Maximum records to retrieve per request, not to exceed 200. Defaults to 200.
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
            default: 0
            minimum: 0
          description: Used to retrieve the results based on a particular resource offset.
      responses:
        '200':
          description: Retrieved Site Custom Preferences successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomPreferenceList'
              examples:
                SiteCustomPreferenceExample:
                  $ref: '#/components/examples/SiteCustomPreferenceExample'
        '400':
          description: Thrown if the query is ill-formed.
        '401':
          description: |
            Unauthorized. Your Client ID is invalid, or you are not allowed to access
            the content provided by the requested URL.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InvalidAccessToken:
                  $ref: '#/components/examples/InvalidAccessToken'
      security:
        - AmOAuth2:
            - sfcc.preferences
components:
  securitySchemes:
    AmOAuth2:
      type: oauth2
      description: AccountManager OAuth 2.0 bearer token Authentication.
      flows:
        clientCredentials:
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            sfcc.preferences: Preferences scope
        authorizationCode:
          authorizationUrl: https://account.demandware.com/dwsso/oauth2/authorize
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            sfcc.preferences: Preferences scope
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    Limit:
      default: 10
      minimum: 1
      format: int32
      description: Maximum records to retrieve per request, not to exceed the maximum defined. A limit must be at least 1 so at least one record is returned (if any match the criteria).
      type: integer
      example: 10
    Total:
      default: 0
      minimum: 0
      format: int64
      description: The total number of hits that match the search's criteria. This can be greater than the number of results returned as search results are pagenated.
      type: integer
      example: 10
    ResultBase:
      description: "Schema defining generic list result. Each response schema of a resource requiring a list response should extend this schema. \nAdditionally it needs to be defined what data is returned."
      type: object
      required:
        - limit
        - total
      properties:
        limit:
          maximum: 200
          allOf:
            - $ref: '#/components/schemas/Limit'
        total:
          $ref: '#/components/schemas/Total'
    Offset:
      default: 0
      minimum: 0
      format: int64
      description: The zero-based index of the first hit/data to include in the result.
      type: integer
      example: 0
    PaginatedResultBase:
      description: "Schema defining generic pageable result. Each response schema of a resource requiring pagination should extend this schema. \nIf you use this extend this schema directly, it needs to be defined what data is returned. Allowed names for the data field is `data`."
      type: object
      allOf:
        - $ref: '#/components/schemas/ResultBase'
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      required:
        - limit
        - offset
        - total
    CustomPreference:
      description: Preference object
      properties:
        groupId:
          description: The ID of the preference group.
          type: string
        id:
          description: The Preference Id.
          type: string
        value:
          description: The value for the Preference Id.
      required:
        - groupId
        - id
        - value
      type: object
    CustomPreferenceList:
      description: Document representing a Custom Preference result.
      allOf:
        - $ref: '#/components/schemas/PaginatedResultBase'
      properties:
        data:
          description: The list of custom preferences in the search result.
          type: array
          items:
            $ref: '#/components/schemas/CustomPreference'
      required:
        - limit
        - data
        - offset
        - total
      type: object
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    maskPassword:
      name: maskPassword
      in: query
      description: Whether to mask password or not.
      required: false
      schema:
        type: boolean
        default: false
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
  examples:
    GlobalCustomPreferenceExample:
      value:
        limit: 10
        data:
          - groupId: PreferenceGroup1
            id: booleanValue
            value: true
          - groupId: PreferenceGroup1
            id: htmlValue
            value:
              markup: <h1>HTML Value</h1>
              source: <h1>HTML Value</h1>
          - groupId: PreferenceGroup1
            id: dateValue
            value: '2007-06-20T00:00:00.000Z'
          - groupId: PreferenceGroup2
            id: integerValueValue
            value: 12345
          - groupId: PreferenceGroup2
            id: stringValueList
            value: s1
          - groupId: PreferenceGroup2
            id: imageValue
            value:
              abs_url: https://localhost/on/demandware.static/-/Sites/default/v2d48bd5c705782218c66e02f6776751b2e227ac5/img/value.jpg
              dis_base_url: https://image.demandware.com/dw/image/v2/zzzz_s02/on/demandware.static/-/Sites/default/v2d48bd5c705782218c66e02f6776751b2e227ac5/img/value.jpg
              path: /img/value.jpg
        offset: 0
        total: 100
    InvalidAccessToken:
      value:
        title: Invalid Access Token
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-access-token
        detail: The request is unauthorized, the access token is invalid.
        accessToken: hbGciOiJIUzI1NiIsInR5cCI6Ikp
    SiteCustomPreferenceExample:
      value:
        limit: 10
        data:
          - groupId: PreferenceGroup1
            id: booleanValue
            value: true
          - groupId: PreferenceGroup1
            id: htmlValue
            value:
              markup: <h1>HTML Value</h1>
              source: <h1>HTML Value</h1>
          - groupId: PreferenceGroup2
            id: integerValueValue
            value: 12345
          - groupId: PreferenceGroup2
            id: imageValue
            value:
              abs_url: https://localhost/on/demandware.static/-/Sites/default/v2d48bd5c705782218c66e02f6776751b2e227ac5/img/value.jpg
              dis_base_url: https://image.demandware.com/dw/image/v2/zzzz_s02/on/demandware.static/-/Sites/default/v2d48bd5c705782218c66e02f6776751b2e227ac5/img/value.jpg
              path: /img/value.jpg
        offset: 0
        total: 100
