#%RAML 1.0 NamedExample
value:
  {
      "assignedCategories": [
        {
            "catalogId": "apparel-catalog",
            "categoryId": "mens-accessories"
        },
        {
            "catalogId": "storefront-catalog-en",
            "categoryId": "top-seller"
        },
        {
            "catalogId": "storefront-catalog-en",
            "categoryId": "electronics-gaming"
        }
      ],
      "brand": "Apple",
      "classificationCategory": {
          "catalogId": "storefront-catalog-en",
          "categoryId": "top-seller"
      },      
      "creationDate": "2019-02-21T22:10:02.000Z",
      "id": "apple-ipod-classic",
      "image": {
          "absUrl": "https://example.com/images/large/ipod-classic-silver.jpg",
          "alt": {
              "default": "Apple iPod Classic, , large"
          },
          "path": "large/ipod-classic-silver.jpg",
          "title": {
              "default": "Apple iPod Classic, "
          }
      },
      "imageGroups": [
          {
              "images": [
                  {
                      "absUrl": "https://example.com/images/large/ipod-classic-silver.jpg",
                      "alt": {
                          "default": "Apple iPod Classic, , large"
                      },
                      "path": "large/ipod-classic-silver.jpg",
                      "title": {
                          "default": "Apple iPod Classic, "
                      }
                  }
              ],
              "viewType": "large"
          },
          {
              "images": [
                  {
                      "absUrl": "https://example.com/images/medium/ipod-classic-silver.jpg",
                      "alt": {
                          "default": "Apple iPod Classic, , medium"
                      },
                      "path": "medium/ipod-classic-silver.jpg",
                      "title": {
                          "default": "Apple iPod Classic, "
                      }
                  }
              ],
              "viewType": "medium"
          },
          {
              "images": [
                  {
                      "absUrl": "https://example.com/images/small/ipod-classic-silver.jpg",
                      "alt": {
                          "default": "Apple iPod Classic, , small"
                      },
                      "path": "small/ipod-classic-silver.jpg",
                      "title": {
                          "default": "Apple iPod Classic, "
                      }
                  }
              ],
              "viewType": "small"
          }
      ],
      "lastModified": "2019-08-28T18:49:09.000Z",
      "localizedTaxClassId": {
          "de": "exempt",
          "default": "standard",
          "en-US": "exempt"
      },
      "longDescription": {
          "default": {
              "markup": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats",
              "source": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats"
          }
      },
      "name": {
          "default": "Apple iPod Classic"
      },
      "onlineFlag": {
          "default": true
      },
      "owningCatalogId": "electronics-catalog",
      "owningCatalogName": {
          "default": "Electronics Master Catalog"
      },
      "pageDescription": {
          "default": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
      },
      "pageKeywords": {
          "default": "Apple, iPod, iPod Classic, MP3, Music Player"
      },
      "pageTitle": {
          "default": "Apple iPod Nano"
      },
      "primaryCategories": [
        {
            "catalogId": "apparel-catalog",
            "categoryId": "mens-accessories"
        },
        {
            "catalogId": "storefront-catalog-en",
            "categoryId": "top-seller"
        }
      ],
      "primaryCategoryId": "top-seller",
      "searchable": {
          "default": true
      },
      "shortDescription": {
          "default": {
              "markup": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go.",
              "source": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
          }
      },
      "taxClassId": "standard",
      "type": {
          "master": true
      },
      "validFrom": {
          "default": "1998-05-03T00:00:00.000Z",
          "default@SiteGenesis": "1998-05-11T00:00:00.000Z"
      },
      "validTo": {
          "default": "2028-07-03T00:00:00.000Z",
          "default@SiteGenesis": "2028-05-30T00:03:00.000Z"
      },
      "variants": [
          {
              "productId": "apple-ipod-classic-silver-120g",
              "variationValues": {
                  "color": "Silver",
                  "memorySize": "120 GB"
              }
          },
          {
              "productId": "apple-ipod-classic-black-120g",
              "variationValues": {
                  "color": "Black",
                  "memorySize": "120 GB"
              }
          }
      ],
      "variationAttributes": [
          {
              "attributeDefinitionId": "color",
              "attributeDefinitionName": {
                  "default": "Color"
              },
              "id": "color",
              "name": {
                  "default": "Color"
              },
              "shared": true,
              "slicing": false,
              "values": [
                  {
                      "name": {
                          "default": "Silver"
                      },
                      "position": 1.0,
                      "value": "Silver"
                  },
                  {
                      "name": {
                          "default": "Black"
                      },
                      "position": 2.0,
                      "value": "Black"
                  },
                  {
                      "name": {
                          "default": "Purple"
                      },
                      "position": 3.0,
                      "value": "Purple"
                  },
                  {
                      "name": {
                          "default": "Blue"
                      },
                      "position": 4.0,
                      "value": "Blue"
                  },
                  {
                      "name": {
                          "default": "Green"
                      },
                      "position": 5.0,
                      "value": "Green"
                  },
                  {
                      "name": {
                          "default": "Yellow"
                      },
                      "position": 6.0,
                      "value": "Yellow"
                  },
                  {
                      "name": {
                          "default": "Orange"
                      },
                      "position": 7.0,
                      "value": "Orange"
                  },
                  {
                      "name": {
                          "default": "Red"
                      },
                      "position": 8.0,
                      "value": "Red"
                  },
                  {
                      "name": {
                          "default": "Fuscia"
                      },
                      "position": 9.0,
                      "value": "Fuscia"
                  }
              ],
              "variationAttributeType": "string"
          },
          {
              "attributeDefinitionId": "memorySize",
              "attributeDefinitionName": {
                  "default": "Memory Size"
              },
              "id": "memorySize",
              "name": {
                  "default": "Memory Size"
              },
              "shared": true,
              "slicing": false,
              "values": [
                  {
                      "name": {
                          "default": "1 GB"
                      },
                      "position": 1.0,
                      "value": "1 GB"
                  },
                  {
                      "name": {
                          "default": "2 GB"
                      },
                      "position": 2.0,
                      "value": "2 GB"
                  },
                  {
                      "name": {
                          "default": "8 GB"
                      },
                      "position": 3.0,
                      "value": "8 GB"
                  },
                  {
                      "name": {
                          "default": "16 GB"
                      },
                      "position": 4.0,
                      "value": "16 GB"
                  },
                  {
                      "name": {
                          "default": "32 GB"
                      },
                      "position": 5.0,
                      "value": "32 GB"
                  },
                  {
                      "name": {
                          "default": "120 GB"
                      },
                      "position": 6.0,
                      "value": "120 GB"
                  }
              ],
              "variationAttributeType": "string"
          }
      ],
      "customCatalogName": {
        "default": "Apple Ipod Catalog"
      }
  }