#%RAML 1.0 NamedExample
value:
  {
    "limit": 1,
    "data": [
        {
            "id": "digitalCameraWarranty",
            "values" :
            [
                {
                  "_type" : "product_option_value",
                  "id" : "001",
                  "option_price" :
                  {
                      "USD" : "9.99"
                  },
                  "value" :
                  {
                      "default" : "1 Year Warranty"
                  }
                },

                {
                  "_type" : "product_option_value",
                  "id" : "003",
                  "option_price" :
                  {
                      "USD" : "29.99"
                  },
                  "value" :
                  {
                      "default" : "5 Year Warranty"
                  }
                },

                {
                  "_type" : "product_option_value",
                  "id" : "000",
                  "option_price" :
                  {
                    "USD" : "39.99"
                  },
                  "value" :
                  {
                      "default" : "None"
                  }
                },

                {
                  "_type" : "product_option_value",
                  "id" : "002",
                  "option_price" :
                  {
                      "USD" : "49.99"
                  },
                  "value" :
                  {
                      "default" : "3 Year Warranty"
                  }
                }
            ]
        }
    ],
    "offset": 0,
    "total": 1
}