#%RAML 1.0 NamedExample
value:
  {
    "id":"my-option",
    "value": {
        "default": "value 1",
        "en": "value 1(en)",
        "en-US": "value 1(en-US)"
    },
    "optionPrice": {
        "currencyMnemonic": "USD",
        "value": 100
    },
    "skuExtension": "s10"
  }