#%RAML 1.0 NamedExample
value:
  {
   "id":"my-option",
   "customName" :
   {
      "default" : "My Option"
   },
   "description" :
   {
      "default" : "Description for my option."
   },
   "image" :
   {
      "path" : "option.jpg"
   }
  }