#%RAML 1.0 NamedExample
value:
  {
    "orderable": true,
    "price": 500.00,
    "productId": "apple-ipod-classic-blue-32g",
    "variationValues": {
        "color": "Blue",
        "memorySize": "32 GB"
    }
  }