#%RAML 1.0 NamedExample
value:
  {
    "limit": 2,
    "expand": [
        "variations"
    ],
    "hits": [
        {
            "defaultProductVariation": false,
            "productId": "apple-ipod-classic-silver-120g",
            "variationValues": {
                "color": "Silver",
                "memorySize": "120 GB"
            }
        },
        {
            "defaultProductVariation": false,
            "productId": "apple-ipod-classic-black-120g",
            "variationValues": {
                "color": "Black",
                "memorySize": "120 GB"
            }
        }
    ],
    "query": {
        "textQuery": {
            "fields": [
                "id"
            ],
            "searchPhrase": "ipod"
        }
    },
    "offset": 0,
    "total": 2
}