#%RAML 1.0 NamedExample
value:
  {
    "attributeDefinitionId": "size",
    "attributeDefinitionName": {
        "default": "Size"
    },
    "id": "screenSize",
    "name": {
        "default": "Size"
    },
    "shared": false,
    "slicing": false,
    "variationAttributeType": "string"
  }