openapi: 3.0.3
info:
  title: Shopper Products API - Category Responses
  description: "Shopper Products API - Category Responses"
  version: 1.0.0
paths: {}
components:
  responses:
    GetCategoriesResponse:
      description: "Response of getCategories endpoint"
      content:
        application/json:
          schema:
            $ref: '../schemas/category.yaml#/components/schemas/CategoryResult'
          examples:
            GetCategoriesResponseExample:
              value:
                limit: 2
                data:
                  - id: electronics-digital-cameras
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw3535377d/images/slot/sub_banners/cat-banner-electronics-camera.jpg
                    name: Digital Cameras
                    onlineSubCategoriesCount: 0
                    pageDescription: Shop the latest digital cameras from all the top brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: cameras, digital camerasm point and shoot, slr
                    pageTitle: Digital Cameras
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                  - categories:
                      - id: electronics-televisions-flat-screen
                        image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dwc3940e75/images/slot/sub_banners/cat-banner-electronics-tv.jpg
                        name: Flat Screen
                        pageDescription: Shop all Flat Screen Televisions including the latest in LCD and Plasma technology from all the latest brands, makes and models at Salesforce Commerce Cloud.
                        pageKeywords: flat screen, flat screen television, LCD, plasma, HDTV
                        pageTitle: LCD & Plasma High Definition Flat Screen Televisions
                        parentCategoryId: electronics-televisions
                        parent_category_tree:
                          - id: electronics
                            name: electronics
                      - id: electronics-televisions-projection
                        image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dwc3940e75/images/slot/sub_banners/cat-banner-electronics-tv.jpg
                        name: Projection
                        onlineSubCategoriesCount: 0
                        pageDescription: Shop all Projection Televisions from all the latest brands, makes and models at Salesforce Commerce Cloud.
                        pageKeywords: projection, projection televisions, HDTV
                        pageTitle: Projection High Definition Televisions
                        parentCategoryId: electronics-televisions
                        parent_category_tree:
                          - id: electronics
                            name: electronics
                    id: electronics-televisions
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dwc3940e75/images/slot/sub_banners/cat-banner-electronics-tv.jpg
                    name: Televisions
                    onlineSubCategoriesCount: 2
                    pageDescription: Shop the latest Televisions including LCD, Plasma, Flat Screens, Projection including all the top brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: televisions, tvs, LCD, plasma, flat screen, high definition, HDTV, projection
                    pageTitle: Televisions Including LCD, Plasma & More in High Definition
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                total: 2
    GetCategoryResponse:
      description: "Response of getCategory endpoint"
      content:
        application/json:
          schema:
            $ref: '../schemas/category.yaml#/components/schemas/CategoryResult'
          examples:
            GetCategoryResponseExample:
              value:
                categories:
                  - id: electronics-televisions
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dwc3940e75/images/slot/sub_banners/cat-banner-electronics-tv.jpg
                    name: Televisions
                    onlineSubCategoriesCount: 2
                    pageDescription: Shop the latest Televisions including LCD, Plasma, Flat Screens, Projection including all the top brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: televisions, tvs, LCD, plasma, flat screen, high definition, HDTV, projection
                    pageTitle: Televisions Including LCD, Plasma & More in High Definition
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                    c_enableCompare: true
                    c_showInMenu: true
                    c_slotBannerImage: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw1d6f6411/images/slot/landing/cat-landing-tv.jpg
                  - id: electronics-digital-cameras
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw3535377d/images/slot/sub_banners/cat-banner-electronics-camera.jpg
                    name: Digital Cameras
                    onlineSubCategoriesCount: 0
                    pageDescription: Shop the latest digital cameras from all the top brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: cameras, digital camerasm point and shoot, slr
                    pageTitle: Digital Cameras
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                    c_enableCompare: true
                    c_showInMenu: true
                    c_slotBannerImage: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw1a543dc7/images/slot/landing/cat-landing-camera.jpg
                  - id: electronics-digital-media-players
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw7e9353db/images/slot/sub_banners/cat-banner-electronics-mp3.jpg
                    name: iPod & MP3 Players
                    onlineSubCategoriesCount: 0
                    pageDescription: Shop Digital Media Players including iPods, Creative Zen, Sony & the latest from all the top brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: mp3, iPods, mp3 players
                    pageTitle: iPod & MP3 Digital Media Players
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                    c_enableCompare: true
                    c_showInMenu: true
                    c_slotBannerImage: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw9f3d289a/images/slot/landing/cat-landing-mp3.jpg
                  - id: electronics-gps-units
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw6ea864f2/images/slot/sub_banners/cat-banner-electronics-gps.jpg
                    name: GPS Navigation
                    onlineSubCategoriesCount: 0
                    pageDescription: Shop the latest in GPS units from Garmin and Tom Tom along with other brands, makes and models at Salesforce Commerce Cloud.
                    pageKeywords: gps, gps units, garmin, tom tom
                    pageTitle: GPS Units
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                    c_enableCompare: true
                    c_showInMenu: true
                    c_slotBannerImage: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dwad4e06f8/images/slot/landing/cat-landing-gps.jpg
                  - id: electronics-gaming
                    image: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/default/dw9da58d91/images/slot/sub_banners/cat-banner-electronics.jpg
                    name: Gaming
                    onlineSubCategoriesCount: 2
                    pageDescription: Shop games and game consoles from Xbox, Xbox360, Playstation 2, Playstation 3, Game Cube, Wii, Playstation Portable and Nintento DS at Salesforce Commerce Cloud.
                    pageKeywords: gaming, xbox, xbox360, ps3, ps2, playstaion 3, psp, game cube, wii, nintendo, nintendo ds
                    pageTitle: Gaming
                    parentCategoryId: electronics
                    parent_category_tree:
                      - id: electronics
                        name: electronics
                    c_enableCompare: true
                    c_showInMenu: true
                    c_slotBannerImage: https://example.com/on/demandware.static/-/Sites-storefront-catalog-en/en_US/v1551233475301/images/slot/landing/cat-landing-gaming.jpg
                id: electronics
                name: Electronics
                onlineSubCategoriesCount: 5
                pageDescription: Shop Electronics including the latest in televisions, digital cameras, camcorders, mp3, ipod, mobil phones, GPS & gaming at Salesforce Commerce Cloud
                pageKeywords: televisions, digital cameras, camcorders, mp3, ipod, mobil phones, GPS, gaming
                pageTitle: Shop Electronics Including Televisions, Digital Cameras, iPods & More
                parentCategoryId: root
                parent_category_tree:
                  - id: root
                    name: root
                c_enableCompare: true
                c_headerMenuOrientation: Vertical
                c_showInMenu: true