#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Data Campaigns API.
responses:
  404:
    description:
      Thrown when there is no campaign found with the given ID for the requested site.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
          "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/campaign-not-found",
          "detail": "No campaign with ID 'SpecialCampaign' in site 'SiteGenesis' could be found.",
          "title": "Not Found Error"
          }           