#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response for an ID conflict for campaign in the Data Campaigns API.
responses:
  400:
    description:
      Thrown if the ID in request is not the same as the ID in document.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
          "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/id-conflict",
          "detail": "The ID in the request body ('CampaignXYZ') doesn't match the ID in the URL ('NewWinterCampaign')",
          "title": "Duplicate Error"
          }         