openapi: 3.0.3
info:
  title: Shopper Promotions
  version: v1
  description: |-
    # API Overview

    Retrieve information about active promotions within the context of a shopper and a site. You can use this API to retrieve promotions that you configured in the commerce platform by searching for specific promotion IDs or by searching for promotions associated with a campaign.

    Caching is provided for the Shopper Promotions API. For details, see [Server-Side Web-Tier Caching.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/server-side-web-tier-caching.html)

    ## Authentication & Authorization

    The Shopper Promotions API requires a JSON Web Token acquired via the Shopper Customers endpoint:

    ```
    https://{{shortcode}}.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/{{organizationId}}/customers/actions/login
    ```

    You must include the relevant scope(s) in the client ID used to generate the SLAS token. For details, see [Authorization Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html)

    ## Use Cases

    ### Get Promotion by Promotion ID

    Use the Shopper Promotions API to find promotion information by the promotion ID.

    For example, a customer who is browsing on a commerce shopping app built using Commerce Cloud APIs can see the details about the applied promotions in the cart.

    ### Get Promotion by Campaign ID

    Use the Shopper Promotions API to find promotion information by the campaign ID.

    For example, a customer who is browsing on a commerce shopping app built using Commerce Cloud APIs can see the possible promotions that can be applied in the cart.

    ### Use Hooks

    For details working with hooks, see [Extensibility with Hooks.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/extensibility_via_hooks.html)
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/pricing/shopper-promotions/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/promotions:
    get:
      summary: Return an array of enabled promotions for specified IDs.
      description: "In the request URL, you can specify up to 50 IDs. If you specify an ID that contains either parentheses or the separator characters, you must URL encode these characters. \nEach request returns only enabled promotions as the server does not consider promotion qualifiers or schedules."
      operationId: getPromotions
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/ids'
        - $ref: '#/components/parameters/locale'
      responses:
        '200':
          description: Promotion information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromotionResult'
              examples:
                PromotionsResult:
                  $ref: '#/components/examples/PromotionsResult'
        '404':
          description: Thrown when there is no promotion found with the given ID for the requested site.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getPromotions404:
                  $ref: '#/components/examples/PromotionsNotFound404'
      security:
        - ShopperToken:
            - sfcc.shopper-promotions
  /organizations/{organizationId}/promotions/campaigns/{campaignId}:
    get:
      summary: Return an array of enabled promotions matching the specified filter criteria.
      description: |-
        Retrieves promotion information using filter criteria. In the request URL, you must provide a campaign_id parameter, and you can optionally specify a date
        range by providing start_date and end_date parameters. Both parameters are required to specify a date range, and
        omitting one causes the server to return a MissingParameterException fault. Each request returns only enabled
        promotions, since the server does not consider promotion qualifiers or schedules.
      operationId: getPromotionsForCampaign
      parameters:
        - $ref: '#/components/parameters/campaignId'
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
        - $ref: '#/components/parameters/currency'
      responses:
        '200':
          description: Retrieved promotion information successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromotionResult'
              examples:
                PromotionsResult:
                  $ref: '#/components/examples/PromotionsResult'
        '400':
          description: Thrown when a start date is provided without an end date, when an end date is provided without a start date, or when an end date precedes the start date.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getPromotionsForCampaign400:
                  $ref: '#/components/examples/InvalidDate400'
        '404':
          description: Thrown when no promotion with the specified ID is found for the requested site.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getPromotions404:
                  $ref: '#/components/examples/PromotionsNotFound404'
      security:
        - ShopperToken:
            - sfcc.shopper-promotions
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      description: "ShopperToken authentication follows the authorization code grant flow, as defined by the OAuth 2.1 standard. Depending on the type of OAuth client (public or private), this authorization flow has further requirements. \nFor a detailed description of the authorization flow, see the [SLAS overview](https://developer.salesforce.com/docs/commerce/commerce-api/references?meta=shopper-login:Summary).\nA shopper token allows you to access the Shopper API endpoints of both OCAPI and the B2C Commerce API. These endpoints can be used to build headless storefronts and other applications.\nThe `ShopperToken` security scheme is a parent of other security schemes, such as `ShopperTokenTsob`. A Shopper API endpoint can require a specific child scheme (`ShopperTokenTsob`, for example) that cannot be accessed with a regular shopper token.\n"
      flows:
        clientCredentials:
          tokenUrl: https://{shortCode}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc:shopper-promotions: Allows read operations on shopper promotions
        authorizationCode:
          authorizationUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/authorize
          tokenUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-promotions: Allows read operations on shopper promotions
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
    LanguageCountry:
      pattern: ^[a-z][a-z]-[A-Z][A-Z]$
      description: A concatenated version of the standard Language and Country codes, combined with a hyphen '`-`'.
      example: en-US
      type: string
    LanguageCode:
      pattern: ^[a-z][a-z]$
      description: A two letter lowercase language code conforming to the [ISO 639-1](https://www.iso.org/iso-639-language-codes.html) standard. Additionally, this may be used to submit requests with the header parameter `Accept-Language`, following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766).
      example: en
      type: string
    DefaultFallback:
      default: default
      description: A specialized value indicating the system default values for locales.
      example: default
      enum:
        - default
      type: string
    LocaleCode:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      oneOf:
        - $ref: '#/components/schemas/LanguageCountry'
        - $ref: '#/components/schemas/LanguageCode'
        - $ref: '#/components/schemas/DefaultFallback'
    Limit:
      default: 10
      minimum: 1
      format: int32
      description: Maximum records to retrieve per request, not to exceed the maximum defined. A limit must be at least 1 so at least one record is returned (if any match the criteria).
      type: integer
      example: 10
    Total:
      default: 0
      minimum: 0
      format: int64
      description: The total number of hits that match the search's criteria. This can be greater than the number of results returned as search results are pagenated.
      type: integer
      example: 10
    ResultBase:
      description: "Schema defining generic list result. Each response schema of a resource requiring a list response should extend this schema. \nAdditionally it needs to be defined what data is returned."
      type: object
      required:
        - limit
        - total
      properties:
        limit:
          maximum: 200
          allOf:
            - $ref: '#/components/schemas/Limit'
        total:
          $ref: '#/components/schemas/Total'
    Promotion:
      description: Document representing a promotion.
      additionalProperties:
        title: Additional Property Support
        description: |-
          This type supports additional properties passed along with the defined properties of this API.
          To indicate that the properties were defined and expected to be handled as additional properties, they are expected to be prefixed with a `c_`.
          The type will reject any property that does not fit this pattern, only allowing additional properties beginning with the known prefix.
        example: c_trackingId
      type: object
      required:
        - id
      properties:
        calloutMsg:
          description: The localized call-out message of the promotion.
          example: $30 Fixed Shipping Amount Above 150
          type: string
        currency:
          description: |-
            The currency that a promotion can be applied to. A null value means that the promotion applies to all allowed
             currencies.
          example: USD
          type: string
        details:
          description: The localized detailed description of the promotion.
          example: $30 Fixed Shipping Amount Above 150
          type: string
        endDate:
          description: |-
            The end date of the promotion. This property follows the ISO8601 date time format: yyyy-MM-dd'T'HH:mmZ . The time
             zone of the date time is always UTC.
          example: '2015-07-04T21:00:00Z'
          type: string
          format: date-time
        id:
          description: The unique ID of the promotion.
          example: $30FixedShippingAmountAbove150
          type: string
        image:
          description: The URL to the promotion image.
          type: string
        name:
          description: The localized name of the promotion.
          example: $30 Fixed Shipping Amount Above 150
          type: string
        startDate:
          description: |-
            The start date of the promotion. This property follows the ISO8601 date time format: yyyy-MM-dd'T'HH:mmZ. The
             time zone of the date time is always UTC.
          example: '2015-07-04T21:00:00Z'
          type: string
          format: date-time
    PromotionResult:
      description: Result document containing an array of promotions.
      required:
        - data
      type: object
      allOf:
        - $ref: '#/components/schemas/ResultBase'
      properties:
        data:
          description: The array of promotion documents.
          type: array
          items:
            $ref: '#/components/schemas/Promotion'
      example:
        limit: 2
        data:
          - calloutMsg: Buy5for50
            details: Buy5for50
            id: Buy5for50
            name: Buy5for50
          - calloutMsg: $5 off Men's Ties
            details: $5 off Men's Ties (with coupon)
            id: $5_off_ties_promotion
            name: 5 Off Ties Promotion
        total: 2
      additionalProperties: false
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
    ISOCurrency:
      pattern: ^[A-Z][A-Z][A-Z]$
      description: A three letter uppercase currency code conforming to the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard.
      example: USD
      type: string
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
    ids:
      name: ids
      in: query
      required: true
      schema:
        type: array
        items:
          type: string
          maxLength: 256
    locale:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      name: locale
      in: query
      examples:
        LanguageCountry:
          value: en-US
        CountryCode:
          value: US
      schema:
        $ref: '#/components/schemas/LocaleCode'
    campaignId:
      name: campaignId
      in: path
      description: Find the promotions assigned to this campaign (mandatory).
      required: true
      schema:
        maxLength: 256
        minLength: 1
        type: string
    startDate:
      name: startDate
      in: query
      description: 'The start date of the promotion in ISO8601 date time format: yyyy-MM-dd''T''HH:mmZ'
      required: false
      schema:
        type: string
    endDate:
      name: endDate
      in: query
      description: 'The end date of the promotion in ISO8601 date time format: yyyy-MM-dd''T''HH:mmZ'
      required: false
      schema:
        type: string
    currency:
      name: currency
      in: query
      description: The currency mnemonic specified for price. This parameter is effective only for product suggestions.
      required: false
      schema:
        $ref: '#/components/schemas/ISOCurrency'
  examples:
    PromotionsResult:
      value:
        limit: 2
        data:
          - calloutMsg: Buy5for50
            details: Buy5for50
            id: Buy5for50
            name: Buy5for50
          - calloutMsg: $5 off Men's Ties
            details: $5 off Men's Ties (with coupon)
            id: $5_off_ties_promotion
            name: 5 Off Ties Promotion
        total: 2
    PromotionsNotFound404:
      value:
        type: /PromotionNotFoundException
        detail: There is no promotion found with the given ID for the requested site.
        title: Not Found
        instance: /foo
    InvalidDate400:
      value:
        type: /InvalidDateException
        detail: Invalid Start or End Date
        title: Invalid Start or End Date
        instance: /foo
