#%RAML 1.0 NamedExample
value:
  {
    "active": false,
    "active_redirect": {
        "_type": "source_code_redirect_info",
        "location": "https://production-functional23-qa.demandware.net/s/-/dw/data/v18_7/sites/SiteGenesis/source_code_groups/20%25%20off%20%28%C2%A330%29%20New%20Customer",
        "location_type": "url"
    },
    "creation_date": "2019-11-25T15:24:25.317Z",
    "description": "description for source code group test",
    "enabled": false,
    "end_time": "2030-10-01T00:00:00.000Z",
    "id": "20% off (£30) New Customer",
    "inactive_redirect": {
        "_type": "source_code_redirect_info",
        "location": "https://production-functional23-qa.demandware.net/on/demandware.store/Sites-Site/default/ViewApplication-DisplayWelcomePage",
        "location_type": "url"
    },
    "last_modified": "2019-11-25T15:24:25.320Z",
    "link": "https://production-functional23-qa.demandware.net/s/-/dw/data/v18_7/sites/SiteGenesis/source_code_groups/20%25%20off%20%28%C2%A330%29%20New%20Customer",
    "start_time": "2014-10-01T00:00:00.000Z"
  }