#%RAML 1.0 NamedExample
patch-promotion-request:
  {
    "enabled" : false,  
    "name" : {
      "default" : "__PROMOTION_ID__"
    },
    "exclusivity" : "class",
    "promotionClass" : "order",
    "c_customString": "Custom Value"
  }