#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response when no rule could be found for the specified rule ID.

responses:
  404:
    description: |
            Resource requested not found.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Rule Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/rule-not-found",
            "detail": "No Rule with ID 'VHRULE' could be found.",
            "ruleId": "VHRULE"
           }