#%RAML 1.0 NamedExample
value:
  { 
   "description" : "Gift certificate sample description-updated",
   "enabled" :false, 
   "message" : "Gift certificate sample message-updated",
   "recipientEmail": "updatedemail@abc.com",
   "recipientName": "xyz-updated",
   "senderName": "abc-updated",
   "status": "pending"
}