#%RAML 1.0 SecurityScheme

description: |
  Trusted System on Behalf Token OAuth Token Authentication.  
  TSOB authentication is done by requesting a TSOB token from SLAS using grant, hint, login_id, idp_origin, channel_id and a basic authentication header with a SLAS client id and client secret. A Shopper JWT is returned in 'access_token' of the response. The 'scp' claim from the Shopper JWT should be validated to have 'sfcc.ts_ext_in_behalf_of' scope. The shopper JWT signature should also be validated and that the Shopper JWT has not expired.
type: OAuth 2.0

uses:

describedBy:
  headers:
    Authorization:
      description: |
        OAuth 2.0 access-token in Bearer scheme
      type: string
      pattern: "Bearer .*"
      examples: 
        authenticatedUser: Bearer b325e95c-2cd7-11e5-b345-feff819cdc9f
  responses:
    401:
      description: Unauthorized. Your access-token is invalid or expired and could not be used to identify an API client or user.
      headers:
        WWW-Authenticate: 
          example: |
            WWW-Authenticate: Bearer realm="servers",
                              error="invalid_token",
                              error_description="The access-token expired"
      body:
        application/json:
          type: !include ../Types/error-response.raml
          example:
            type: "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unauthorized"
            title: Unauthorized
            detail: Your access-token is invalid and could not be used to identify an API client or user.
    403:
      description: Forbidden. Your access-token is valid, but you have no permissions to access the resource.
      body:
        application/json:
          type: !include ../Types/error-response.raml
          example:
            type: "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden"
            title: Forbidden
            detail: Your access-token is valid, but you have no permissions to access the resource.
settings:
  accessTokenUri: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/trusted-system/token
  authorizationGrants: [client_credentials]
  