#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Data Coupons API.

responses:
  404:
    description: |
            Thrown if the coupon does not exist matching the given ID.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
              "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-not-found",
              "title": "Coupon Not Found",
              "detail": "No coupon with ID 'foo' for site 'RefArch' could be found.",
              "couponId": "foo",
              "siteId": "RefArch"
          }        
