#%RAML 1.0 NamedExample
value:
  {
    "data":
      {
        "headerName": "x-sfdc-access-control",
        "headerValue": "********789",
        "lastUpdated": "2024-04-27T18:32:34.675182Z"
      }
  }