#%RAML 1.0 DocumentationItem
title: baseUri Standards
content: |
  The baseUri has been standardized as the following. You should use the below snippet in your RAML definitions:
          
      baseUri: https://{shortCode}.api.commercecloud.salesforce.com/{apiFamily}/{apiName}/{version}
      version: v1
      baseUriParameters:
        shortCode:
          description: A region-specific merchant identifier.
          example: fd4gt8
          pattern: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
        apiFamily:
          description: Api Family of the API, also known as the bounded context (Should never change within your API)
          default: my-api-family
          example: product
          pattern: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
        apiName:
          description: The name of the specific API, also known as the root aggregate (Should never change within your API)
          default: my-api-name
          example: catalogs
          pattern: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$


  Of note:
    - the baseUri is templated URL that is templated for constency, all URLs accross commerce cloud will have the same baseUrl
    - you MUST set the default values of the apiFamily and apiName in the URI parameters.  These shouldn't ever change.
    - the only baseUriParameter that will change between calls is `shortCode`.
      - `version` is special and will use the version of the API. 
      - `apiFamily` and `apiName` should be treated as constants
    
