#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in when Product with the given Product Id could not be found..

responses:
  404:
    description: |
            Resource requested not found.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Product Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/product-not-found",
            "detail": "No product with ID '1585183329877' could be found.",
            "productId": "1585183329877"
           }