#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in when Product with the given Product Id could not be found..

responses:
  404:
    description: |
            Resource requested not found.
    body:
      application/json:
        type: Error
        example: |
          {
            "type": "ProductNotFoundException",
            "title": "No product with ID 'apple-ipod-s' for site 'SiteGenesis' could be found.",
            "detail": "Resource Not Found"
          }