#%RAML 1.0 Trait
description: This trait represents API behavior for a 401 response when an invalid client_id is passed.

responses:
  401:
    description: |
            Unauthorized. Your Client ID is invalid, or you are not allowed to access
            the content provided by the requested URL.
    body:
      application/json:
        type: Error
        example: |
          {
            "type": "UnknownClientIdException",
            "title": "Client ID 'asddhjt-2e5t-4dfe-567f-678d27c0d8f2' is unknown.",
            "detail": "Client Id is not valid"
          }