#%RAML 1.0 Trait

usage: |
  To be applied on endpoints that use offset and limit pagination controls as 
  described in [pagination controls](https://confluence.internal.salesforce.com/display/ENG/RESTful+APIs+Conventions+and+Standards+v1.1).
  Parameters:
    - `maxLimit` (integer): the max value for the limit

uses:
  pagination: ../dataTypes/pagination-types.raml

queryParameters: 
  offset: 
    required: false 
    type: pagination.offset
  limit: 
    required: false
    description: Maximum records to retrieve per request, not to exceed <<maxLimit>>. Defaults to <<defaultSize>>.
    type: pagination.limit
    maximum: <<maxLimit>>
    default: <<defaultSize>>

responses: 
  200:
    headers:
      SFDC-Pagination-Offset:
        type: number
        description: The starting offset returned. 
      SFDC-Pagination-Limit:
        type: number
        description: The limit requested.
      SFDC-Pagination-Total-Count?:
        type: number
        description: The total number of records available.
      SFDC-Pagination-Result-Count?:
        type: number
        description: The number of results included in the response.

