#%RAML 1.0 NamedExample
value:
  {
    "limit": 2,
    "hits": [
      {
        "brand": "Apple",
        "creationDate": "2019-02-21T22:10:02.000Z",
        "id": "apple-ipod-classic",
        "lastModified": "2019-09-17T19:13:39.000Z",
        "longDescription": {
          "default": {
            "markup": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats",
            "source": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats"
          }
        },
        "name": {
          "default": "Apple iPod Classic"
        },
        "onlineFlag": {
          "default": true
        },
        "owningCatalogId": "electronics-catalog",
        "owningCatalogName": {
          "default": "Electronics Master Catalog"
        },
        "pageDescription": {
          "default": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
        },
        "pageKeywords": {
          "default": "Apple, iPod, iPod Classic, MP3, Music Player"
        },
        "pageTitle": {
          "default": "Apple iPod Nano"
        },
        "searchable": {
          "default": true
        },
        "shortDescription": {
          "default": {
            "markup": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go.",
            "source": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
          }
        },
        "type": {
          "master": true
        }
      },
      {
        "brand": "Apple",
        "creationDate": "2019-09-04T16:07:43.000Z",
        "id": "apple-ipod-classic-1",
        "lastModified": "2019-09-04T16:19:03.000Z",
        "longDescription": {
          "default": {
            "markup": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats",
            "source": "Supports MP3, MP3 VBR, AAC, Protected AAC, Audible 2, 3 and 4, Apple Lossless and AIFF audio formats; also supports JPEG, BMP, GIF, TIFF, PSD (Mac only) and PNG image formats and H.264 (high-definition), MPEG-4 and MPEG-4 video formats"
          }
        },
        "name": {
          "default": "Apple iPod Classic"
        },
        "onlineFlag": {
          "default": false
        },
        "owningCatalogId": "electronics-catalog",
        "owningCatalogName": {
          "default": "Electronics Master Catalog"
        },
        "pageDescription": {
          "default": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
        },
        "pageKeywords": {
          "default": "Apple, iPod, iPod Classic, MP3, Music Player"
        },
        "pageTitle": {
          "default": "Apple iPod Nano"
        },
        "searchable": {
          "default": false
        },
        "shortDescription": {
          "default": {
            "markup": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go.",
            "source": "This iPod delivers everything you love about iPod with added features all wrapped in a tiny 4.9 oz. package. With 120GB of storage and up to 36 hours music playback, iPod classic lets you enjoy up to 30,000 songs or 150 hours of video — or a combination — wherever you go."
          }
        },
        "type": {
          "variationGroup": true,
          "master": false
        }
      }
    ],
    "query": {
      "textQuery": {
        "fields": [
          "id"
        ],
        "searchPhrase": "apple-ipod-classic"
      }
    },
    "offset": 0,
    "total": 2
  }