#%RAML 1.0 NamedExample
value:
  {
    "limit": 3,
    "data": [
        {
            "attributeDefinitionId": "color",
            "attributeDefinitionName": {
                "default": "Color"
            },
            "id": "color",
            "name": {
                "default": "Color"
            },
            "shared": true,
            "slicing": false,
            "values": [
                {
                    "name": {
                        "default": "Silver"
                    },
                    "position": 1.0,
                    "value": "Silver"
                },
                {
                    "name": {
                        "default": "Black"
                    },
                    "position": 2.0,
                    "value": "Black"
                },
                {
                    "name": {
                        "default": "Purple"
                    },
                    "position": 3.0,
                    "value": "Purple"
                },
                {
                    "name": {
                        "default": "Blue"
                    },
                    "position": 4.0,
                    "value": "Blue"
                },
                {
                    "name": {
                        "default": "Green"
                    },
                    "position": 5.0,
                    "value": "Green"
                },
                {
                    "name": {
                        "default": "Yellow"
                    },
                    "position": 6.0,
                    "value": "Yellow"
                },
                {
                    "name": {
                        "default": "Orange"
                    },
                    "position": 7.0,
                    "value": "Orange"
                },
                {
                    "name": {
                        "default": "Red"
                    },
                    "position": 8.0,
                    "value": "Red"
                },
                {
                    "name": {
                        "default": "Fuscia"
                    },
                    "position": 9.0,
                    "value": "Fuscia"
                }
            ],
            "variationAttributeType": "string"
        },
        {
            "attributeDefinitionId": "memorySize",
            "attributeDefinitionName": {
                "default": "Memory Size"
            },
            "id": "memorySize",
            "name": {
                "default": "Memory Size"
            },
            "shared": true,
            "slicing": false,
            "values": [
                {
                    "name": {
                        "default": "1 GB"
                    },
                    "position": 1.0,
                    "value": "1 GB"
                },
                {
                    "name": {
                        "default": "2 GB"
                    },
                    "position": 2.0,
                    "value": "2 GB"
                },
                {
                    "name": {
                        "default": "8 GB"
                    },
                    "position": 3.0,
                    "value": "8 GB"
                },
                {
                    "name": {
                        "default": "16 GB"
                    },
                    "position": 4.0,
                    "value": "16 GB"
                },
                {
                    "name": {
                        "default": "32 GB"
                    },
                    "position": 5.0,
                    "value": "32 GB"
                },
                {
                    "name": {
                        "default": "120 GB"
                    },
                    "position": 6.0,
                    "value": "120 GB"
                }
            ],
            "variationAttributeType": "string"
        },
        {
            "attributeDefinitionId": "size",
            "attributeDefinitionName": {
                "default": "Size"
            },
            "id": "screenSize",
            "name": {
                "default": "Size"
            },
            "shared": false,
            "slicing": false,
            "values": [
                {
                    "description": {
                        "default": "desc of 8 (default)",
                        "en-US": "desc of 8 (en-US)",
                        "en": "desc of 8 (en)"
                    },
                    "position": 1.0,
                    "value": "8"
                }
            ],
            "variationAttributeType": "string"
        }
    ],
    "offset": 0,
    "total": 3
}