#%RAML 1.0 NamedExample
value:
  {
    "clientId": "client-id1",
    "secret": "secret12345",
    "name": "ShopperClient1",
    "ecomTenant": "test_prd",
    "ecomSite": "SiteGenesis",
    "scopes": [
        "sfcc.products",
        "sfcc.catalogs",
        "sfcc.products.ro"
    ],
    "redirectUri": "http://localhost:9010/callback",
    "channels": ["SiteGenesis",
                 "OtherSite"],
    "privateClient": true
}