#%RAML 1.0 NamedExample
value:
  {
    "clientId": "client-id1",
    "name": "High Adventure Wear",
    "secret": "secret1234",
    "scopes": ["sfcc.products",
              "sfcc.catalogs",
              "sfcc.customers:ro"],
    "redirectUri": "http://localhost/callback",
    "callbackUri": "http://localhost:9010/pwd/reset/callback",
    "channels": ["SiteGenesis",
                 "OtherSite"],
    "privateClient": true
  }