#%RAML 1.0 NamedExample
value: 
  {
    "tenantId": "aaaa_prd",
    "checkCount": 40,
    "credsOkay": 1024,
    "repeatedCompromisedUse": 12,
    "credsCompromised": 0,
    "exposure1": 0,
    "exposure2to4": 0,
    "exposure5to9": 0,
    "exposure10plus": 0,
    "pwdsOkay": 47,
    "pwdsCompromised": 3,
    "avgPwdStrength": 5.0,
    "avgCredQualityMeasure": 0.0,
    "avgPwdQualityMeasure": 0.0,
    "medPwdStrength": 0.0,
    "medCredQualityMeasure": 0.0,
    "medPwdQualityMeasure": 0.0
  }