#%RAML 1.0 NamedExample
value:
  {
    "id": 100,
    "name": "Google",
    "clientId": "idp-client-id",
    "clientSecret": "idp-secret",
    "authUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://www.googleapis.com/oauth2/v3/token",
    "tokenInfoUrl": "https://www.googleapis.com/oauth2/v3/tokeninfo",
    "userInfoUrl": "https://www.googleapis.com/oauth2/v3/userinfo",
    "redirectUrl": "http://localhost:9010/api/v1/idp/callback/Google",
    "scopes": ["openid","email","profile"],
    "isPreferred": true
  }