#%RAML 1.0 NamedExample
value:
  {
    data: 
    [
      {
          "name": "auth0",
          "clientId": "idp-client-id",
          "clientSecret": "idp-secret",
          "authUrl": "https://slas-auth0-dev.us.auth0.com/authorize",
          "tokenUrl": "https://slas-auth0-dev.us.auth0.com/oauth/token",
          "tokenInfoUrl": "https://slas-auth0-dev.us.auth0.com/userinfo",
          "userInfoUrl": "https://slas-auth0-dev.us.auth0.com/userinfo",
          "redirectUrl": "http://localhost:9010/api/v1/idp/callback/auth0",
          "isPreferred": false
      },
      {
          "name": "Google",
          "clientId": "idp-client-id",
          "clientSecret": "idp-secret",
          "authUrl": "https://accounts.google.com/o/oauth2/v2/auth",
          "tokenUrl": "https://www.googleapis.com/oauth2/v3/token",
          "tokenInfoUrl": "https://www.googleapis.com/oauth2/v3/tokeninfo",
          "userInfoUrl": "https://www.googleapis.com/oauth2/v3/userinfo",
          "redirectUrl": "http://localhost:9010/api/v1/idp/callback/Google",
          "isPreferred": false
      },
      {
          "name": "okta",
          "clientId": "idp-client-id",
          "clientSecret": "idp-secret",
          "authUrl": "https://dev-9565236.okta.com/oauth2/v1/authorize",
          "tokenUrl": "https://dev-9565236.okta.com/oauth2/v1/token",
          "tokenInfoUrl": "https://dev-9565236.okta.com/oauth2/v1/introspect",
          "userInfoUrl": "https://dev-9565236.okta.com/oauth2/v1/userinfo",
          "redirectUrl": "http://localhost:9010/api/v1/idp/callback/okta",
          "isPreferred": false
      },
      {
          "name": "salesforce",
          "clientId": "idp-client-id",
          "clientSecret": "idp-secret",
          "authUrl": "https://login.salesforce.com/services/oauth2/authorize",
          "tokenUrl": "https://login.salesforce.com/services/oauth2/token",
          "tokenInfoUrl": "https://login.salesforce.com/services/oauth2/introspect",
          "userInfoUrl": "https://login.salesforce.com/services/oauth2/userinfo",
          "redirectUrl": "http://localhost:9010/api/v1/idp/callback/salesforce",
          "isPreferred": false
      }
    ]
  }