#%RAML 1.0 NamedExample
value:
  {
    "tenantId": "slsa_dev",
    "merchantName": "Popular Merchant",
    "description": "Merchant Description",
    "contact": "Jerry Smith",
    "emailAddress": "jerry@merchant.com",
    "phoneNo": "801-555-1234"
  }