#%RAML 1.0 Library

types:
  ErrorCodeTypesEnum:
    type: ErrorCodesEnum
  TenantNotProvisionedEnum:
    enum: [TenantNotProvisioned]
    type: string
    example: TenantNotProvisioned

  EntityNotFoundEnum:
    enum: [EntityNotFound]
    type: string
    example: EntityNotFound

  InvalidRequestLocOrGroupDoesNotExistEnum:
    enum: [InvalidRequest, LocationDoesNotExist, GroupDoesNotExist]
    type: string
    example: LocationDoesNotExist

  InvalidRequestParameterEnum:
    enum: [InvalidRequestParameter]
    type: string
    example: InvalidRequestParameter

  InvalidRequestParameterLocOrGroupDoesNotExistEnum:
    enum: [InvalidRequestParameter, LocationDoesNotExist, GroupDoesNotExist]
    type: string
    example: LocationDoesNotExist

  InvReqParamInvReqLocOrGroupDoesNotExistEnum:
    enum: [InvalidRequest, InvalidRequestParameter, LocationDoesNotExist, GroupDoesNotExist]
    type: string
    example: GroupDoesNotExist

  MissingParameterEnum:
    enum: [MissingParameter]
    type: string
    example: MissingParameter
    
  ErrorCodesEnum:
    enum:
      - InsufficientQuantity
      - DuplicateGroupId
      - InvalidGroupId
      - DuplicateSku
      - MissingParameter
      - InvalidRequest
      - InvalidRequestParameter
      - EntityAlreadyExists
      - PositiveQuantityRequired
      - ReservationInUnknownState
      - ReservationInvalidState
      - ReservationCancelled
      - EntityNotFound
      - ReservationCancellationFailed
      - ExportInProcess
      - ExportProcessFailed
      - Unknown
      - DuplicateEventId
      - ReservationOperationInProcess
      - ConcurrentModification
      - GroupDoesNotExist
      - OnlyOneLocationSupported
      - NotAppliedDueToAtomicFailure
      - ImportInProgress
      - ExpiredDeltaLink
      - InventoryReset
      - UnableToStartExport
      - ResourceNotFound
      - LocationListMustNotBeEmpty
      - SeeOtherResource
      - TenantNotProvisioned
      - ReservationAlreadyFinalized
      - MismatchedGroupAndLocation
      - GroupMustNotBeEmpty
      - LocationListTooLarge
      - ExpiredUploadLink
      - ExpiredResultLink
      - FileAlreadyReceived
      - IllegalGroupState
      - DeleteTenantNotAllowed
      - TenantResetInProgress
      - LocationDoesNotExist
      - LocationNotInGroup
      - PreviousRequestAborted
      - PreviousRequestCancelled
      - DuplicateLocationId
    type: string
    example: InsufficientQuantity
