#%RAML 1.0 NamedExample
value:
  {
    "address1": "123 Trailblazer Ave.",
    "address2": "",  
    "addressId": "HomeAddress",
    "city": "San Francisco",
    "companyName": "",
    "countryCode": "US",
    "firstName": "Wei",
    "fullName": "Wei Leung",
    "jobTitle": "",
    "lastName": "Leung",
    "phone": "",
    "postalCode": "",
    "postBox": "",
    "salutation": "Ms.",
    "secondName": "",
    "state_code": "CA",
    "suffix": "",
    "suite": "",
    "title": ""
  }
