#%RAML 1.0 NamedExample
value:
  {
    "addressId": "3",
    "city": "San Francisco",
    "companyName": "Ursa Major Solar",
    "countryCode": "US",
    "creationDate": "2019-09-23T20:49:38.370Z",
    "etag": "8772fd1c59fed8313a6c1ad260544c116dc0af4bc13941957173244edba47d31",
    "firstName": "Wei",
    "fullName": "Wei Leung",
    "jobTitle": "",
    "lastModified": "2019-09-23T20:49:38.372Z",
    "lastName": "Leung",
    "phone": "415-555-1212",
    "postalCode": "94105",
    "salutation": "Ms",
    "secondName": "",
    "stateCode": "CA"
  }
