#%RAML 1.0 NamedExample
value:
  {
    "address1": "700 Monsters University Cir.",
    "address2": "",  
    "addressId": "HomeAddress",
    "city": "Grand Junction",
    "companyName": "",
    "countryCode": "US",
    "firstName": "Mike",
    "fullName": "Mike Wazowski",
    "jobTitle": "",
    "lastName": "Wazowski",
    "phone": "",
    "postalCode": "",
    "postBox": "",
    "salutation": "Mr.",
    "secondName": "",
    "state_code": "CO",
    "suffix": "",
    "suite": "",
    "title": ""
  }
