#%RAML 1.0 NamedExample
value:
  {
    "limit": 1,
    "data": [
        {
            "addressId": "1",
            "city": "San Francisco",
            "companyName": "Ursa Major Solar",
            "countryCode": "US",
            "creationDate": "2019-09-23T16:14:07.000Z",
            "etag": "d288bfd83f75b23640b4bbab2b0d3f65a5c5e934dab818f2246b7c1aed5672f8",
            "firstName": "Wei",
            "fullName": "Leung",
            "jobTitle": "",
            "lastModified": "2019-09-23T16:23:19.000Z",
            "lastName": "Leung",
            "phone": "415-555-1212",
            "postalCode": "94105",
            "salutation": "Ms",
            "secondName": "",
            "stateCode": "CA"
        }
    ],
    "offset": 0,
    "total": 1
  }