#%RAML 1.0 NamedExample
value:
  {
    "addressId": "2",
    "address1": "",
    "postalCode": "33122",
    "lastName": "RR",
    "title": "",
    "salutation": "Ms",
    "companyName": "Ursa Major Solar",
    "secondName": "richi",
    "phone": "123-456-7890",
    "countryCode": "US",
    "city": "ATLANTA",
    "address2": "",
    "firstName": "gwedolyn",
    "jobTitle": "Actor",
    "stateCode": "GA"
  }

