#%RAML 1.0 NamedExample
value:
  {
    "addressId": "3",
    "city": "ATLANTA",
    "companyName": "Ursa Major Solar",
    "countryCode": "US",
    "creationDate": "2019-09-23T20:49:38.370Z",
    "etag": "8772fd1c59fed8313a6c1ad260544c116dc0af4bc13941957173244edba47d31",
    "firstName": "gwedolyn",
    "fullName": "gwedolyn richi RR",
    "jobTitle": "Actor",
    "lastModified": "2019-09-23T20:49:38.372Z",
    "lastName": "RR",
    "phone": "123-456-7890",
    "postalCode": "33122",
    "salutation": "Ms",
    "secondName": "richi",
    "stateCode": "GA"
  }
