#%RAML 1.0 NamedExample
value:
  {
    "limit": 2,
    "offset": 50,
    "query": {
        "textQuery": {
            "fields": [
                "credentials.login"
            ],
            "searchPhrase": "wleung"
        }
    }
  }