#%RAML 1.0 NamedExample
value:
  {
    "limit": 1,
    "hits": [
        {
            "creationDate": "2020-01-09T16:50:32.000Z",
            "description": "Big Spenders",
            "id": "Big Spenders",
            "inDeletion": false,
            "lastModified": "2020-01-09T16:50:32.000Z",
            "memberCount": 109,
            "rule": {
                "description": "Customers who spend more than $1000 in the last month"
            },
            "type": "dynamic"
        }
    ],
    "query": {
        "textQuery": {
            "fields": [
              "id"
            ],
            "searchPhrase": "Big"
        }
    },
    "offset": 0,
    "total": 1
  }