#%RAML 1.0 NamedExample
value:
  {
    "creationDate": "2019-09-23T19:46:07.412Z",
    "credentials": {
        "enabled": true,
        "locked": false,
        "login": "wleung"
    },
    "customerId": "adg2p1zObo8JDt3iXZCNIZBcai",
    "customerNo": "00005001",
    "lastModified": "2019-09-23T19:46:07.417Z",
    "lastName": "Leung"
  }
  