#%RAML 1.0 NamedExample
value:
  {
    "credentials": {
      "enabled": true,
      "locked": false,
      "login": "wleung",
      "passwordQuestion": ""
    },
    "lastName": "Leung",
    "customerNo": "00005002"
  }
  