#%RAML 1.0 NamedExample
value:
  {
    "credentials": {
      "enabled": true,
      "locked": false,
      "login": "RollerSkater2022",
      "passwordQuestion": ""
    },
    "lastName": "Smith",
    "customerNo": "00005002"
  }
  