#%RAML 1.0
title: Coupons
version: v1
protocols:
  - HTTPS
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/pricing/coupons/{version}
baseUriParameters:
  shortCode:
    description: A region-specific merchant identifier.
    example: 0dnz6oep
    pattern: ^([a-z0-9]+)(-[a-z0-9]+)*$ 

description: !include coupons-description.md
mediaType: application/json

uses:
  CouponTraits: coupons-traits-library.raml
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/api-standards.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.20/commerce-cloud-standards.raml

types:
  Coupon:
    description: Document representing a coupon.
    properties:
      couponId:
        description: The ID of the coupon.
        maxLength: 256
        minLength: 1
        type: string
        example: MyCoupon
      creationDate:
        description: Returns the value of attribute 'creationDate'.
        type: datetime
        example: 2019-10-20T12:00:00Z
        required: false
      description:
        description: The description of the coupon.
        maxLength: 4000
        type: string
        required: false
        example: |
          This coupon is used to give 10% off stuff.
      enabled:
        description: A flag indicating whether the coupon is enabled.
        type: boolean
        example: false
      exportedCodeCount:
        description: The number of coupon codes attached to the coupon that have been issued (request search only).
        type: integer
        format: int32
        example:
          0
        required: false
      lastModified:
        description: Returns the value of attribute 'lastModified'.
        type: datetime
        example: 2019-10-30T04:23:59Z
        required: false
      redemptionCount:
        description: The number of times the coupon has been redeemed (request search only).
        type: integer
        format: int32
        example: 3
        required: false
      redemptionLimits:
        description: The redemption limit per coupon code.
        type: RedemptionLimits
        required: false
        example:
            limitPerCode: 1
            limitPerCustomer: 1
            limitPerTimeFrame:
              limit: 2
              redemptionTimeFrame: 24
      singleCode:
        description: Single coupon code, only valid for Single Code type.
        maxLength: 256
        minLength: 1
        type: string
        required: false
        example: MyCode
      systemCodesConfig:
        description: The configuration of system coupon codes, including prefix and number of codes.
        type: CouponSystemCodeConfig
        required: false
        example:
          codePrefix: SG
          numberOfCodes: 500000
      totalCodesCount:
        description: The total number of coupon codes associated with this coupon.
        type: integer
        format: int32
        required: false
        example: 50
      type:
        description: The type of coupon code.
        type: string
        enum:
          - single_code
          - multiple_codes
          - system_codes
        example: single_code
  CouponCode:
    description: A coupon code with accompanying stats for redemptions and issues.
    properties:
      code:
        description: The code used to redeem the coupon.
        type: string
        example: MyCode
      issued:
        description: Flag indicating if the coupon code has been issued.
        type: boolean
        example: true
      redemptionCount:
        description: The count of the number of redemptions associated with the code.
        type: integer
        format: int32
        example: 1
  CouponCodes:
    description: Document representing a set of coupon codes.
    properties:
      limit?: ApiStandards.Limit
      data:
        description: The collection of coupon codes.
        type: array
        example: !include Examples/coupon_codes_data_example.raml
        items:
          type: CouponCode
      offset?: ApiStandards.Offset
      total:
        description: The total number of documents.
        type: integer
        format: int32
        example: 50
  CouponMultiCodesRequest:
    description: A request object to add and remove coupon codes from a document.
    properties:
      codes:
        description: The list of coupon codes to add or delete.
        type: array
        example: ["CodeA","CodeB"]
        items:
          type: string
  CouponSystemCodeConfig:
    properties:
      codePrefix:
        description: The code prefix for system-generated coupon codes.
        type: string
        example: "SG"
      numberOfCodes:
        description: The number of system coupon codes that can be issued.
        type: integer
        format: int32
        example: 50000
  RedemptionLimitPerPeriod:
    description: Document representing a coupon redemption limit.
    properties:
      limit:
        description: The limit on the number of times a coupon can be redeemed for a specified redemption time period.
        minimum: 0
        type: integer
        format: int32
        example: 1
      redemptionTimeFrame:
        description: The redemption time period.
        maximum: 999
        minimum: 0
        type: integer
        format: int32
        example: 24
  RedemptionLimits:
    description: Document representing a coupon.
    properties:
      limitPerCode:
        description: The redemption limit per code.
        minimum: 0
        type: integer
        format: int32
        example: 0
      limitPerCustomer:
        description: The redemption limit per customer.
        minimum: 0
        type: integer
        format: int32
        example: 0
      limitPerTimeFrame:
        description: The redemption limit per time frame.
        type: RedemptionLimitPerPeriod
        example:
          redemptionTimeFrame: 24
          limit: 1
  CouponRedemption:
    description: A redemption record returned from the coupon redemption resources.
    properties:
      code:
        description: The coupon code that was redeemed.
        type: string
      couponId:
        description: The coupon id that was redeemed.
        type: string
      creationDate:
        description: Date when the redemption was created.
        type: datetime
      customerEmail:
        description: The customer email that was used to redeem it.
        type: string
      orderNo:
        description: The order number where the redemption occurred.
        type: string
      viewOrderUrl:
        description: A URL able to access the order.
        type: string
  CouponSearchResult:
    description: Document representing a coupon search result.
    type: CommerceCloudStandards.PaginatedSearchResult
    properties:
      hits:
        description: The sorted array of coupon search hits. Can be empty.
        type: Coupon[]
  CouponRedemptionSearchResult:
    description: The result of the coupon redemption search.
    type: CommerceCloudStandards.PaginatedSearchResult
    properties:
      hits:
        description: The array of coupon redemption search hits. Can be empty.
        type: CouponRedemption[]

'/organizations/{organizationId}/coupons':
    type: CommerceCloudStandards.Organization
    is:
      - CommerceCloudStandards.SiteSpecific
    post:
      description: |-
        Searches for coupons.

         The Coupon Search document contains a search object that allows filtering on various attributes.

         The query attribute specifies a complex query that can be used to narrow down the search with the following searchable attributes:
         
        | Attribute | Type |
        |-----------|--------|
        | couponId| String |
        | description | String |
        | type | one of {"single_code", "multiple_codes", "system_codes"} |
        | enabled | Boolean |        

         Note that only searchable attributes can be used in sorting.         
      displayName: couponsSearch
      is:
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:
            responseStatus: 400
      responses:
        '200':
          description: API executed Successfully.
          body:
            application/json:
              type: CouponSearchResult
        '400':
          description: Thrown if the query is ill-formed.
      body:
        application/json:
          type: CommerceCloudStandards.SearchRequest
      securedBy:
        - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
        - CommerceCloudStandards.AmOAuth2
    '/redemptions':
      is:
        - CommerceCloudStandards.SiteSpecific
      post:
        description: |-
          Searches for coupon redemptions.
          
          The Coupon Redemption Search document contains a search object that allows filtering on various attributes.
          

          The query attribute specifies a complex query that can be used to narrow down the search with the following searchable attributes:
          
            | Attribute | Type |
            |-----------|--------|
            | code| String |
            | couponId | String |
            | customerEmail | String |
            | orderNo | String |

          Note that only searchable attributes can be used in sorting.

          If the user role does not have the `View_Coupon_Codes` permission, then the coupon codes returned are masked.
        displayName: couponRedemptionsSearch
        is:
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
        responses:
          '200':
            description: API executed Successfully.
            body:
              application/json:
                type: CouponRedemptionSearchResult
          '400':
            description: Thrown if the query is ill-formed.
        body:
          application/json:
            type: CommerceCloudStandards.SearchRequest
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
          - CommerceCloudStandards.AmOAuth2
    '/{couponId}':
      is:
        - CommerceCloudStandards.SiteSpecific
      delete:
        description: Delete a coupon by ID.
        displayName: deleteCoupon
        is:
        - ApiStandards.RateLimited:
            responseStatus: 204
        responses:
          '204':
            description: API returned successfully.
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
          - CommerceCloudStandards.AmOAuth2
      get:
        description: |-
          Returns coupon information for the given coupon ID.
           If the user role does not have the View_Coupon_Codes permission, then the coupon codes returned are masked.
        displayName: getCoupon
        is:
          - CouponTraits.CouponNotFound
          - ApiStandards.RateLimited:
              responseStatus: 200
          - ApiStandards.RateLimited:    
              responseStatus: 404
        responses:
          '200':
            description: API returned successfully.
            body:
              application/json:
                type: Coupon
                example: !include Examples/put_sites_siteid_coupons_couponid.raml
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
          - CommerceCloudStandards.AmOAuth2
      patch:
        description: Updates the coupon with the specified information.
        displayName: updateCoupon
        is:
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
        - ApiStandards.RateLimited:    
            responseStatus: 403
        responses:
          '200':
            description: API returned successfully.
            body:
              application/json:
                type: Coupon
                example: !include Examples/put_sites_siteid_coupons_couponid.raml
          '400':
            description: |-
              Thrown if you try to update certain fields in a coupon after
                            redeeming it, exporting it, if the code provided is in use by another coupon, or whenever a quota regarding system-generated coupons is violated.
            body:
              application/json:
                type: ApiStandards.ErrorResponse
                example: !include Examples/patch_sites_siteid_coupons_couponid_400.raml
          '403':
            description: Thrown when trying to update a broken coupon that should be deleted and re-created, or when trying to update a legacy coupon.
            body:
              application/json:
                type: ApiStandards.ErrorResponse
                example: !include Examples/patch_sites_siteid_coupons_couponid_403.raml
        body:
          application/json:
            type: Coupon
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
          - CommerceCloudStandards.AmOAuth2
      put:
        description: |-
          Creates a coupon using the information provided. If a coupon exists with the same unique identifier,
           the coupon is replaced completely.
        displayName: createCoupon
        is:
        - ApiStandards.RateLimited:
            responseStatus: 200
        - ApiStandards.RateLimited:    
            responseStatus: 400
        - ApiStandards.RateLimited:    
            responseStatus: 403
        responses:
          '200':
            description: API returned successfully.
            body:
              application/json:
                type: Coupon
                example: !include Examples/put_sites_siteid_coupons_couponid.raml
          '400':
            description: |-
              Thrown if the coupon passed in is not valid (the argument indicates
                            the field that was invalid), if the code provided is in use by another coupon, if a single code coupon does not set the coupon code properly, if the ID in request is not the same as the ID in document, or whenever a quota regarding system-generated coupons is violated.
            body:
              application/json:
                type: ApiStandards.ErrorResponse
                example: !include Examples/put_sites_siteid_coupons_couponid_400.raml
          '403':
            description: Thrown if the resource requires global instead of site-specific context.
            body:
              application/json:
                type: ApiStandards.ErrorResponse
                example: !include Examples/put_sites_siteid_coupons_couponid_403.raml
        body:
          application/json:
            type: Coupon
        securedBy:
          - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
          - CommerceCloudStandards.AmOAuth2
      uriParameters:
        couponId:
          description: The ID of the coupon to create.
          minLength: 1
          type: string
          example: MyCoupon
      '/codes':
        is:
          - CommerceCloudStandards.SiteSpecific
        get:
          description: |-
            Get the coupon codes for the given coupon.

             If the user role does not have the View_Coupon_Codes permission, then the coupon codes returned are masked.
          displayName: getCouponCodes
          is:
            - CouponTraits.CouponNotFound
            - ApiStandards.OffsetPaginated:
                maxLimit: 200
                defaultSize: 25
            - ApiStandards.RateLimited:
                responseStatus: 200
            - ApiStandards.RateLimited:    
                responseStatus: 404
          responses:
            '200':
              description: API returned successfully.
              body:
                application/json:
                  type: CouponCodes
                  example: !include Examples/get_sites_siteid_coupons_couponid_codes.raml
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions, sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2
        post:
          description: Add or delete (modify) multiple codes to and from the supplied coupon.
          displayName: updateCouponCodes
          is:
            - CouponTraits.CouponNotFound
            - ApiStandards.RateLimited:
                responseStatus: 204
            - ApiStandards.RateLimited:    
                responseStatus: 400
            - ApiStandards.RateLimited:    
                responseStatus: 404
          responses:
            '204':
              description: API returned successfully.
            '400':
              description: Thrown if the coupon code could not be created.
              body:
                application/json:
                  type: ApiStandards.ErrorResponse
                  example: !include Examples/post_sites_siteid_coupons_couponid_codes_400.raml
          queryParameters:
            delete:
              description: Pass as true to delete the passed codes.
              type: boolean
              default: false
              required: false
              example: true
          body:
            application/json:
              type: CouponMultiCodesRequest
          securedBy:
            - CommerceCloudStandards.BearerToken: { scopes: [ sfcc.promotions.rw ] }
            - CommerceCloudStandards.AmOAuth2