#%RAML 1.0 NamedExample
put-promotion-response:
  {
    "archived": false,
    "assignmentInformation": {
      "active": false,
      "enabled": true,
      "scheduleType": "none"
    },
    "creationDate": "2020-01-13T20:22:09.189Z",
    "disableGloballyExcluded": false,
    "enabled": true,
    "exclusivity": "class",
    "id": "my-promotion",
    "lastModified": "2020-01-13T20:22:09.199Z",
    "name": {
      "default": "__PROMOTION_ID__"
    },
    "promotionClass": "order"
  }