#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Data Source Code Group API.
responses:
  404:
    description: |
            Thrown in case the source code group does not exist matching the given ID.
    body:
      application/json:
        type: ApiStandards.ErrorResponse
        example: |
          {
            "type": "SourceCodeGroupNotFoundException",
            "title": "No source code group with ID 'foo' for site 'SiteGenesis' could be found.",
            "instance": "/sites/SiteGenesis/source_code_groups/foo"
          }