#%RAML 1.0 NamedExample
value:
  [
    {
      "amount": {
        "currencyMnemonic": "USD",
        "value": 1000.00
      },
      "balance": {
        "currencyMnemonic": "USD",
        "value": 1000.00
      },
      "creationDate": "2020-01-10T21:31:49.242Z",
      "description": "my-test-description",
      "enabled": false,
      "lastModified": "2020-01-10T21:31:49.246Z",
      "maskedGiftCertificateCode": "************KHAL",
      "merchantId": "00001001",
      "message": "my-test-message",
      "orderNo": "my-test-order_no",
      "recipientEmail": "test@gmail.com",
      "recipientName": "my-test-recipient_name",
      "senderName": "my-test-sender_name",
      "status": "issued",
      "transactions": [
        {
          "amount": {
            "currencyMnemonic": "USD",
            "value": 1000.00
          },
          "orderNo": "my-test-order_no",
          "timestamp": "2020-01-10T21:31:49.244Z",
          "typeCode": "create"
        }
      ]
    }
  ]