#%RAML 1.0 Trait

usage: This trait allows for taking in an input header containing the tenant-tier.

headers:
  tenant-tier?:
    description: Header defining the tenant tier for NFR limits.
    type: string
    maxLength: 256
    example: internal-large-catalog