ignores:
  [
    '@types/chai',
    'chai',
    'depcheck',
    'eslint*',
    'gulp-typescript',
    'mocha',
    'nyc',
    'prettier',
    'tslib',
    'typescript',
    'typedoc-plugin-external-module-map',
    'utility-types',
  ]
