#%RAML 1.0 NamedExample
value:
  {
    "description": "Rate limit /path1",
    "expression": "http.request.uri.path matches \"^/path1/.*\"",
    "characteristics": ["cf.unique_visitor_id"],
    "action": "block",
    "period": 60,
    "requestsPerPeriod": 50,
    "mitigationTimeout": 600,
    "countingExpression": "http.request.uri.path matches \"^/path1/.*\" and http.response.code eq 400",
    "enabled": false,
    "position": {
        "before": "2c0fc9fa937b11eaa1b71c4d701ab86e"
    }
}