#%RAML 1.0 NamedExample
{
  "active": false,
  "activeRedirect": {
      "location": "urlString",
      "locationType": "url"
  },
  "creationDate": "2019-11-25T15:24:25.317Z",
  "description": "description for source code group test2",
  "enabled": false,
  "endTime": "2030-10-01T00:00:00.000Z",
  "id": "20% off (£30) New Customer",
  "inactiveRedirect": {
      "location": "urlString",
      "locationType": "url"
  },
  "lastModified": "2019-11-25T15:28:55.175Z",
  "startTime": "2014-10-01T00:00:00.000Z"
}