#%RAML 1.0 NamedExample
value:
  {
    "limit": 0,
    "offset": 50,
    "query": {
        "textQuery": {
            "fields": [
                "credentials.login"
            ],
            "searchPhrase": "GwennyStrah3661"
        }
    }
  }