#%RAML 1.0 NamedExample
value:
  {
    "limit": 4,
    "hits": [
        {
            "id": "Big Spenders"
        },
        {
            "id": "Everyone"
        },
        {
            "id": "Registered"
        },
        {
            "id": "Unregistered"
        }
    ],
    "query": [{
        "matchAllQuery": {
            "type": "matchAllQuery"
        }
    }],
    "offset": 0,
    "total": 4
  }