#%RAML 1.0 NamedExample
value:
  {
    "version": "v1",
    "creationDate": "2019-09-11T20:52:33.000Z",
    "id": "Small Spenders",
    "description": "Customer's who spent less than $200 in the last month",
    "lastModified": "2019-09-11T22:46:50.000Z",
    "rule": {
        "conditionListLink": "",
        "description": "Customers with customer attribute 'Order Value (30 Days)' < '200.00'"
    },
    "type": "dynamic"
  }