#%RAML 1.0 NamedExample
value:
  {
    "version": "v1",
    "id": "customerGroups",
    "limit": 8,
    "data": [
        {
            "id": "Big Spenders"
        },
        {
            "id": "Customer Group"
        },
        {
            "id": "Customer Group with Members"
        },
        {
            "id": "Everyone"
        },
        {
            "id": "Medium Spenders"
        },
        {
            "id": "Registered"
        },
        {
            "id": "Small Spenders"
        },
        {
            "id": "Unregistered"
        }
    ],
    "offset": 0,
    "total": 8
  }
