#%RAML 1.0 NamedExample
value:
  {
    "customerNo": "D00000001",
    "login": "testuser1@demandware.com",
    "firstName": "Test1",
    "lastName": "User1",
    "active": true,
    "customerLink": ""
  }