#%RAML 1.0 NamedExample
value:
  {
    "limit": 3,
    "data": [
        {
            "customerNo": "D00000001",
            "login": "testuser1@demandware.com",
            "firstName": "Test1",
            "lastName": "User1",
            "email": "testuser1@demandware.com",
            "active": true
        },
        {
            "customerNo": "D00000002",
            "login": "testuser2@demandware.com",
            "firstName": "Test2",
            "lastName": "User2",
            "email": "testuser2@demandware.com",
            "active": true
        },
        {
            "customerNo": "D00000003",
            "login": "testuser3@demandware.com",
            "firstName": "Test3",
            "lastName": "User3",
            "email": "testuser3@demandware.com",
            "active": true
        }
    ],
    "offset": 0,
    "total": 3
  }