#%RAML 1.0 NamedExample
value:
  {
      "query" : {
          "termQuery": {
              "fields": ["active"],
              "operator": "is",
              "values": [true]
          }
      }
  }