#%RAML 1.0 NamedExample
value:
  {
  "limit" : 1,
   "hits" : 
   [
      {
         "customerNo" : "0001",
         "login" : "test_customer",
         "firstName" : "Robin",
         "lastName" : "Hood",
         "email" : "rhood@example.com",
         "active" : true
      }
   ],
   "query" : 
   [
    {
        "termQuery" : 
        {
          "fields" : 
          [
              "active"
          ],
          "operator" : "is",
          "values" : 
          [
              true
          ]
        }
    }
   ],
   "offset" : 0,
   "total" : 1
}