#%RAML 1.0 NamedExample
#title: catalogcategoryprdAssignment-example
value:
  {
    "catalogId": "apparel-catalog",
    "categoryId": "kids-wear",
    "owningCatalogName": {
        "default": "Electronics Master Catalog"
    },
    "position": 1.0,
    "productId": "apple-ipod-shuffle",
    "productName": {
        "default": "Apple iPod Shuffle"
    }
}