#%RAML 1.0 NamedExample
value:
  {
      "limit": 2,
      "data": [
        {
          "productId": "red-shirt"
        },
        {
          "productId": "blue-shirt"
        }
      ],
      "total" :2
  }