#%RAML 1.0 NamedExample
value:
  {
    "id": "VHRule",
    "enabled": true,
    "exclusion": false,
    "categorizationLocaleId": "en-US",
    "categorizationClassificationFlag": true,
    "categorizationPrimaryFlag": true,
    "conditions": [
        {
            "id": "NameCondition",
            "attributeKey": "name",
            "attributeValue": ["Shirt"],
            "attributeName": "name", 
            "operator": "startsWith"
        },
        {
            "id": "BrandCondition",
            "attributeKey": "brand",
            "attributeName": "brand", 
            "attributeValue": ["Van Heusen"],
            "operator": "equals"
        }
      ]
  }