#%RAML 1.0 NamedExample
value:
  {
  "data":
  [
        {
          "id": "VHRule",
          "enabled": true,
          "exclusion": false,
          "categorizationLocaleId": "en-US",
          "categorizationClassificationFlag": true,
          "categorizationPrimaryFlag": true,
          "conditions": [
            {
               "id": "NameCondition",
               "attributeKey": "name",
               "attributeValue": ["Shirt"],
               "operator": "starts_with"
            },
            {
               "id": "BrandCondition",
               "attributeKey": "brand",
               "attributeValue": ["Van Heusen"],
               "operator": "equals"
            }
         ]
        },
        {
          "id": "DXRule",
          "enabled": true,
          "exclusion": false,
          "categorizationLocaleId": "en-US",
          "categorizationClassificationFlag": true,
          "categorizationPrimaryFlag": true,
          "conditions": [
            {
               "id": "NameCondition",
               "attributeKey": "name",
               "attributeValue": ["Shirt"],
               "operator": "starts_with"
            },
            {
               "id": "BrandCondition",
               "attributeKey": "brand",
               "attributeValue": ["DX"],
               "operator": "equals"
            }
          ]
        }
      ]
  }