#%RAML 1.0 NamedExample
#title: product-assignment-body-example
value:
  {
    "offset": 0,
    "limit": 50,
    "query": {
        "boolQuery": {
            "should": [
                {
                    "textQuery": {
                        "searchPhrase": "Jacket",
                        "fields": [
                            "product_name"
                        ]
                    }
                }
            ]
        }
    },
    "select": "(hits.(catalog_id,category_id,link,owning_catalog_name,product_id,product_name,position,normalized_position,product.(image,display_name,type)),count,start,total)",
    "expand": [
        "product_images",
        "normalized_positions"
    ]
  }