#%RAML 1.0 NamedExample
#title: product-assignment-body-example
value:
  {
    "offset": 0,
    "limit": 50,
    "query": {
        "boolQuery": {
            "should": [
                {
                    "textQuery": {
                        "searchPhrase": "Jacket",
                        "fields": [
                            "productName"
                        ]
                    }
                }
            ]
        }
    }
  }