#%RAML 1.0 Library

types:
  ErrorCodeTypesEnum:
    type: ErrorCodesEnum
  InvalidRequestParameterOrLocationDoesNotExist:
    enum: [InvalidRequestParameter, LocationDoesNotExist]
    type: string
    example: InvalidRequestParameter

  InvalidRequestParameterOrLocOrGroupDoesNotExist:
    enum: [InvalidRequestParameter, LocationDoesNotExist, GroupDoesNotExist]
    type: string
    example: GroupDoesNotExist
  
  InvalidRequestParameterOrExpiredDeltaLink:
    enum: [InvalidRequestParameter, ExpiredDeltaLink]
    type: string
    example: ExpiredDeltaLink

  InvalidRequestParameterLocDoesNotExistEntityAlreadyExistsOrEntityNotFound:
    enum: [InvalidRequestParameter, LocationDoesNotExist, EntityAlreadyExists, EntityNotFound]
    type: string
    example: EntityNotFound

  InvalidRequestParameterLocDoesNotExistOrEntityNotFound:
    enum: [InvalidRequestParameter, LocationDoesNotExist, EntityNotFound]
    type: string
    example: EntityNotFound

  InvalidRequestParameter:
    enum: [InvalidRequestParameter]
    type: string
    example: InvalidRequestParameter

  ExpiredDeltaLinkEnum:
    enum: [ExpiredDeltaLink]
    type: string
    example: ExpiredDeltaLink
  
  EntityNotFoundEnum:
    enum: [EntityNotFound]
    type: string
    example: EntityNotFound

  ErrorCodesEnum:
    enum:
      - InsufficientQuantity
      - DuplicateGroupId
      - InvalidGroupId
      - DuplicateSku
      - MissingParameter
      - InvalidRequest
      - InvalidRequestParameter
      - EntityAlreadyExists
      - PositiveQuantityRequired
      - ReservationInUnknownState
      - ReservationInvalidState
      - ReservationCancelled
      - EntityNotFound
      - ReservationCancellationFailed
      - ExportInProcess
      - ExportProcessFailed
      - Unknown
      - DuplicateEventId
      - ReservationOperationInProcess
      - ConcurrentModification
      - GroupDoesNotExist
      - OnlyOneLocationSupported
      - NotAppliedDueToAtomicFailure
      - ImportInProgress
      - ExpiredDeltaLink
      - InventoryReset
      - UnableToStartExport
      - ResourceNotFound
      - LocationListMustNotBeEmpty
      - SeeOtherResource
      - TenantNotProvisioned
      - ReservationAlreadyFinalized
      - MismatchedGroupAndLocation
      - GroupMustNotBeEmpty
      - LocationListTooLarge
      - ExpiredUploadLink
      - ExpiredResultLink
      - FileAlreadyReceived
      - IllegalGroupState
      - DeleteTenantNotAllowed
      - TenantResetInProgress
      - LocationDoesNotExist
      - LocationNotInGroup
      - PreviousRequestAborted
      - PreviousRequestCancelled
      - DuplicateLocationId
    type: string
    example: InsufficientQuantity
