openapi: 3.0.3
info:
  title: Shopper SEO
  version: v1
  description: |-
    # API Overview

    The Shopper SEO API Provides access to SEO-related information, such as URL mapping information.

    ## Authentication & Authorization

    The Shopper SEO API requires a shopper access token from the [Shopper Login and API Access Service (SLAS).](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-shopper-apis.html)

    You must include the relevant scope(s) in the client ID used to generate the SLAS token. For details, see [Authorization Scopes Catalog.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/auth-z-scope-catalog.html)

    ## Use Cases

    ### URL Resolution

    For information on setting up URL rules and URL redirects in Business Manager, see [URL Resolution.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/url-resolution.html)

    ### Caching

    Caching capabilities are available for the Shopper SEO API. For details, see [Server-Side Web-Tier Caching.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/server-side-web-tier-caching.html)

    ### Using Hooks

    For details working with hooks, see [Extensibility with Hooks.](https://developer.salesforce.com/docs/commerce/commerce-api/guide/extensibility_via_hooks.html)
servers:
  - url: https://{shortCode}.api.commercecloud.salesforce.com/site/shopper-seo/v1
    variables:
      shortCode:
        default: shortCode
paths:
  /organizations/{organizationId}/url-mapping:
    get:
      summary: Get URL mapping information for a URL segment.
      description: "The mapping information is based on URL rules and redirects that are set up in Business Manager. \nFor more information about prerequisites and sample usage, see [URL Resolution](/docs/commerce/commerce-api/guide/url-resolution.html). \nYou can customize the behavior of this endpoint by using hooks. For details, refer to the [Hook List](https://developer.salesforce.com/docs/commerce/commerce-api/guide/hook_list.html)."
      operationId: getUrlMapping
      parameters:
        - $ref: '#/components/parameters/organizationId'
        - $ref: '#/components/parameters/urlSegment'
        - $ref: '#/components/parameters/siteId'
        - $ref: '#/components/parameters/locale'
      responses:
        '200':
          description: Returns URL mapping information for a URL that a shopper entered or selected.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlMapping'
              examples:
                UrlMapping:
                  $ref: '#/components/examples/UrlMapping'
        '400':
          description: 'The locale is invalid. Make sure you provide a locale using the correct format: ISO 639-1 for the language code and ISO 3166-1 for the country code. For example, en-US.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getUrlMapping400:
                  $ref: '#/components/examples/getUrlMapping400'
        '401':
          description: The user making the call isn't authorized to make this request. For example, the correct scope wasn't added to an SLAS API Client or the access token is invalid or missing.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getUrlMapping401:
                  $ref: '#/components/examples/getUrlMapping401'
        '404':
          description: No mapping information for the requested URL exists because there's no corresponding URL rule in Business Manager.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                getUrlMapping404:
                  $ref: '#/components/examples/getUrlMapping404'
      security:
        - ShopperToken:
            - sfcc.shopper-seo
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      description: "ShopperToken authentication follows the authorization code grant flow, as defined by the OAuth 2.1 standard. Depending on the type of OAuth client (public or private), this authorization flow has further requirements. \nFor a detailed description of the authorization flow, see the [SLAS overview](https://developer.salesforce.com/docs/commerce/commerce-api/references?meta=shopper-login:Summary).\nA shopper token allows you to access the Shopper API endpoints of both Open Commerce API and the B2C Commerce API. These endpoints can be used to build headless storefronts and other applications.\nThe `ShopperToken` security scheme is a parent of other security schemes, such as `ShopperTokenTsob`. A Shopper API endpoint can require a specific child scheme (`ShopperTokenTsob`, for example) that cannot be accessed with a regular shopper token.\n"
      flows:
        clientCredentials:
          tokenUrl: https://{shortCode}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-seo: Allows read operations on shopper seo.
        authorizationCode:
          authorizationUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/authorize
          tokenUrl: https://{short-code}.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/{organizationId}/oauth2/token
          scopes:
            sfcc.shopper-seo: Allows read operations on shopper seo.
  schemas:
    OrganizationId:
      description: An identifier for the organization the request is being made by
      example: f_ecom_zzxy_prd
      type: string
      minLength: 1
      maxLength: 32
    SiteId:
      minLength: 1
      maxLength: 32
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
      example: RefArch
      type: string
    LanguageCountry:
      pattern: ^[a-z][a-z]-[A-Z][A-Z]$
      description: A concatenated version of the standard Language and Country codes, combined with a hyphen '`-`'.
      example: en-US
      type: string
    LanguageCode:
      pattern: ^[a-z][a-z]$
      description: A two letter lowercase language code conforming to the [ISO 639-1](https://www.iso.org/iso-639-language-codes.html) standard. Additionally, this may be used to submit requests with the header parameter `Accept-Language`, following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766).
      example: en
      type: string
    DefaultFallback:
      default: default
      description: A specialized value indicating the system default values for locales.
      example: default
      enum:
        - default
      type: string
    LocaleCode:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      oneOf:
        - $ref: '#/components/schemas/LanguageCountry'
        - $ref: '#/components/schemas/LanguageCode'
        - $ref: '#/components/schemas/DefaultFallback'
    String256:
      type: string
      maxLength: 256
      description: "The String256 schema is a foundational schema designed for fields or attributes that are stored in a database field with a maximum capacity of 256 bytes. \nThis schema accommodates various character sets, with the following considerations:\n  - ASCII Characters: Each ASCII character occupies 1 byte, allowing up to 256 characters.\n  - Latin Characters: Many Latin characters require 2 bytes each, allowing up to 128 characters.\n  - Asian Characters: Many Asian characters require 3 bytes each, allowing approximately 85 characters."
      example: Max Mustermann
    UrlMapping:
      description: The URL mapping information for a URL that a shopper clicked or typed in.
      type: object
      properties:
        resourceType:
          minLength: 1
          allOf:
            - $ref: '#/components/schemas/String256'
          description: "The type of resource that corresponds to the requested URL. If you set up a URL redirect in Business Manager, \nresourceType returns the corresponding destination type value from the redirect. If there's a URI redirect, resourceType isn't returned. \nThe URL redirect feature is available from B2C Commerce version 24.3."
          enum:
            - CATEGORY
            - PRODUCT
            - CONTENT_ASSET
          example: CATEGORY
        resourceSubType:
          minLength: 1
          allOf:
            - $ref: '#/components/schemas/String256'
          description: "If the resourceType is CONTENT_ASSET, this field tells you whether the resource is a standard content asset or a Page Designer content asset. \nThis output is available from B2C Commerce version 24.2."
          enum:
            - STANDARD_CONTENT_ASSET
            - PAGE_DESIGNER_CONTENT_ASSET
          example: STANDARD_CONTENT_ASSET
        resourceId:
          minLength: 1
          allOf:
            - $ref: '#/components/schemas/String256'
          description: "The identifier for the resource that corresponds to the requested URL. If you set up a URL redirect in Business Manager, \nresourceId returns the corresponding destination ID value from the redirect. \nIf there's a URI redirect, resourceId isn't returned. The URL redirect feature is available from B2C Commerce version 24.3."
          example: mens-clothing-shorts
        refinements:
          description: "The refinement filters that correspond to the URL and resourceType. \nRefinements are returned only if all of these conditions are met - a) the resourceType is CATEGORY, b) refinements are included in the urlSegment, and c) the refinements are configured in Business Manager. \nThis field returns a key-value pair of refinement name and refinement value. If there’s a matching URL redirect for the requested URL. the refinements output isn’t returned.\nThe URL redirect feature is available from B2C Commerce version 24.3."
          type: object
          additionalProperties: true
        statusCode:
          format: int32
          description: "This field is populated only if you set up a URL redirect in Business Manager. It specifies whether the redirect is temporary (302 or 307) or permanent (301). \nSee [Create a Redirect from a B2C Commerce URL.](https://help.salesforce.com/s/articleView?id=cc.b2c_creating_a_redirect_from_a_digital_url.htm&type=5) \nThis parameter is available from B2C Commerce version 24.3."
          type: integer
          example: 301
        destinationUrl:
          minLength: 1
          maxLength: 2048
          description: "This field is populated if the urlSegment resolves to a redirect. Specifies the URL you want to redirect to as an absolute or relative URL. \nThe destinationUrl is based on your configuration in Business Manager. It's either a calculated value indicating the Commerce Cloud object (product, category, or content asset) URL or your specified URL. \nNote that an object's path may not necessarily match your headless storefront URLs but can be used as a reference for calculating the destinationUrl. \nSee [Create a Redirect from a B2C Commerce URL.](https://help.salesforce.com/s/articleView?id=cc.b2c_creating_a_redirect_from_a_digital_url.htm&type=5). \nAvailable from B2C Commerce 24.3."
          type: string
          example: mens/clothing/shorts
        copySourceParams:
          description: "This field is populated only if you set up a URL redirect in Business Manager. \nIt’s a flag that shows whether the parameters of the source URL have been copied to the destination URL. \nThis parameter is available from B2C Commerce version 24.3."
          type: boolean
          example: true
        additionalUrlParams:
          minLength: 1
          maxLength: 2048
          description: "This field is populated only if you set up a URL redirect in Business Manager. \nIt returns the parameters you want to add to the end of the URL. \nThis parameter is available from B2C Commerce version 24.3."
          type: string
          example: '&cgid=womens-accessories-scarves&prefn1=displaySize'
        productCategoryId:
          minLength: 1
          allOf:
            - $ref: '#/components/schemas/String256'
          description: "This field is populated only if you set up a URL redirect in Business Manager. \nIt identifies the destination product's category ID. This field is returned only when the destination type is product. \nThis parameter is available from B2C Commerce version 24.3."
    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        title:
          description: "A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n"
          type: string
          maxLength: 256
          example: You do not have enough credit
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank". It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: NotEnoughMoney
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Your current balance is 30, but that costs 50
        instance:
          description: |
            A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced.  It accepts relative URIs; this means
            that they must be resolved relative to the document's base URI, as
            per [RFC3986], Section 5.
          type: string
          maxLength: 2048
          example: /account/12345/msgs/abc
      required:
        - title
        - type
        - detail
  parameters:
    organizationId:
      description: An identifier for the organization the request is being made by
      name: organizationId
      in: path
      required: true
      example: f_ecom_zzxy_prd
      schema:
        $ref: '#/components/schemas/OrganizationId'
    urlSegment:
      name: urlSegment
      in: query
      description: "The part of the requested URL that comes after the domain name. For example, the urlSegment for \\\"www.abc.com/blue/new-arrivals/tops\\\" is \\\"blue/new-arrivals/tops\\\". \nThere's no limit on the length of the urlSegment. However, for this endpoint, the maximum allowed length of the URL (after URL encoding) is 2047 characters. \nMake this field URL-encoded so that it properly handles special values such as whitespace. If a urlSegment includes a query string, a 404 error code is returned."
      required: true
      schema:
        minLength: 1
        type: string
        maxLength: 2047
        example: mens/clothing/shorts
    siteId:
      description: The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites.
      name: siteId
      in: query
      required: true
      examples:
        SiteId:
          value: RefArch
      schema:
        $ref: '#/components/schemas/SiteId'
    locale:
      description: A descriptor for a geographical region by both a language and country code. By combining these two, regional differences in a language can be addressed, such as with the request header parameter `Accept-Language` following [RFC 2616](https://tools.ietf.org/html/rfc2616) & [RFC 1766](https://tools.ietf.org/html/rfc1766). This can also just refer to a language code, also RFC 2616/1766 compliant, as a default if there is no specific match for a country. Finally, can also be used to define default behavior if there is no locale specified.
      name: locale
      in: query
      examples:
        LanguageCountry:
          value: en-US
        CountryCode:
          value: US
      schema:
        $ref: '#/components/schemas/LocaleCode'
  examples:
    UrlMapping:
      value:
        resourceType: CATEGORY
        resourceId: new-arrivals-tops
        refinements:
          refinementColor: Blue
    getUrlMapping400:
      value:
        title: Unknown Locale
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unknown-locale
        detail: The locale 'ab-CD' is unknown.
        locale: ab-CD
    getUrlMapping401:
      value:
        title: Invalid Access Token
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-access-token
        detail: The request is unauthorized, the access token is invalid.
        accessToken: hbGciOiJIUzI1NiIsInR5cCI6Ikp
    getUrlMapping404:
      value:
        title: Seo Url Mapping Not Found
        type: https://api.commercecloud.salesforce.com/documentation/error/v1/errors/seo-url-mapping-not-found
        detail: black/mens/accessories/luggage
        urlSegment: black/mens/accessories/luggage
        locale: en_US
