#%RAML 1.0 DataType

description: The file upload and validation status.
enum: 
  - WAITING 
  - VALIDATING 
  - SUCCESS 
  - HASH_FAILURE 
  - TRANSFER_FAILURE 
  - FILE_FORMAT_FAILURE
  - FILE_SIZE_LIMIT_FAILURE
example: SUCCESS
