#%RAML 1.0 DataType

description: The ingestion process action to be executed. The REPLACE will overwrite any existing data if a collision occurs.
type:
  enum: 
  - REPLACE
  - MERGE_AND_CREATE
  - MERGE_IF_EXISTS
example: REPLACE