#%RAML 1.0 Library
types:
  PlaceType: !include ../../types/PlaceType.raml
  
  Response200:
    description: Successful request for location or group type
    properties:
      type: 
        type: PlaceType
        required: false
