#%RAML 1.0 DataType
type: object
description: Request for doing a cache purge
properties:
  path:
    type: string
    description: Path for clearing the cache.
    example: www.sfcc-ecdn-test5.net/dw/shop/v21_9/products 