#%RAML 1.0 DataType
description: Certificate request information
type: object
properties:
  hostname:
    description: Hostname that certificate needs to be applied to.
    type: string
  certificateType:
    description: Indicates certificate is custom or automatic certificate renewal by eCDN. Optional field, if nothing specified the default value is custom. Valid values are custom or automatic.
    type: string
    required: false
  certificate:
    description: Public key of the custom certificate. Required if the certificateType value is custom.
    type: string
    required: false
  privateKey:
    description: Private key associated with the custom certificate. Required if the `certificateType` value is custom.
    type: string
    required: false
  certificateAuthority:
    description: Certificate authority only for automatic certificate renewal by eCDN. Required if the `certificateType` value is automatic. Valid values are `google` or `lets_encrypt`.
    type: string
    required: false
  certificateValidation:
    description: Certificate validation type is optional only for `certificateType` automatic, default value is `http`. Valid values are `http` or `txt`.
    type: string
    required: false
