#%RAML 1.0 DataType
description: Update the order of all existing custom rules.
type: object 
properties:
  ruleIds:
    description: An array of ruleIds representing the new order of custom rules.
    type: string[]
    example: ["ffffe61cf25e4ec49c34b029ff3060f7", "2c0fc9fa937b11eaa1b71c4d701ab86e"]