#%RAML 1.0 DataType
description: eCDN automatic renewal certificate DCV delegation records.
type: object
properties:
  dcvCname:
    description: DNS CNAME for Domain Control Validation.
    type: string
    required: false
  dcvCnameValue:
    description: DNS CNAME value for Domain Control Validation.
    type: string
    required: false