#%RAML 1.0 DataType
description: Request for update Logpush job
type: object
properties:
  enabled:
    description: Flag that indicates if the job is enabled or disabled.
    type: boolean
    example: true
    required: true