#%RAML 1.0 DataType
description: POST response for created new Logpush Ownership.
type: object
properties:
  data:
    description: The customer's new Logpush Ownership.
    type: object
    properties:
      destinationPath:
        description: Destination where logs will be sent (S3 bucket only).
        type: string
        example: s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256
      fileName:
        description: File path where the ownership challenge file is written.
        type: string
        example: site-name/20230101/ownership-challenge-d12345678.txt