#%RAML 1.0 DataType
description: Request for create Logpush job.
type: object
properties:
  destinationPath:
    description: Uniquely identifies s3 bucket for logs. Additional configuration parameters like region can be included. The string {DATE} in the URL path to separate logs into daily subdirectories; for example `s3://customer-bucket/logs/{DATE}?region=us-east-1&sse=AES256` The name of the directory will be replaced with the date in YYYYMMDD format (e.g. 20220215) when the logs are stored.
    type: string
    example: s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256
    required: true
  name:
    description: Logpush job name; the name cannot be changed after the job is created.
    pattern: ^[a-zA-Z0-9\-\.]*$
    type: string
    example: my-logpush-job
    required: true
  filter:
    description: Filter provides a way to customize which logs you want to receive. Filters are added as escaped JSON strings formatted. Default will include all logs.
    type: string
    required: false
  logFields:
    description: List of log fields. Depending on the type of log, the list of fields that you would like to see in the logs may vary.
    type: array
    items: string
    example: ["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"]
    required: true
  ownershipChallengeToken:
    description: Ownership token to proves the ownership of the destinationPath.
    type: string
    example: abc00000000000000000000
    required: true
  logType:
    description: Type of logs. Available log types are `http_requests` and `firewall_events`.
    type: string
    enum: ["http_requests", "firewall_events"]
    example: http_requests
    required: true
