#%RAML 1.0 DataType
description: POST request for creating new Logpush Ownership.
type: object
properties:
  destinationPath:
    description: Uniquely identifies a resource (such as an s3 bucket) where data will be pushed. Additional configuration parameters supported by the destination may be included. You can use the special string {DATE} in the URL path to separate logs into daily subdirectories; for example s3://customer-bucket/logs/{DATE}?region=us-east-1&sse=AES256. The name of the directory will be replaced with the date in YYYYMMDD format (e.g. 20220215) when the logs are stored.
    type: string
    example: s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256
    required: true