#%RAML 1.0 DataType
description: An MRT ruleset. Defines a list of MRT rules that will route certain storefront requests to the managed runtime instance.
type: object
properties:
  id:
    description: The ID of the ruleset.
    type: string
    example: 12345678901234asdfasfasdf
  name: 
    description: The name of the ruleset. 
    type: string
    example: MRT Rules
  lastUpdated:
    description: Date when the ruleset was last updated.
    type: datetime
    example: 2022-01-01T05:20:00Z
  rules:
    description: The rules defined by the ruleset.
    type: array
    items: MRTRules