#%RAML 1.0 DataType
description: POST request for creating MRT rules. MRT rules are a way to route certain storefront requests to the managed runtime instance.
type: object
properties:
  mrtHostname:
    description: The customer's MRT instance hostname. 
    type: string
    example: customer-react-projec-production.mobify-storefront.com
  expressions:
    description: An array containing the expressions for each MRT rule.
    type: string[]
    example: ["(http.host eq \"dev-customer.salesforce.com\" and not ( http.request.uri.path matches \"^/path1/.*\" or http.request.uri.path matches \"^.*/path2/.*/products/.*\"))"]