#%RAML 1.0 DataType
description: mTLS certificate request information.
type: object
properties:
  certificate:
    description: Public key for the CA certificate in mTLS.
    type: string
    required: true
  privateKey:
    description: Private key of the CA certificate in mTLS.
    type: string
    required: true
  name:
    description: Certificate name used for ease of understanding.
    type: string
    required: true
