#%RAML 1.0 DataType
description: Update a rate limiting rule.
type: object 
properties:
  description:
    description: The description of the rate limiting rule.
    type: string
    example: Rate limit /path1.
    required: false
  expression:
    description: The expression that defines when to evaluate the rate limiting rule.
    type: string
    example: (http.request.uri.path matches \"^/path1/.*\")
    required: false
  characteristics:
    description: Set of parameters defining how to group requests when tracking the request rate.
    type: string[]
    example: ["cf.unique_visitor_id"]
    required: false
  action:
    description: The action applied by the rate limiting rule. Valid actions are "block", "managed_challenge", "js_challenge", "legacy_captcha", and "log".
    type: string
    example: block
    required: false
  period:
    description: The period of time to consider when evaluating the request rate (in seconds). Valid values are 10, 60, 120, 300, and 600.
    type: integer
    example: 60
    required: false
  requestsPerPeriod:
    description: The limit for the number of requests in the specified period of time.
    type: integer
    example: 50
    required: false
  mitigationTimeout:
    description: Once the rate is reached, the rate limiting rule applies the rule action to further requests for the period of time defined in this field (in seconds). Only applicable for "block" and "log" actions. Valid values are 60, 120, 300, 600, 3600, and 86400.
    type: integer
    example: 600
    required: false
  countingExpression:
    description: The expression that defines what kind of requests we want to rate limit.
    type: string
    example: (http.request.uri.path matches \"^/path1/.*\" and http.response.code eq 400)
    required: false
  enabled:
    description: Whether or not the rate limiting rule is enabled.
    type: boolean
    example: true
    required: false
  position:
    description: Used to specify the position in the ruleset at which to insert the rate limiting rule.
    type: RulePosition
    required: false