#%RAML 1.0 DataType
description:
type: object
properties:
  id:
    description:
    type: string
    example: someId
  value:
    description:
    type: !include StrictTransportSecurity.raml
  modifiedOn:
    description: When the security zone was last modified.
    type: datetime
    example: 2022-01-12T04:15:57Z
