#%RAML 1.0 DataType
properties:
  brotliCompression:
    type: string
    description: Brotli compression setting of a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
  http2Prioritization:
    type: string
    description: Http2 prioritization setting for a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
    example: off

examples:
  brotliCompressionExample:
    brotliCompression: on
  http2PrioritizationExample:
    http2Prioritization: off