#%RAML 1.0 DataType
properties:
  brotliCompression:
    type: string
    description: Brotli compression setting of a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
  http2Prioritization:
    type: string
    description: Http2 prioritization setting for a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
    example: off
  webp:
    type: string
    description: WebP setting for a zone, valid values are "on" and "off".  This property cannot be modified if 'polish' property is set to 'off'.
    required: false
    default: off
    enum: ["on", "off"]
    example: off      
  polish:
    type: string
    description: Polish level setting for a zone, valid values are "lossless", "lossy" and "off".  Property must be set to 'on' to make update 'webp' property.
    required: false
    default: off
    enum: [off, lossless, lossy]
    example: off 
  minifyJs:
    type: string
    description: Minify JS for a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
    example: off    
  minifyHtml:
    type: string
    description: Minify html for a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
    example: off       
  minifyCss:
    type: string
    description: Minify JS for a zone, valid values are "on" and "off".
    required: false
    default: off
    enum: ["on", "off"]
    example: off

examples:
  brotliCompressionExample:
    brotliCompression: off
  http2PrioritizationExample:
    http2Prioritization: off
  polishExample: 
    polish: off
  webpExample: 
    webp: off
  minifyJsExample: 
    minifyJs: off    
  minfyHtmlExample: 
    minfyHtml: off    
  minifyCssExample: 
    minifyCss: off

    