#%RAML 1.0 DataType
description: The storefront zone information to be created.
type: object
properties:
  domainName:
    required: true
    description: Domain name for the site.
    type: string
    example: cc-merchant.com
    