#%RAML 1.0 DataType
description: The response of create zone, includes zone and zone properties.
type: object
properties:
  zoneId:
    description: The zone id tag.
    type: string
    example: 023e105f4ecef8ad9ca31a8372d0c353
  zoneName: 
    description: The domain name for the zone.
    type: string
    pattern: ^([a-zA-Z0-9][\-a-zA-Z0-9]*\.)+[\-a-zA-Z0-9]{2,20}$
    example: stg-zzzz-cc-merchant-com.cc-ecdn.net
  status:
    description: current status of the zone
    type: string
    enum: [active, pending, initializing, moved, deleted, deactivated]
    example: active
  createdOn:
    description: Date and time of zone creation. 
    type: datetime
    example: 2014-01-01T05:20:00.12345Z