#%RAML 1.0 DataType
properties:
  groupId?:
    type: string
    maxLength: 100
    example: 372e67954025e0ba6aaa6d586b9e0b60
  action?:
    type: string
    enum: ["block", "challenge", "monitor", "default"]
    description: The action to apply to WAF group
    example: block
  mode:
    type: string
    enum: ["on", "off"]
    description: Mode of the waf rule - on vs off
    example: on
  description?:
    type: string
    description: Description of the WAF Group.
    example: "Test WAF Group to protect against SQL injection"

examples:
  example1:
    groupId: 372abe67954025e0ba6aaa6d586b9e0b
    zoneId: example1-zone-Id
    action: monitor
    mode: on
    description: SQL injection protection
  example2:
    groupId: 396abe67954025e0ba6bde6d586b9e5a
    zoneId: example2-zone-Id
    action: challenge
    mode: off
    description: xss attack protection