#%RAML 1.0 DataType
description: A PATCH request for updating a WAF managed rule.
type: object
properties:
  action:
    description: The action applied by the WAF managed rule.
    type: string
    example: block
    required: false
  enabled:
    description: Whether or not the WAF managed rule is enabled.
    type: boolean
    example: true
    required: false