#%RAML 1.0 NamedExample
value:
  {
    "data": [
        {
            "name": "Managed Ruleset",
            "rulesetId": "efb7b8c949ac4650a09736fc376e9aee",
            "action": "default",
            "enabled": true
        },
        {
            "name": "OWASP Core Ruleset",
            "rulesetId": "4814384a9e5d4991b9815dcfc25d2f1f",
            "action": "log",
            "anomalyScoreThreshold": 25,
            "anomalyScore": "high",
            "paranoiaLevel": 1,
            "enabled": true
        },
        {
            "name": "Leaked Crednetials Check Ruleset",
            "rulesetId": "c2e184081120413c86c3ab7e14069605",
            "action": "block",
            "enabled": true
        }
    ]
  }