#%RAML 1.0 NamedExample
value:
  {
    "data": [
      {
        "ruleId": "ef9520b6b08b4e279a6bf67286aa4371",
        "action": "block",
        "categories": [
          "broken-access-control",
          "wordpress"
        ],
        "description": "Wordpress - Broken Access Control",
        "lastUpdated": "2024-04-15T16:49:28.423829Z",
        "enabled": true
      },
      {
        "ruleId": "20e34d3164a340dbb5c5d29203ccff90",
        "action": "block",
        "categories": [
          "broken-access-control",
          "wordpress"
        ],
        "description": "Wordpress - Broken Access Control - Update Script",
        "lastUpdated": "2024-04-15T16:49:28.423829Z",
        "enabled": true
      }
    ]
  }