#%RAML 1.0 NamedExample
value:
  {
    "data": [
        {
            "ruleId": "8ac8bc2a661e475d940980f9317f28e1",
            "action": "block",
            "score": 5,
            "categories": [
                "application-multi",
                "attack-generic",
                "capec-1000",
                "capec-210",
                "capec-220",
                "capec-272",
                "capec-274",
                "language-multi",
                "paranoia-level-1",
                "pci-12-1",
                "platform-multi"
            ],
            "description": "911100: Method is not allowed by policy",
            "lastUpdated": "2024-08-19T17:26:58.593021Z",
            "enabled": false
        },
        {
            "ruleId": "53065ac9bd9449f3895f1865467a0e6a",
            "action": "block",
            "score": 5,
            "categories": [
                "application-multi",
                "attack-reputation-scanner",
                "capec-1000",
                "capec-118",
                "capec-224",
                "capec-310",
                "capec-541",
                "language-multi",
                "paranoia-level-1",
                "pci-6-5-10",
                "platform-multi"
            ],
            "description": "913100: Found User-Agent associated with security scanner",
            "lastUpdated": "2024-08-19T17:26:58.593021Z",
            "enabled": true
        }
    ]
  }