#%RAML 1.0 NamedExample
value:
  {
    "data": {
      "ruleId": "ef9520b6b08b4e279a6bf67286aa4371",
      "action": "log",
      "categories": [
        "broken-access-control",
        "wordpress"
      ],
      "description": "Wordpress - Broken Access Control",
      "lastUpdated": "2024-04-15T16:49:28.423829Z",
      "enabled": true
    }
  }