#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-update-read-only",
  "title": "Coupon Update Read Only",
  "detail": "The coupon field 'system_codes_config/coupon_code_prefix' in coupon 'foo' can't be updated. Once a coupon is redeemed or exported, certain fields can no longer be edited.",
  "couponId": "foo",
  "field": "system_codes_config/coupon_code_prefix"  
}