#%RAML 1.0 DataType

description: The group array items contained in a location graph export
type: object
properties:
  id: 
    type: string
    required: true
    example: 8ae8b814-0b28-4710-8c3c-8ed95abed62e
  locations:
    required: true
    type: array
    items: string
    examples:
      ex1: [l4b17f6a0-b4e6-43a1-bfee-a4a2db37b3f2]
      ex2: [ld3b3090b-11c0-4c7d-bb5f-0ca88c7da8f8]
      ex3: [ld3b3090b-11c0-4c7d-bb5f-0ca88c7da8f8, l4b17f6a0-b4e6-43a1-bfee-a4a2db37b3f2]