#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 400 - Bad Request.

responses:
  400:
    description: |
      The request sent by the caller is not valid.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/bad-request-example.raml