#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 403 - Access Forbidden exception.

responses:
  403:
    description: |
      The caller does not have access to requested resource.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/forbidden-access-example.raml