#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 500 - Internal Server Error response.

responses:
  500:
    description: An error occurred on the server side.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/internal-server-error-example.raml