#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 500 - Internal Server Error response.

uses:
  ApiStandards: ../exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.6/api-standards.raml
  
responses:
  500:
    description: |
      An error occurred on the server side.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/internal-server-error-example.raml