#%RAML 1.0 Trait

usage: |
  To be applied to the **response** on endpoints that can send back a 404 - Resource Not Found exception.

responses:
  404:
    description: |
      The resource requested by the caller was not found.
    body:
      application/problem+json:
        type: ApiStandards.ErrorResponse
        example: !include ../examples/error/resource-not-found-example.raml