#%RAML 1.0 NamedExample
{ 
  "data" : [
    {
      "date": "2022-01-01T00:00:00Z",
      "cacheStatus" : "HIT",
      "count" : 200
    },
    {
      "date": "2022-01-01T00:00:00Z",
      "cacheStatus" : "MISS",
      "count" : 100
    },
    {
      "date": "2022-01-01T00:00:00Z",
      "cacheStatus" : "EXPIRED",
      "count" : 100
    },{
      "date": "2022-01-02T00:00:00Z",
      "cacheStatus" : "HIT",
      "count" : 200
    },
    {
      "date": "2022-01-02T00:00:00Z",
      "cacheStatus" : "MISS",
      "count" : 100
    },
    {
      "date": "2022-01-02T00:00:00Z",
      "cacheStatus" : "EXPIRED",
      "count" : 100
    },
    {
      "date": "2022-01-03T00:00:00Z",
      "cacheStatus" : "HIT",
      "count" : 200
    },
    {
      "date": "2022-01-03T00:00:00Z",
      "cacheStatus" : "MISS",
      "count" : 100
    },
    {
      "date": "2022-01-03T00:00:00Z",
      "cacheStatus" : "EXPIRED",
      "count" : 100
    }
  ]
}