#%RAML 1.0 NamedExample

value:
  {
    "data": [
      {
        "firewallruleId": "3cc2523177bd4bc68e0065c3baf5e283",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "type": "ip",
        "action": "blocklist",
        "values": ["10.0.0.2/16"]
      },
      {
        "firewallruleId": "1044cb26a5d94e58b2d08d1ad246d038",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "type": "country",
        "action": "blocklist",
        "values": ["SU"]
      },
      {
        "firewallruleId": "8eccf2baf52a45668b4524aaa2546e60",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "type": "ip",
        "action": "allowlist",
        "values": ["10.0.0.1/16"]
      },
      {
        "firewallruleId": "e60bbc2c7a674ccf9754e76a1ee1924c",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "type": "country",
        "action": "allowlist",
        "values": ["US"]
      }
    ]
  }