#%RAML 1.0 NamedExample
value :
  {
    "data": {
      "destinationPath": "s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256",
      "fileName": "site-name/20230101/ownership-challenge-f1234567.txt"
    }
  }