#%RAML 1.0 NamedExample
value:
  {
    "name": "example-job-name-with-filter",
    "destinationPath": "s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256",
    "ownershipChallengeToken": "abc00000000000000000000",
    "logFields" : ["ClientRequestBytes", "ClientRequestPath", "ClientRequestHost", "ClientRequestMethod", "EdgeResponseStatus"],
    "filter": "{\"where\":{\"and\":[{\"key\":\"ClientRequestPath\",\"operator\":\"contains\",\"value\":\"/example-path\"}, {\"key\":\"EdgeResponseStatus\",\"operator\":\"in\",\"value\":[502, 503, 504, 520, 521, 522, 522, 523, 524, 525, 526, 530]}]}}",
    "logType" : "http_requests"
  }