#%RAML 1.0 NamedExample
value:
  {
    "data":
      {
        "jobId": 123456,
        "name": "example-job-name",
        "logType" : "http_requests",
        "logFields" : ["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"],
        "destinationPath": "s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256",
        "lastComplete": "2023-03-14T02:09:32Z",
        "createdOn" : "2023-01-01T00:00:27Z"
      }
  }