#%RAML 1.0 NamedExample
value:
  {
    "type": "credentials",
    "password": "12345!aBcD",
    "customer": {
      "login": "jsmith",
      "email": "jsmith@test.com",
      "lastName": "Smith"
    }
  }