#%RAML 1.0 DataType

# Added for work performed in W-7535728

description: Used for identifying the group when moving a reservation to a group.
properties:
  group:
    type: string
    example: Canada