#%RAML 1.0 DataType

 # Added for work performed in W-7535728
description: Detail line info for an error generated during the move of a reservation.
properties:
  id: 
    type: string
    example: 82251928-8863-488e-840b-2aebd10b57ba
  externalRefId: 
    type: string
    example: 7282822-9823-aaa
  from:
    type: string
    examples:
      ex1: "group: UnitedStates"
      ex2: "location: warehouse4"
  to:
    type: string
    examples:
      ex1: "group: Cananda"
      ex2: "location: warehouse5"
  sku:
    type: string
    example: sku-001
  quantity:
    type: number
    example: 2.011

