#%RAML 1.0 DataType

description: Error generated during a move of a reservation.
properties:
  details:
    type: MoveReservationErrorDetail
  message:
    type: string
    example: "MoveError"
  errorCode:
    type: string
    example: "error750"