#%RAML 1.0 DataType

description: Whether or not to allow partial reservations. The default value is 'true'.  If the value sent in is 'true', or no value is sent, the response will only include the quantity that was available to be reserved.  There will be no error message.  In this case, the response must be verified by the caller.
type: boolean
example: true