#%RAML 1.0 DataType

description: |
  The number of seconds until this reservation expires. If not specified, this  reservation never expires. 
  
  Typically, there’s about a 10-15 second delay between the specified expiration time and its reflection on inventory counts under normal load, but usually stays within 60 seconds under higher loads. 
type: integer
example: 300
minimum: 1