#%RAML 1.0 DataType

description: Whether or not to fulfill a reservation ONLY against the ATF amount. The default value is 'false'.  If the value sent in is 'false', or no value is sent, the reservations will apply normally.  If the value is sent as 'true', the reservation will ONLY be placed against the ATF amount and will fail if this amount is insufficient to fulfill the reservation request.
type: boolean
example: true