#%RAML 1.0 DataType

description: Enum for the error code values that can be expected when placing a reservation.

type:
  description: The error code.
  type: string 
  enum: [InsufficientQuantity, Unknown]
  example: InsufficientQuantity