#%RAML 1.0 DataType

description: The reservations to request at the location group.
properties:
  id:
    type: !include GlobalTypes/GroupId.raml
  reservations:
    required: true
    type: array
    items:
      type: !include ReservationRequestRecord.raml