#%RAML 1.0 DataType
description: Reserved items at the location group.

properties:
  id:
    type: !include GlobalTypes/GroupId.raml
  items:
    type: array
    items: !include ReservedReservationRecord.raml