#%RAML 1.0 DataType

type:
  type: string
  # we only allow the status of a Reservation document to be set to
  # Cancelled, so we're restricting it here with an ENUM
  enum: [CANCELLED]
  example: CANCELLED