#%RAML 1.0 DataType

description: Reserved items at the location.
properties:
  id:
    type: !include GlobalTypes/LocationId.raml
  items:
    type: array
    items: !include ReservedReservationRecord.raml