#%RAML 1.0 DataType

description: Information about the SKU, and quantity to reserve.
properties:
  sku:
    type: !include GlobalTypes/SkuId.raml
    required: true
    minLength: 1
  quantity:
    type: !include GlobalTypes/ReservedQuantity.raml
    required: true
    minimum: 0.001