#%RAML 1.0 NamedExample
value :
  {
    "enabled" : true,
    "filter" : "{\"where\":{\"key\":\"ClientRequestPath\",\"operator\":\"contains\",\"value\":\"/example-path\"}}",
    "logFields" : ["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"]
  }