#%RAML 1.0 NamedExample
value:
  {
    "data": [
      {
        "jobId": 123456,
        "name": "example1-job-name",
        "logType" : "http_requests",
        "logFields" : ["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"],
        "destinationPath": "s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256",
        "lastComplete": "2023-03-14T02:09:32Z",
        "createdOn" : "2023-01-01T00:00:27Z"
      },
      {
        "jobId": 123457,
        "name": "example2-job-name",
        "logType" : "firewall_events",
        "logFields" : ["RuleID", "ClientRequestUserAgent", "ClientRequestPath"],
        "filter": "{\"where\":{\"and\":[{\"key\":\"ClientRequestPath\",\"operator\":\"contains\",\"value\":\"/example-path\"}, {\"key\":\"EdgeResponseStatus\",\"operator\":\"in\",\"value\":[502, 503, 504, 520, 521, 522, 522, 523, 524, 525, 526, 530]}]}}",
        "destinationPath": "s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256",
        "lastComplete": "2023-03-22T02:09:32Z",
        "createdOn" : "2023-01-03T00:00:27Z"
      }
    ]
  }
