#%RAML 1.0 NamedExample
value:
  {
  "limit": 3,
  "expand":
    [
      "stats"
    ],
  "offset": 0,
  "total": 50,
  "data": [
    {
      "code": "CodeA",
      "issued": false,
      "redemptionCount": 0
    },
    {
      "code": "CodeB",
      "issued": false,
      "redemptionCount": 0
    },
    {
      "code": "CodeC",
      "issued": false,
      "redemptionCount": 0
    }
  ]
  }