#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/site-access-forbidden",
  "title": "Site Access Forbidden",
  "detail": "Site-specific access via '/s/RefArch/' isn't allowed. Organization-specific access is expected via '/s/-/'.",
  "siteId": "RefArch"
  }