#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-code-duplicate",
  "title": "Coupon Code Duplicate",
  "detail": "The coupon code 'bar' is already used in coupon 'foo'. Please make sure the code is unique.",
  "couponId": "foo",
  "couponCode": "bar"
  }