#%RAML 1.0 NamedExample

value:
  {
    "data":
      {
        "groupId": "f90712123fb02287348dd34c0a282bb9",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "mode": "on",
        "description": "This WAF Group contains a number of rules that have been created to deal with specific attack types. "
      }
  }