#%RAML 1.0 NamedExample

value:
  {
    "data": [
      {
        "ruleId": "100001",
        "groupId": "f90712123fb02287348dd34c0a282bb9",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "action": "monitor",
        "defaultAction": "challenge",
        "description": "Anomaly:Header:User-Agent - Missing"
      },
      {
        "ruleId": "100002",
        "groupId": "f90712123fb02287348dd34c0a282bb9",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "action": "monitor",
        "defaultAction": "challenge",
        "description": "DoS - IE6 Binary POST"
      },
      {
        "ruleId": "100002A",
        "groupId": "f90712123fb02287348dd34c0a282bb9",
        "zoneId": "e4288c0a1f80fa5490b598d74c69bde4",
        "action": "monitor",
        "defaultAction": "challenge",
        "description": "DoS - CtrlFunc Botnet"
      }
    ]
  }