#%RAML 1.0 NamedExample
value:
  {
    "title": "Customer Temporary Baskets Quota Exceeded",
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/customer-temporary-baskets-quota-exceeded",
    "detail": "The maximum number of temporary baskets per customer was exceeded. Please reuse or delete one of the existing temporary baskets (40e91e04aba6e42a6836f79308, 73ca0f0860a67df946782c2688).",
    "basketIds": "40e91e04aba6e42a6836f79308, 73ca0f0860a67df946782c2688"
}