#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-code-not-redeemable",
  "title": "Coupon Code Not Redeemable",
  "detail": "The coupon code 'CODE374' in site 'RefArch' is not redeemable because 'COUPON_DISABLED'.",
  "errorCode": "COUPON_DISABLED",
  "couponCode": "CODE374",
  "siteId": "RefArch"
  }