#%RAML 1.0 NamedExample
value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-not-found",
    "title": "Coupon Not Found",
    "detail": "No coupon for the given coupon code 'CODE374' and site 'RefArch' could be found.",
    "couponCode": "CODE374",
    "siteId": "RefArch"
  }