#%RAML 1.0 NamedExample
#title: category-search-body
value:
  {
    "start": 0,
    "count": 50,
    "query": {
        "boolQuery": {
            "should": [
                {
                    "textQuery": {
                        "searchPhrase": "Luggage",
                        "fields": [
                            "name"
                        ]
                    }
                }
            ]
        }
    }
  }