#%RAML 1.0 NamedExample
#title: catalogcategoryprodAssignment-body
value:
  {
    
      "catalogId": "apparel-catalog",
      "categoryId": "kids-wear",
      "productId": "apple-ipod-shuffle",
      "position": 1.0

  }