#%RAML 1.0 NamedExample
#title: category-search-body
value:
  {   "query" : { 
          "termQuery": { 
              "fields" : ["is_storefront_catalog"], 
              "operator" : "is",
              "values" : [true] 
          }
      },
      "select" : "(**)" 
  }