#%RAML 1.0 NamedExample
# this example is for the Data Category_Search body
value:
  {  "query" : { 
        "termQuery": { 
            "fields" : ["online"], 
            "operator" : "is",
            "values" : [false] 
        }
    }
  }