#%RAML 1.0 NamedExample
#title: category_product_assignment
value:
  {
   "hits":[
      {
         "catalogId":"NTOCatalog",
         "categoryId":"NTOFirstClassCategory",
         "creationDate":"2024-05-27T10:11:48.000Z",
         "lastModified":"2024-05-27T10:11:48.000Z",
         "owningCatalogName":{
            "default":"NTO Product Image Catalog"
         },
         "product":{
            "assignedCategories":[
               {
                  "catalogId":"NTOCatalog",
                  "categoryId":"NTOFirstClassCategory"
               }
            ],
            "brand":"Wapi brand",
            "creationDate":"2024-05-27T10:11:45.000Z",
            "id":"NTOSimpleBundle",
            "image":{
               "absUrl":"https://www.yoursecureimageserver.com/foo/bar/bundle_image_detail.jpg",
               "alt":{
                  "default":"ALT bundle image detail"
               },
               "path":"bundle_image_detail.jpg",
               "title":{
                  "default":"TITLE bundle image detail"
               }
            },
            "onlineFlag":{
               "default":true
            },
            "searchable":{
               "default":true
            }
         },
         "productId":"NTOSimpleBundle",
         "productName":{
            "default":"Simple Web API Bundle"
         }
      }
   ],
   "query":{
      "TermQuery":{
         "fields":[
            "product_id"
         ],
         "operator":"is",
         "values":[
            "NTOSimpleBundle"
         ]
      }
   },
   "limit":1,
   "offset":0,
   "total":1
}