#%RAML 1.0 NamedExample
#title: category_product_assignment
value:
  {
    "hits": [
      {
        "catalogId": "apparel-catalog",
        "categoryId": "mens-clothing-outerwear",
        "owningCatalogName": {
          "default": "Apparel Master Catalog"
        },
        "productId": "11736753",
        "productName": {
          "default": "Summer Bomber Jacket"
        },
        "product": {
          "image": {
            "alt": {
              "default": "Summer Bomber Jacket, , large"
            },
            "path": "large/B0574182_001_0.jpg",
            "title": {
              "default": "Summer Bomber Jacket, "
            }
          },
          "type": {
            "master": true
          }
        }
      },
      {
        "catalogId": "apparel-catalog",
        "categoryId": "mens-clothing-outerwear",
        "owningCatalogName": {
          "default": "Apparel Master Catalog"
        },
        "productId": "62516752",
        "productName": {
          "default": "Casual Spring Easy Jacket"
        },
        "product": {
          "image": {
            "alt": {
              "default": "Casual Spring Easy Jacket, , large"
            },
            "path": "large/B0374107_DL0_0.jpg",
            "title": {
              "default": "Casual Spring Easy Jacket, "
            }
          },
          "type": {
            "master": true
          }
        }
      }
    ],
    "query": {
        "boolQuery": {
            "should": [
                {
                    "textQuery": {
                        "searchPhrase": "Jacket",
                        "fields": [
                            "product_name"
                        ]
                    }
                }
            ]
        }
    },
    "limit": 2,
    "offset": 0,
    "total": 2
  }