#%RAML 1.0 NamedExample
value:
  {
    type: "evaluation",
    "total": 5,
    "jobStatus": "success",
    "productIds": [ 
      "25772792",
      "25772717"
    ],
    "limit": 2,
    "offset": 3
  } 