#%RAML 1.0 NamedExample
value:
  {
    "id": "NameCondition",
    "attributeKey": "name",
    "attributeValue": [
        "Shirt"
      ],
    "attributeName": "name",  
    "operator": "starts_with"
  }