#%RAML 1.0 NamedExample
# title: product-assignment-body-example
value:
  {
  "query": {
    "term_query": {
      "fields": [
        "product_id"
      ],
      "operator": "is",
      "values": [
        "NTOSimpleBundle"
      ]
    }
  },
  "expand": [
    "product_categories",
    "product_images"
  ]
}