#%RAML 1.0 NamedExample

value:
  {
  "catalogId": "apparel-catalog",
  "creationDate": "2019-02-21T22:09:40.000Z",
  "id": "mens",
  "lastModified": "2019-09-04T15:07:14.000Z",
  "online": true,
  "parentCategoryId": "root",
  "position": 2.0
}
