#%RAML 1.0 NamedExample

value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unauthorized",
    "title": "UnAuthorized Access",
    "detail": "The authorization token passed is no longer valid"
  }