#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in Data Catalogs API.
responses:
  404:
    description: |
            Requested resource not found.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Catalog Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/catalog-not-found",
            "detail": "No catalog with ID '095c2082-5f2a-47d5-bc73-27d06c5c9db8' could be found.",
            "catalogId": "095c2082-5f2a-47d5-bc73-27d06c5c9db8"
          }
