#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in Data Catalogs API.
responses:
  404:
    description: |
            Requested resource not found.
    body:
      application/json:
        type: Error
        example: |
          {
            "type": "CatalogNotFoundException",
            "title": "No catalog with ID 'blah' for site 'SiteGenesis' could be found.",
            "detail": "Blah",
            "instance": "/blah"
          }
