#%RAML 1.0 NamedExample
value:
  {
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/coupon-legacy-update-forbidden",
  "title": "Coupon Legacy Update Forbidden",
  "detail": "The coupon 'foo' can't be modified because it was created before Release 16.7.2. Customers can still redeem this coupon code on the Storefront.",
  "couponId": "foo"
  }