#%RAML 1.0 DataType

type: string
description: The URI to be used for accessing the export status
example: "https://inv-service.com/inventory/inventory-availability/status?exportIds=d88e54c5-23ed-4e33-a6a9-c31dc810662b"