#%RAML 1.0 DataType

description: Common response from export events activity initiation calls
properties:
  exportId: 
    type: string
    description: The ID associated with the initiated export
    example: e-d88e54c5-23ed-4e33-a6a9-c31dc810662b
  exportStatusLink:
    type: string
    description: URI where export status can be acquired
    example: "/inventory/impex/v1/organizations/testOrg/event-log/exports/e-d88e54c5-23ed-4e33-a6a9-c31dc810662b/status"