#%RAML 1.0 DataType

description: Error message generated after a failed fulfillment.
properties:
  details:
    type: !include FulfillReservationErrorDetail.raml
  message:
    description: Error message
    type: string
    example: Fulfillment failed - invalid location provided
  errorCode:
    description: The error code associated with this error
    type: string
    example: err751