#%RAML 1.0 DataType

description: The records provided in a fulfillment request.

properties:
  id:
    type: !include ../GlobalTypes/IdempotenceId.raml
  externalRefId:
    required: false 
    type: !include ../GlobalTypes/ExternalRefId.raml
  location:
    type: !include ../GlobalTypes/LocationId.raml
    required: true
  sku:
    type: !include ../GlobalTypes/SkuId.raml
    required: true
    minLength: 1
  quantity:
    description: Must be a positive value
    type: !include ../GlobalTypes/QOH.raml
    required: true
    minimum: 0.001
    example: 1200.35
  fulfillmentTime:
    description: The time the fulfillment takes place
    type: datetime
    format: rfc3339
    required: false
    example: 2019-07-24T21:13:00Z
