#%RAML 1.0 DataType

description: Errors generated during the delete process on an event log
type: object
properties:
  id:
    type: string
    example: a94a8fe5-ccb1-9ba6-1c4c-0873d3943215
  message:
    type: string
    example: Failed to delete event log
  errorCode:
    type: string
    example: err204