#%RAML 1.0 DataType

description: Export event log download link data

properties:
  downloadLink: 
    description: The URI link to be used for retrieving the event log export file. This link is valid anytime after the status of the export is completed and the link has not expired.
    type: string
    example: https://inv-service-host.com/inventory/inventory-availability/v1/organizations/AtsisIntegrationTenant/event-log/exports/a218f4b2-2dc3-4ea8-af6d-c75fafd62323/file-content
  downloadLinkExpirationUTC: 
    description: The time at which the download link will expire, in UTC time.
    type: !include ../GlobalTypes/Date.raml
    example: 2019-02-12T13:23:51Z