#%RAML 1.0 DataType
description: Simple record included in event log export

# reserve the right to add to this record in future releases if it is determined that we need additional info in this record

type: object

properties:
  EventType:
    description: The type associated with this event
    type: string
    example: "INSERT"
  ExternlRefId:
    type: !include ../GlobalTypes/ExternalRefId.raml
  EventDate:
    type: !include ../GlobalTypes/Date.raml
  LocationId:
    type: !include ../GlobalTypes/LocationId.raml