#%RAML 1.0 DataType

description: "See the main API documentation for a full description of the content and formatting of the file."
example: "{\"locationId\":\"weimar\"}
\n{\"locationId\":\"newbraunfels\"}
\n{\"eventType\":\"location_import\",\"location\":\"newbraunfels\",\"sequenceNumber\":0,\"quantity\":10.0,\"newReserved\":0.0,\"newAto\":11.0,\"newOnHand\":10.0,\"newAtf\":10.0,\"newSoftReserved\":0.0,\"futureQuantity\":1.0,\"oldReserved\":0.0,\"oldAto\":0.0,\"oldOnHand\":0.0,\"oldAtf\":0.0,\"oldSoftReserved\":0.0,\"createdTime\":\"2022-01-18T15:58:40.443Z\",\"effectiveTime\":\"2020-04-08T14:05:22.795243-07:00\",\"safetyStockCount\":0.0}"
