#%RAML 1.0 DataType

properties:
  name: 
    description: The name of the attribute
    type: string
    example: color
  value:
    description: The value of the attribute
    type: string
    example: red