name: Publish to NPM

on:
  release:
    types: [published] # Releases to NPM when a github release is created
  workflow_dispatch: # in case we need to manually publish

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install snyk --legacy-peer-deps
      - run: npm run snyk:auth ${{ secrets.SNYK_TOKEN }}
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
