#%RAML 1.0 NamedExample
value:
  {
      "limit": 1,
      "data": [
          {
              "id": "ProductType",
              "attributeName": "Product Type",
              "allowedOperators": [
                  "equals",
                  "not_equals"
              ],
              "allowedValues": [
                "Item",
                "Master",
                "BundledProduct",
                "ProductSet",
                "SetProduct",
                "VariationGroup",
                "VariationProduct"
              ],
              "allowedDisplayValues": [
                "Item",
                "Master",
                "BundledProduct",
                "ProductSet",
                "SetProduct",
                "VariationGroup",
                "VariationProduct"
              ],
              "attributeType": "categorization",
              "valueType": "enum-of-string"
          },
          {
              "id": "CategoryId",
              "attributeName": "Category Id",
              "allowedOperators": [
                  "equals"
              ],
              "attributeType": "categorization",
              "valueType": "string"
          },
          {
              "id": "OwningCatalogId",
              "attributeName": "Owning Catalog Id",
              "allowedOperators": [
                  "equals"
              ],
              
              "attributeType": "categorization",
              "valueType": "string"
          },
          {
              "id": "brand",
              "attributeName": "Brand",
              "allowedOperators": [
                  "equals",
                  "not_equals",
                  "contains",
                  "starts_with",
                  "is_defined",
                  "is_not_defined",
                  "is_one_of",
                  "not_one_of"
              ],
              "attributeType": "system",
              "valueType": "string"
          },
          {
              "id": "RelevanceAttribute1",
              "attributeName": "RelevanceAttribute1",
              "allowedOperators": [
                  "equals",
                  "not_equals",
                  "contains",
                  "starts_with",
                  "is_defined",
                  "is_not_defined",
                  "is_one_of",
                  "not_one_of"
              ],
              "attributeType": "custom",
              "valueType": "string"
          }
      ],
      "total": 5
  }