#%RAML 1.0 NamedExample
value:
  {
    "limit": 4,
    "data": [
        {
            "productId": "apple-ipod-classic-silver-120g",
            "variation_values": {
                "color": "Silver",
                "memorySize": "120 GB"
            }
        },
        {
            "productId": "apple-ipod-classic-black-120g",
            "variation_values": {
                "color": "Black",
                "memorySize": "120 GB"
            }
        },
        {
            "productId": "apple-ipod-classic-2"
        },
        {
            "productId": "apple-ipod-classic-blue-32g",
            "variation_values": {
                "color": "Blue",
                "memorySize": "32 GB"
            }
        }
    ],
    "offset": 0,
    "total": 4
}