#%RAML 1.0 NamedExample
value:
  {
    "query" : {
          "textQuery": {
              "fields": ["id"],
              "searchPhrase": "ipod"
          }
      },
      "expand": ["variations"]
  }