#%RAML 1.0 NamedExample
value:
  {
    "orderable": true,
    "price": 500.00,
    "productId": "apple-ipod-classic-1",
    "variationValues": {
        "color": "Silver",
        "memorySize": "120 GB"
    }
  }