#%RAML 1.0 Trait
description: This trait represents API behavior for a 201 response when a create operation was successful and no content is returned.

responses:
  201:
    description: |
      The object has been created, no content is returned.
    headers:
      Location: 
        description: |
          The location to access the created resource.
        example: |
          /baskets/1fd9bf3fc49cd5c626665088a1/price-adjustments/fcf9f3167d05d0de1184977f04