#%RAML 1.0 Trait
description: This trait represents a successfully retrieved basket.

uses:
  DataTypes: ../data-types.raml
  
responses:
  200:
    description: |-
      The operation was successful.
    body:
      application/json:
        type: DataTypes.Basket
        examples:
          Basket: !include ../examples/basket-get-response.raml
