#%RAML 1.0 Trait
description: This trait represents a successfully retrieved price adjustment.

uses:
  DataTypes: ../data-types.raml
  
responses:
  200:
    description: |-
      The operation was successful.
    body:
      application/json:
        type: DataTypes.PriceAdjustment
        examples:
          PriceAdjustment: !include ../examples/price-adjustment-get-response.raml
          PriceAdjustmentWithEligibleProducts: !include ../examples/price-adjustment-get-response-with-eligible-products.raml
