#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response when a price adjustment was not found.

responses:
  404:
    description: |
      The given price adjustment identifier does not reference an existing price adjustment.
    body:
      application/json:
        type: ErrorResponse
        example: |
          {
            "title": "Price Adjustment not found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/price-adjustment-not-found",
            "detail": "No price adjustment with ID 'bczFTaOjgEqUkaaadkvHwbgrP5' could be found."
          }
