#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response when a product item was not found.

responses:
  404:
    description: |
      The given product item identifier does not reference an existing product item.
    body:
      application/json:
        type: ErrorResponse
        example: |
          {
            "title": "Product Item not found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/product-item-not-found",
            "detail": "No product item with ID 'bczFTaOjgEqUkaaadkvHwbgrP5' could be found."
          }
