#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response when a site was not found.

responses:
  404:
    description: |
      The given site ID does not reference an existing site.
    body:
      application/json:
        type: ErrorResponse
        example: |
          {
            "title": "Site Not Found",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/not-found",
            "detail": "No site with ID 'SiteGnesis' could be found."
          }